// BothArmsWriteDifferentMembers — ported from test/libsolidity/semanticTests/controlFlow/if_else.sol
// Stresses: a branch where each arm writes a different member and neither writes the other's — so a merged or hoisted store shows up as a member that moved when it should not have
// Variant: entryOrder=reversed entryShape=direct initStyle=full placement=nested stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct BothArmsWriteDifferentMembers2
{
};

struct BothArmsWriteDifferentMembers : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 evenPath;
        uint64 oddPath;
        uint64 shared;
        uint64 untouched;
        uint64 calls;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        uint64 value;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.value = input.a;
        if (QPI::mod(locals.value, 2ULL) == 0)
        {
        state.mut().inner.evenPath = locals.value;
        state.mut().inner.shared = locals.value * 2;
        }
        else
        {
        state.mut().inner.oddPath = locals.value;
        state.mut().inner.shared = locals.value * 3;
        }

        state.mut().inner.calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 evenPath;
        uint64 oddPath;
        uint64 shared;
        uint64 untouched;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.evenPath = state.get().inner.evenPath;
        output.oddPath = state.get().inner.oddPath;
        output.shared = state.get().inner.shared;
        output.untouched = state.get().inner.untouched;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.evenPath = 0;
        state.mut().inner.oddPath = 0;
        state.mut().inner.shared = 0;
        state.mut().inner.untouched = 0;
        state.mut().inner.calls = 0;
    }
};
