// EntryNumbersWithGaps — ported from test/libsolidity/semanticTests/functionSelector/function_selector.sol
// Stresses: a sparse registration table
// Port caveat: QPI entry numbers are chosen, not hashed
// Variant: entryOrder=reversed entryShape=direct initStyle=absent placement=nested stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct EntryNumbersWithGaps2
{
};

struct EntryNumbersWithGaps : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 first;
        uint64 fifth;
        uint64 ninth;
        uint64 calls;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 first;
        uint64 fifth;
        uint64 ninth;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.first = state.get().inner.first;
        output.fifth = state.get().inner.fifth;
        output.ninth = state.get().inner.ninth;
        output.calls = state.get().inner.calls;
    }

    struct Ninth_input
    {
        uint64 value;
    };

    struct Ninth_output {};

    struct Ninth_locals
    {
        uint64 scratch;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Ninth)
    {
        state.mut().inner.ninth += input.value * 9;
        state.mut().inner.calls++;
    }

    struct First_input
    {
        uint64 value;
    };

    struct First_output {};

    struct First_locals
    {
        uint64 scratch;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(First)
    {
        state.mut().inner.first += input.value;
        state.mut().inner.calls++;
    }

    struct Fifth_input
    {
        uint64 value;
    };

    struct Fifth_output {};

    struct Fifth_locals
    {
        uint64 scratch;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Fifth)
    {
        state.mut().inner.fifth += input.value * 5;
        state.mut().inner.calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 3);
        REGISTER_USER_PROCEDURE(First, 1);
        REGISTER_USER_PROCEDURE(Fifth, 5);
        REGISTER_USER_PROCEDURE(Ninth, 9);
    }
};
