// GuardedDivisionPaths — ported from test/libsolidity/semanticTests/expressions/division_by_zero.sol
// Stresses: three ways of not dividing by zero — a guard before, QPI::div's own guard, and a substituted divisor — with the three results compared
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full placement=first stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct GuardedDivisionPaths2
{
};

struct GuardedDivisionPaths : public ContractBase
{
    struct StateData
    {
        uint64 calls;
        uint64 zeroDivisors;
        uint64 allAgree;
        uint64 substituted;
        uint64 builtin;
        uint64 guarded;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 guarded;
        uint64 builtin;
        uint64 substituted;
        uint64 allAgree;
        uint64 zeroDivisors;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.guarded = state.get().guarded;
        output.builtin = state.get().builtin;
        output.substituted = state.get().substituted;
        output.allAgree = state.get().allAgree;
        output.zeroDivisors = state.get().zeroDivisors;
        output.calls = state.get().calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    struct RunBody_locals
    {
        uint64 divisor;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RunBody)
    {
        locals.divisor = input.b;
        if (locals.divisor == 0)
        {
        state.mut().guarded = 0;
        state.mut().zeroDivisors++;
        }
        else
        {
        state.mut().guarded = QPI::div(input.a, locals.divisor);
        }
        state.mut().builtin = QPI::div(input.a, locals.divisor);
        state.mut().substituted = QPI::div(input.a, locals.divisor == 0 ? 1ULL : locals.divisor);
        state.mut().allAgree = state.get().guarded == state.get().builtin ? 1 : 0;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().guarded = 0;
        state.mut().builtin = 0;
        state.mut().substituted = 0;
        state.mut().allAgree = 0;
        state.mut().zeroDivisors = 0;
        state.mut().calls = 0;
    }
};
