// LoopShapes — ported from test/libsolidity/semanticTests/statements/for_loop_continue.sol
// Stresses: loop bound shape crossed with accumulator width
// Variant: loopShape=constant width=sint64
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct LoopShapes2
{
};

struct LoopShapes : public ContractBase
{
    struct StateData
    {
        sint64 total;
        uint64 iterations;
        uint64 skipped;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        sint64 total;
        uint64 iterations;
        uint64 skipped;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.total = state.get().total;
        output.iterations = state.get().iterations;
        output.skipped = state.get().skipped;
    }

    struct Sum_input
    {
        uint64 bound;
        uint64 skipEvery;
    };

    struct Sum_output {};

    struct Sum_locals
    {
        uint64 i;
        uint64 bound;
        uint64 count;
        uint64 skips;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Sum)
    {
        // Clamp the bound so the loop is statically bounded whatever the caller sends.
        locals.bound = input.bound;
        if (locals.bound > 64)
        {
        locals.bound = 64;
        }
        locals.count = 0;
        locals.skips = 0;
        for (locals.i = 0; locals.i < 8; locals.i++)
        {
        if (input.skipEvery != 0 && QPI::mod(locals.i, input.skipEvery) == 0)
        {
        locals.skips++;
        continue;
        }
        if (locals.i > 60)
        {
        break;
        }
        state.mut().total += (sint64)locals.i;
        locals.count++;
        }
        state.mut().iterations = locals.count;
        state.mut().skipped = locals.skips;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Sum, 1);
    }

    INITIALIZE()
    {
        state.mut().total = 0;
        state.mut().iterations = 0;
        state.mut().skipped = 0;
    }
};
