// LoopShapes — ported from test/libsolidity/semanticTests/statements/for_loop_continue.sol
// Stresses: loop bound shape crossed with accumulator width
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=full loopShape=zero placement=nested stateOrder=reversed temporaries=locals width=uint32
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct LoopShapes2
{
};

struct LoopShapes : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 skipped;
        uint64 iterations;
        uint32 total;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Sum_input
    {
        uint64 bound;
        uint64 skipEvery;
    };

    struct Sum_output {};

    struct Sum_locals
    {
        Sum_input forwardedInput;
        Sum_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Sum)
    {
        locals.forwardedInput = input;
        CALL(SumBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint32 total;
        uint64 iterations;
        uint64 skipped;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using SumBody_input = Sum_input;

    using SumBody_output = Sum_output;

    struct SumBody_locals
    {
        uint64 i;
        uint64 bound;
        uint64 count;
        uint64 skips;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(SumBody)
    {
        // Clamp the bound so the loop is statically bounded whatever the caller sends.
        locals.bound = input.bound;
        if (locals.bound > 64)
        {
        locals.bound = 64;
        }
        locals.count = 0;
        locals.skips = 0;
        for (locals.i = 0; locals.i < 0; locals.i++)
        {
        if (input.skipEvery != 0 && QPI::mod(locals.i, input.skipEvery) == 0)
        {
        locals.skips++;
        continue;
        }
        if (locals.i > 60)
        {
        break;
        }
        state.mut().inner.total += (uint32)locals.i;
        locals.count++;
        }
        state.mut().inner.iterations = locals.count;
        state.mut().inner.skipped = locals.skips;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.total = state.get().inner.total;
        output.iterations = state.get().inner.iterations;
        output.skipped = state.get().inner.skipped;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Sum, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.total = 0;
        state.mut().inner.iterations = 0;
        state.mut().inner.skipped = 0;
    }
};
