// NestedLoopBreakContinue — ported from test/libsolidity/semanticTests/controlFlow/loops.sol
// Stresses: break and continue at two nesting levels
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=empty loopShape=zero placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct NestedLoopBreakContinue2
{
};

struct NestedLoopBreakContinue : public ContractBase
{
    struct Scratch
    {
        uint64 walkI;
        uint64 walkJ;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 product;
        uint64 broken;
        uint64 skipped;
        uint64 visited;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 visited;
        uint64 skipped;
        uint64 broken;
        uint64 product;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Walk_input
    {
        uint64 n;
    };

    struct Walk_output {};

    struct Walk_locals
    {
        Walk_input forwardedInput;
        Walk_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Walk)
    {
        locals.forwardedInput = input;
        CALL(WalkBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.visited = state.get().inner.visited;
        output.skipped = state.get().inner.skipped;
        output.broken = state.get().inner.broken;
        output.product = state.get().inner.product;
    }

    using WalkBody_input = Walk_input;

    using WalkBody_output = Walk_output;

    PRIVATE_PROCEDURE(WalkBody)
    {
        for (state.mut().inner.scratch.walkI = 0; state.mut().inner.scratch.walkI < 0; state.mut().inner.scratch.walkI++)
        {
        if (QPI::mod(state.mut().inner.scratch.walkI, 3ULL) == 2)
        {
        state.mut().inner.skipped++;
        continue;
        }
        for (state.mut().inner.scratch.walkJ = 0; state.mut().inner.scratch.walkJ < 4; state.mut().inner.scratch.walkJ++)
        {
        if (state.mut().inner.scratch.walkJ > state.mut().inner.scratch.walkI)
        {
        state.mut().inner.broken++;
        break;
        }
        state.mut().inner.visited++;
        state.mut().inner.product += state.mut().inner.scratch.walkI * 4 + state.mut().inner.scratch.walkJ;
        }
        }
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Walk, 1);
    }

    INITIALIZE()
    {

    }
};
