// RangeLadderWithOverlap — ported from test/libsolidity/semanticTests/various/switch_statement.sol
// Stresses: a range ladder whose arms deliberately overlap, so only the order of the tests decides the answer — and a second ladder written in the opposite order for comparison
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full placement=last stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct RangeLadderWithOverlap2
{
};

struct RangeLadderWithOverlap : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        uint64 calls;
        uint64 differ;
        uint64 lastMatch;
        uint64 firstMatch;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 firstMatch;
        uint64 lastMatch;
        uint64 differ;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.firstMatch = state.get().firstMatch;
        output.lastMatch = state.get().lastMatch;
        output.differ = state.get().differ;
        output.calls = state.get().calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    struct RunBody_locals
    {
        uint64 value;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RunBody)
    {
        locals.value = input.a;
        if (locals.value < 1000)
        {
        state.mut().firstMatch = 1;
        }
        else if (locals.value < 100)
        {
        state.mut().firstMatch = 2;
        }
        else if (locals.value < 10)
        {
        state.mut().firstMatch = 3;
        }
        else
        {
        state.mut().firstMatch = 4;
        }
        if (locals.value < 10)
        {
        state.mut().lastMatch = 3;
        }
        else if (locals.value < 100)
        {
        state.mut().lastMatch = 2;
        }
        else if (locals.value < 1000)
        {
        state.mut().lastMatch = 1;
        }
        else
        {
        state.mut().lastMatch = 4;
        }
        if (state.get().firstMatch != state.get().lastMatch)
        {
        state.mut().differ++;
        }

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().firstMatch = 0;
        state.mut().lastMatch = 0;
        state.mut().differ = 0;
        state.mut().calls = 0;
    }
};
