// ShortCircuitSideEffect — ported from test/libsolidity/semanticTests/expressions/short_circuit.sol
// Stresses: short-circuit evaluation order
// Variant: placement=first
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct ShortCircuitSideEffect2
{
};

struct ShortCircuitSideEffect : public ContractBase
{
    struct StateData
    {
        uint64 sideEffects;
        uint64 andResult;
        uint64 orResult;
        uint64 placementGuard;
    };

    struct Evaluate_input
    {
        uint64 left;
        uint64 right;
    };

    struct Evaluate_output {};

    struct Evaluate_locals
    {
        uint64 before;
        uint64 flag;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Evaluate)
    {
        locals.before = state.get().sideEffects;
        // The right operand bumps the counter, so an evaluated-anyway operand shows up.
        locals.flag = 0;
        if ((input.left != 0) && (state.mut().sideEffects++ < 1000))
        {
        locals.flag = 1;
        }
        state.mut().andResult = locals.flag;
        locals.flag = 0;
        if ((input.right != 0) || (state.mut().sideEffects++ < 1000))
        {
        locals.flag = 1;
        }
        state.mut().orResult = locals.flag;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 sideEffects;
        uint64 andResult;
        uint64 orResult;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.sideEffects = state.get().sideEffects;
        output.andResult = state.get().andResult;
        output.orResult = state.get().orResult;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Evaluate, 1);
    }

    INITIALIZE()
    {
        state.mut().sideEffects = 0;
        state.mut().andResult = 0;
        state.mut().orResult = 0;
    }
};
