// ShortCircuitOrChainCounts — ported from test/libsolidity/semanticTests/expressions/short_circuit.sol
// Stresses: a three-term `||` where each term increments a counter as a side effect, so the counter says exactly how many terms were evaluated
// Variant: entryOrder=declared entryShape=direct initStyle=full placement=last stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct ShortCircuitOrChainCounts2
{
};

struct ShortCircuitOrChainCounts : public ContractBase
{
    struct Scratch
    {
        uint64 runValue;
        uint64 runFlag;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 calls;
        uint64 firstTrue;
        uint64 result;
        uint64 evaluated;
        Scratch scratch;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 evaluated;
        uint64 result;
        uint64 firstTrue;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.evaluated = state.get().evaluated;
        output.result = state.get().result;
        output.firstTrue = state.get().firstTrue;
        output.calls = state.get().calls;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    PUBLIC_PROCEDURE(Run)
    {
        state.mut().scratch.runValue = input.a;
        state.mut().evaluated = 0;
        state.mut().scratch.runFlag = 0;
        state.mut().evaluated++;
        if (state.mut().scratch.runValue > 100)
        {
        state.mut().scratch.runFlag = 1;
        state.mut().firstTrue = 1;
        }
        if (state.mut().scratch.runFlag == 0)
        {
        state.mut().evaluated++;
        if (QPI::mod(state.mut().scratch.runValue, 7ULL) == 0)
        {
        state.mut().scratch.runFlag = 1;
        state.mut().firstTrue = 2;
        }
        }
        if (state.mut().scratch.runFlag == 0)
        {
        state.mut().evaluated++;
        if (state.mut().scratch.runValue == 13)
        {
        state.mut().scratch.runFlag = 1;
        state.mut().firstTrue = 3;
        }
        }
        state.mut().result = state.mut().scratch.runFlag;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().evaluated = 0;
        state.mut().result = 0;
        state.mut().firstTrue = 0;
        state.mut().calls = 0;
    }
};
