// StateMachineTransitionTable — ported from test/libsolidity/semanticTests/various/state_machine.sol
// Stresses: a four-state machine driven by an event code, where illegal transitions are refused and counted — the branch tree every escrow and auction contract is built from
// Variant: entryOrder=declared entryShape=direct initStyle=full placement=first stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct StateMachineTransitionTable2
{
};

struct StateMachineTransitionTable : public ContractBase
{
    struct Scratch
    {
        uint64 runEvent;
        uint64 runNext;
    };

    struct StateData
    {
        uint64 currentState;
        uint64 transitions;
        uint64 refused;
        uint64 terminalReached;
        uint64 calls;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 currentState;
        uint64 transitions;
        uint64 refused;
        uint64 terminalReached;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.currentState = state.get().currentState;
        output.transitions = state.get().transitions;
        output.refused = state.get().refused;
        output.terminalReached = state.get().terminalReached;
        output.calls = state.get().calls;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    PUBLIC_PROCEDURE(Run)
    {
        state.mut().scratch.runEvent = QPI::mod(input.a, 4ULL);
        state.mut().scratch.runNext = state.get().currentState;
        if (state.get().currentState == 0 && state.mut().scratch.runEvent == 1)
        {
        state.mut().scratch.runNext = 1;
        }
        else if (state.get().currentState == 1 && state.mut().scratch.runEvent == 2)
        {
        state.mut().scratch.runNext = 2;
        }
        else if (state.get().currentState == 2 && state.mut().scratch.runEvent == 3)
        {
        state.mut().scratch.runNext = 3;
        }
        else if (state.get().currentState == 1 && state.mut().scratch.runEvent == 3)
        {
        state.mut().scratch.runNext = 0;
        }
        if (state.mut().scratch.runNext == state.get().currentState)
        {
        state.mut().refused++;
        }
        else
        {
        state.mut().transitions++;
        state.mut().currentState = state.mut().scratch.runNext;
        if (state.mut().scratch.runNext == 3)
        {
        state.mut().terminalReached++;
        }
        }

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().currentState = 0;
        state.mut().transitions = 0;
        state.mut().refused = 0;
        state.mut().terminalReached = 0;
        state.mut().calls = 0;
    }
};
