// StateMachineTransitionTable — ported from test/libsolidity/semanticTests/various/state_machine.sol
// Stresses: a four-state machine driven by an event code, where illegal transitions are refused and counted — the branch tree every escrow and auction contract is built from
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=empty placement=first stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct StateMachineTransitionTable2
{
};

struct StateMachineTransitionTable : public ContractBase
{
    struct StateData
    {
        uint64 calls;
        uint64 terminalReached;
        uint64 refused;
        uint64 transitions;
        uint64 currentState;
        uint64 placementGuard;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 currentState;
        uint64 transitions;
        uint64 refused;
        uint64 terminalReached;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    struct RunBody_locals
    {
        uint64 event;
        uint64 next;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RunBody)
    {
        locals.event = QPI::mod(input.a, 4ULL);
        locals.next = state.get().currentState;
        if (state.get().currentState == 0 && locals.event == 1)
        {
        locals.next = 1;
        }
        else if (state.get().currentState == 1 && locals.event == 2)
        {
        locals.next = 2;
        }
        else if (state.get().currentState == 2 && locals.event == 3)
        {
        locals.next = 3;
        }
        else if (state.get().currentState == 1 && locals.event == 3)
        {
        locals.next = 0;
        }
        if (locals.next == state.get().currentState)
        {
        state.mut().refused++;
        }
        else
        {
        state.mut().transitions++;
        state.mut().currentState = locals.next;
        if (locals.next == 3)
        {
        state.mut().terminalReached++;
        }
        }

        state.mut().calls++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.currentState = state.get().currentState;
        output.transitions = state.get().transitions;
        output.refused = state.get().refused;
        output.terminalReached = state.get().terminalReached;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
