// UnrollBoundaryEightIterations — ported from test/libsolidity/semanticTests/controlFlow/loops.sol
// Stresses: a loop whose trip count is one, two, four, eight or nine — the sizes a compiler is most likely to unroll, with a running sum that must not depend on how it was compiled
// Variant: base
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct UnrollBoundaryEightIterations2
{
};

struct UnrollBoundaryEightIterations : public ContractBase
{
    struct StateData
    {
        uint64 sum;
        uint64 squares;
        uint64 iterations;
        uint64 lastIndex;
        uint64 calls;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 sum;
        uint64 squares;
        uint64 iterations;
        uint64 lastIndex;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.sum = state.get().sum;
        output.squares = state.get().squares;
        output.iterations = state.get().iterations;
        output.lastIndex = state.get().lastIndex;
        output.calls = state.get().calls;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        uint64 i;
        uint64 bounded;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.bounded = input.a > 32 ? 32 : input.a;
        state.mut().sum = 0;
        state.mut().squares = 0;
        for (locals.i = 0; locals.i < locals.bounded; locals.i++)
        {
        state.mut().sum += locals.i + 1;
        state.mut().squares += (locals.i + 1) * (locals.i + 1);
        state.mut().lastIndex = locals.i;
        }
        state.mut().iterations = locals.bounded;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().sum = 0;
        state.mut().squares = 0;
        state.mut().iterations = 0;
        state.mut().lastIndex = 0;
        state.mut().calls = 0;
    }
};
