// UnrollBoundaryEightIterations — ported from test/libsolidity/semanticTests/controlFlow/loops.sol
// Stresses: a loop whose trip count is one, two, four, eight or nine — the sizes a compiler is most likely to unroll, with a running sum that must not depend on how it was compiled
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=absent placement=first stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct UnrollBoundaryEightIterations2
{
};

struct UnrollBoundaryEightIterations : public ContractBase
{
    struct Scratch
    {
        uint64 runI;
        uint64 runBounded;
    };

    struct StateData
    {
        uint64 calls;
        uint64 lastIndex;
        uint64 iterations;
        uint64 squares;
        uint64 sum;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 sum;
        uint64 squares;
        uint64 iterations;
        uint64 lastIndex;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    PRIVATE_PROCEDURE(RunBody)
    {
        state.mut().scratch.runBounded = input.a > 32 ? 32 : input.a;
        state.mut().sum = 0;
        state.mut().squares = 0;
        for (state.mut().scratch.runI = 0; state.mut().scratch.runI < state.mut().scratch.runBounded; state.mut().scratch.runI++)
        {
        state.mut().sum += state.mut().scratch.runI + 1;
        state.mut().squares += (state.mut().scratch.runI + 1) * (state.mut().scratch.runI + 1);
        state.mut().lastIndex = state.mut().scratch.runI;
        }
        state.mut().iterations = state.mut().scratch.runBounded;

        state.mut().calls++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.sum = state.get().sum;
        output.squares = state.get().squares;
        output.iterations = state.get().iterations;
        output.lastIndex = state.get().lastIndex;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }
};
