// WhileWithTwoExitConditions — ported from test/libsolidity/semanticTests/controlFlow/while_loop.sol
// Stresses: a loop with two exit conditions where which one fired is recorded — the classic place an `||` and an `&&` get swapped without changing most outcomes
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=empty placement=nested stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct WhileWithTwoExitConditions2
{
};

struct WhileWithTwoExitConditions : public ContractBase
{
    struct Scratch
    {
        uint64 runValue;
        uint64 runCounter;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 iterations;
        uint64 remaining;
        uint64 exitByValue;
        uint64 exitByCounter;
        uint64 calls;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 iterations;
        uint64 remaining;
        uint64 exitByValue;
        uint64 exitByCounter;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.iterations = state.get().inner.iterations;
        output.remaining = state.get().inner.remaining;
        output.exitByValue = state.get().inner.exitByValue;
        output.exitByCounter = state.get().inner.exitByCounter;
        output.calls = state.get().inner.calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    PRIVATE_PROCEDURE(RunBody)
    {
        state.mut().inner.scratch.runValue = input.a;
        state.mut().inner.scratch.runCounter = 0;
        while (state.mut().inner.scratch.runValue > input.b && state.mut().inner.scratch.runCounter < 10)
        {
        state.mut().inner.scratch.runValue = QPI::div(state.mut().inner.scratch.runValue, 2ULL);
        state.mut().inner.scratch.runCounter++;
        }
        state.mut().inner.iterations = state.mut().inner.scratch.runCounter;
        state.mut().inner.remaining = state.mut().inner.scratch.runValue;
        if (state.mut().inner.scratch.runCounter == 10)
        {
        state.mut().inner.exitByCounter++;
        }
        else
        {
        state.mut().inner.exitByValue++;
        }

        state.mut().inner.calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
