// Generates the browser snapshot committed with Qinit; core-lite is a generation-time input only, so browser consumers never need a core checkout.
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { assembleQpiHeader, classifyQpiDrift, GENERATOR_VERSION } from "../src/driver/qpi/snapshot";
import { assembleQpiProtocolPrelude } from "../src/driver/qpi/prelude";
import { QpiDriftKind } from "../src/shared/enums";

const callArguments = process.argv.slice(2);
const flag = (name: string): boolean => callArguments.includes(name);
const opt = (name: string): string | undefined => {
    const i = callArguments.indexOf(name);
    return i >= 0 ? callArguments[i + 1] : undefined;
};

const pkgDir = resolve(import.meta.dir, "..");
const manifestPath = join(pkgDir, "core-snapshot.json");
const outputPath = join(pkgDir, "src", "generated", "qpi-snapshot.ts");
const protocolPreludePath = join(pkgDir, "src", "generated", "qpi-protocol-prelude.ts");
const quiet = flag("--quiet");
const normalize = (source: string) => source.replace(/\r\n?/g, "\n");
const outputMatches = (path: string, contents: string) => existsSync(path) && normalize(readFileSync(path, "utf8")) === normalize(contents);
const log = (msg: string) => {
    if (!quiet) console.log(`[qpi-snapshot] ${msg}`);
};
const warn = (msg: string) => {
    console.log(`[qpi-snapshot] ${msg}`);
    if (process.env.GITHUB_ACTIONS) console.log(`::warning::${msg}`);
};

const corePath = opt("--core-dir") ?? process.env.QINIT_CORE;
if (!corePath) {
    console.error("[qpi-snapshot] no core checkout: pass --core-dir <path> or set QINIT_CORE");
    process.exit(1);
}
const core = resolve(corePath);
if (!existsSync(join(core, "src", "qpi", "qpi.h"))) {
    console.error(`[qpi-snapshot] ${core} is not a core checkout (src/qpi/qpi.h missing)`);
    process.exit(1);
}

interface SnapshotManifest {
    coreCommit: string;
    generatorVersion: number;
    snapshotHash: string;
}

const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as SnapshotManifest;

function render(snapshot: string): { hash: string; module: string; protocolPreludeModule: string } {
    const protocolPrelude = assembleQpiProtocolPrelude(readFileSync(join(core, "src", "network_messages", "common_def.h"), "utf8"));
    const hash = "sha256:" + createHash("sha256").update(snapshot).digest("hex");
    const pkg = JSON.parse(readFileSync(join(pkgDir, "package.json"), "utf8"));
    const meta = {
        snapshotHash: hash,
        coreCommit: manifest.coreCommit,
        generatorVersion: GENERATOR_VERSION,
        qinitCompilerVersion: pkg.version as string,
    };
    return {
        hash,
        module:
            "// Generated by tools/gen-qpi-snapshot.ts — do not edit; commit updates with their core pin.\n" +
            `// core: ${meta.coreCommit} · generator v${GENERATOR_VERSION}\n` +
            `export const QPI_SNAPSHOT_META = ${JSON.stringify(meta, null, 2)} as const;\n\n` +
            `export const QPI_SNAPSHOT: string = ${JSON.stringify(snapshot)};\n`,
        protocolPreludeModule:
            "// Generated by tools/gen-qpi-snapshot.ts — do not edit.\n" + `export const QPI_PROTOCOL_PRELUDE: string = ${JSON.stringify(protocolPrelude)};\n`,
    };
}

function verify(hash: string): void {
    if (manifest.generatorVersion !== GENERATOR_VERSION) {
        throw new Error(`generator v${GENERATOR_VERSION} != manifest v${manifest.generatorVersion} — update core-snapshot.json`);
    }
    if (manifest.snapshotHash !== hash) {
        throw new Error(
            `snapshot hash mismatch\n  generated: ${hash}\n  manifest:  ${manifest.snapshotHash}` +
                `\n  (core at ${core}, expected commit ${manifest.coreCommit})`,
        );
    }
}

try {
    const liveSnapshot = assembleQpiHeader(core);
    const checking = flag("--verify") || flag("--check");
    let snapshot = liveSnapshot;
    if (existsSync(outputPath)) {
        const { QPI_SNAPSHOT } = await import("../src/generated/qpi-snapshot");
        const drift = classifyQpiDrift(liveSnapshot, QPI_SNAPSHOT);
        if (drift.kind === QpiDriftKind.EQUIVALENT) {
            snapshot = QPI_SNAPSHOT;
        } else if (checking && drift.kind === QpiDriftKind.ABI) {
            throw new Error(`core wasm ABI drifted from the committed snapshot; regenerate it from ${core} and review host imports`);
        } else if (checking) {
            // Catalog-only drift keeps the committed snapshot usable; the check then covers its self-consistency.
            warn(`committed snapshot is behind core at ${core} (${drift.changed.join(", ")} changed); regenerate when convenient`);
            snapshot = QPI_SNAPSHOT;
        }
    }
    const generated = render(snapshot);
    if (flag("--verify") || flag("--check")) {
        verify(generated.hash);
        log(`verified against ${manifestPath}`);
    }
    if (flag("--check")) {
        if (!outputMatches(outputPath, generated.module)) {
            throw new Error(`${outputPath} is stale; regenerate it from the pinned core checkout`);
        }
        if (!outputMatches(protocolPreludePath, generated.protocolPreludeModule)) {
            throw new Error(`${protocolPreludePath} is stale; regenerate it from the pinned core checkout`);
        }
        log(`${outputPath} is current`);
    } else {
        const snapshotChanged = !outputMatches(outputPath, generated.module);
        const protocolPreludeChanged = !outputMatches(protocolPreludePath, generated.protocolPreludeModule);
        if (snapshotChanged || protocolPreludeChanged) {
            mkdirSync(dirname(outputPath), { recursive: true });
        }
        if (snapshotChanged) {
            writeFileSync(outputPath, generated.module);
        }
        if (protocolPreludeChanged) {
            writeFileSync(protocolPreludePath, generated.protocolPreludeModule);
        }
        log(snapshotChanged || protocolPreludeChanged ? `generated core snapshot artifacts (${generated.hash})` : `up to date (${generated.hash})`);
    }
} catch (error) {
    console.error(`[qpi-snapshot] ${(error as Error).message}`);
    process.exit(1);
}
