// ArrayOfHashMaps — ported from test/libsolidity/semanticTests/mappings/mapping_of_mappings.sol
// Stresses: physical nesting of a table inside an array
// Port caveat: Solidity nests by hashing, not by layout
// Variant: capacity=1024 entryOrder=reversed entryShape=direct initStyle=full placement=first stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct ArrayOfHashMaps2
{
};

struct ArrayOfHashMaps : public ContractBase
{
    struct StateData
    {
        uint64 writes;
        uint64 canary;
        Array<HashMap<uint64, uint64, 8>, 4> tables;
        uint64 placementGuard;
    };

    struct Write_input
    {
        uint64 outer;
        uint64 key;
        uint64 value;
    };

    struct Write_output {};

    struct Write_locals
    {
        HashMap<uint64, uint64, 8> table;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Write)
    {
        locals.table = state.get().tables.get(input.outer);
        locals.table.set(input.key, input.value);
        state.mut().tables.set(input.outer, locals.table);
        state.mut().writes++;
    }

    struct Read_input
    {
        uint64 outer;
        uint64 key;
    };

    struct Read_output
    {
        uint64 value;
        uint64 present;
        uint64 population;
        uint64 neighbourPopulation;
        uint64 canary;
    };

    struct Read_locals
    {
        uint64 fetched;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        locals.fetched = 0;
        output.present = state.get().tables.get(input.outer).get(input.key, locals.fetched) ? 1 : 0;
        output.value = locals.fetched;
        output.population = state.get().tables.get(input.outer).population();
        output.neighbourPopulation = state.get().tables.get(input.outer + 1).population();
        output.canary = state.get().canary;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Write, 1);
    }

    struct INITIALIZE_locals
    {
        uint64 i;
        HashMap<uint64, uint64, 8> table;
    };

    INITIALIZE_WITH_LOCALS()
    {
        state.mut().canary = 18446744073709551615ULL;
        state.mut().writes = 0;
        locals.table.reset();
        for (locals.i = 0; locals.i < 4; locals.i++)
        {
        state.mut().tables.set(locals.i, locals.table);
        }
    }
};
