// ArrayOfHashMaps — ported from test/libsolidity/semanticTests/mappings/mapping_of_mappings.sol
// Stresses: physical nesting of a table inside an array
// Port caveat: Solidity nests by hashing, not by layout
// Variant: capacity=8 entryOrder=reversed entryShape=viaPrivate initStyle=full placement=nested stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct ArrayOfHashMaps2
{
};

struct ArrayOfHashMaps : public ContractBase
{
    struct Scratch
    {
        HashMap<uint64, uint64, 8> writeTable;
    };

    struct StateData
    {
        struct Inner
        {
        Array<HashMap<uint64, uint64, 8>, 4> tables;
        uint64 canary;
        uint64 writes;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Write_input
    {
        uint64 outer;
        uint64 key;
        uint64 value;
    };

    struct Write_output {};

    struct Write_locals
    {
        Write_input forwardedInput;
        Write_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Write)
    {
        locals.forwardedInput = input;
        CALL(WriteBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input
    {
        uint64 outer;
        uint64 key;
    };

    struct Read_output
    {
        uint64 value;
        uint64 present;
        uint64 population;
        uint64 neighbourPopulation;
        uint64 canary;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        locals.forwardedInput = input;
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using WriteBody_input = Write_input;

    using WriteBody_output = Write_output;

    PRIVATE_PROCEDURE(WriteBody)
    {
        state.mut().inner.scratch.writeTable = state.get().inner.tables.get(input.outer);
        state.mut().inner.scratch.writeTable.set(input.key, input.value);
        state.mut().inner.tables.set(input.outer, state.mut().inner.scratch.writeTable);
        state.mut().inner.writes++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    struct ReadBody_locals
    {
        uint64 fetched;
    };

    PRIVATE_FUNCTION_WITH_LOCALS(ReadBody)
    {
        locals.fetched = 0;
        output.present = state.get().inner.tables.get(input.outer).get(input.key, locals.fetched) ? 1 : 0;
        output.value = locals.fetched;
        output.population = state.get().inner.tables.get(input.outer).population();
        output.neighbourPopulation = state.get().inner.tables.get(input.outer + 1).population();
        output.canary = state.get().inner.canary;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Write, 1);
    }

    struct INITIALIZE_locals
    {
        uint64 i;
        HashMap<uint64, uint64, 8> table;
    };

    INITIALIZE_WITH_LOCALS()
    {
        state.mut().inner.canary = 18446744073709551615ULL;
        state.mut().inner.writes = 0;
        locals.table.reset();
        for (locals.i = 0; locals.i < 4; locals.i++)
        {
        state.mut().inner.tables.set(locals.i, locals.table);
        }
    }
};
