// BitArrayLargeSparse — ported from test/libsolidity/semanticTests/various/bit_operations.sol
// Stresses: bit indices at every word boundary of a 2048-bit array
// Port caveat: wider than one Solidity word by design
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=empty placement=last stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct BitArrayLargeSparse2
{
};

struct BitArrayLargeSparse : public ContractBase
{
    struct Scratch
    {
        uint64 setMasked;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 wordBoundaryHits;
        uint64 lastIndex;
        uint64 setCount;
        BitArray<2048> flags;
        Scratch scratch;
    };

    struct Set_input
    {
        uint64 index;
    };

    struct Set_output {};

    struct Set_locals
    {
        Set_input forwardedInput;
        Set_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Set)
    {
        locals.forwardedInput = input;
        CALL(SetBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input
    {
        uint64 index;
    };

    struct Read_output
    {
        uint64 bit;
        uint64 neighbourBelow;
        uint64 neighbourAbove;
        uint64 setCount;
        uint64 wordBoundaryHits;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        locals.forwardedInput = input;
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using SetBody_input = Set_input;

    using SetBody_output = Set_output;

    PRIVATE_PROCEDURE(SetBody)
    {
        state.mut().scratch.setMasked = input.index & 2047ULL;
        state.mut().flags.set(state.mut().scratch.setMasked, 1);
        state.mut().lastIndex = state.mut().scratch.setMasked;
        state.mut().setCount++;
        if ((state.mut().scratch.setMasked & 63ULL) == 0)
        {
        state.mut().wordBoundaryHits++;
        }
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.bit = state.get().flags.get(input.index & 2047ULL);
        output.neighbourBelow = state.get().flags.get((input.index - 1) & 2047ULL);
        output.neighbourAbove = state.get().flags.get((input.index + 1) & 2047ULL);
        output.setCount = state.get().setCount;
        output.wordBoundaryHits = state.get().wordBoundaryHits;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Set, 1);
    }

    INITIALIZE()
    {

    }
};
