// CheckpointBinarySearchUpperBound — ported from openzeppelin-contracts/contracts/utils/structs/Checkpoints.sol
// Stresses: an upper-bound binary search over a partially filled, sorted array — queried below the first key, between keys, exactly on a key and past the last
// Port caveat: Checkpoints stores (key, value) pairs in a dynamic array; the port uses a fixed one with an explicit length, so the search bound is the length rather than the capacity.
// Variant: capacity=8 entryOrder=reversed entryShape=direct initStyle=empty placement=nested stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CheckpointBinarySearchUpperBound2
{
};

struct CheckpointBinarySearchUpperBound : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 misses;
        uint64 queries;
        uint64 lastAnswer;
        uint64 length;
        Array<uint64, 8> values;
        Array<uint64, 8> keys;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 length;
        uint64 lastAnswer;
        uint64 queries;
        uint64 misses;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.length = state.get().inner.length;
        output.lastAnswer = state.get().inner.lastAnswer;
        output.queries = state.get().inner.queries;
        output.misses = state.get().inner.misses;
    }

    struct Push_input
    {
        uint64 key;
        uint64 value;
    };

    struct Push_output {};

    struct Push_locals
    {
        uint64 scratch;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Push)
    {
        if (state.get().inner.length >= 8)
        {
        return;
        }
        if (state.get().inner.length > 0 && state.get().inner.keys.get(state.get().inner.length - 1) >= input.key)
        {
        return;
        }
        state.mut().inner.keys.set(state.get().inner.length, input.key);
        state.mut().inner.values.set(state.get().inner.length, input.value);
        state.mut().inner.length++;
    }

    struct Lookup_input
    {
        uint64 key;
    };

    struct Lookup_output
    {
        uint64 value;
    };

    struct Lookup_locals
    {
        uint64 low;
        uint64 high;
        uint64 middle;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Lookup)
    {
        locals.low = 0;
        locals.high = state.get().inner.length;
        while (locals.low < locals.high)
        {
        locals.middle = locals.low + QPI::div(locals.high - locals.low, 2ULL);
        if (state.get().inner.keys.get(locals.middle) > input.key)
        {
        locals.high = locals.middle;
        }
        else
        {
        locals.low = locals.middle + 1;
        }
        }
        state.mut().inner.queries++;
        if (locals.low == 0)
        {
        state.mut().inner.misses++;
        state.mut().inner.lastAnswer = 0;
        output.value = 0;
        }
        else
        {
        state.mut().inner.lastAnswer = state.get().inner.values.get(locals.low - 1);
        output.value = state.get().inner.lastAnswer;
        }
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Push, 1);
        REGISTER_USER_PROCEDURE(Lookup, 2);
    }

    INITIALIZE()
    {

    }
};
