// CollectionBackwardWalkByTailIndex — ported from openzeppelin-contracts/contracts/utils/structs/DoubleEndedQueue.sol
// Stresses: tailIndex + prevElementIndex against headIndex + nextElementIndex
// Port caveat: no priorities in the Solidity original
// Variant: capacity=2 entryOrder=reversed entryShape=direct initStyle=full placement=last stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CollectionBackwardWalkByTailIndex2
{
};

struct CollectionBackwardWalkByTailIndex : public ContractBase
{
    struct Scratch
    {
        sint64 addIndex;
        sint64 walkBothIndex;
        uint64 walkBothGuard;
        uint64 walkBothSeen;
        uint64 walkBothFirstSeen;
        uint64 walkBothLastSeen;
    };

    struct StateData
    {
        uint64 placementGuard;
        Collection<uint64, 8> queue;
        uint64 forwardFirst;
        uint64 forwardLast;
        uint64 backwardFirst;
        uint64 backwardLast;
        uint64 forwardCount;
        uint64 backwardCount;
        uint64 mismatched;
        Scratch scratch;
    };

    struct WalkBoth_input
    {
        uint64 unused;
    };

    struct WalkBoth_output {};

    PUBLIC_PROCEDURE(WalkBoth)
    {
        state.mut().scratch.walkBothIndex = state.get().queue.headIndex(SELF);
        state.mut().scratch.walkBothGuard = 0;
        state.mut().scratch.walkBothSeen = 0;
        state.mut().scratch.walkBothFirstSeen = 0;
        state.mut().scratch.walkBothLastSeen = 0;
        while (state.mut().scratch.walkBothIndex >= 0 && state.mut().scratch.walkBothGuard < 16)
        {
        if (state.mut().scratch.walkBothSeen == 0)
        {
        state.mut().scratch.walkBothFirstSeen = state.get().queue.element(state.mut().scratch.walkBothIndex);
        }
        state.mut().scratch.walkBothLastSeen = state.get().queue.element(state.mut().scratch.walkBothIndex);
        state.mut().scratch.walkBothIndex = state.get().queue.nextElementIndex(state.mut().scratch.walkBothIndex);
        state.mut().scratch.walkBothSeen++;
        state.mut().scratch.walkBothGuard++;
        }
        state.mut().forwardFirst = state.mut().scratch.walkBothFirstSeen;
        state.mut().forwardLast = state.mut().scratch.walkBothLastSeen;
        state.mut().forwardCount = state.mut().scratch.walkBothSeen;

        state.mut().scratch.walkBothIndex = state.get().queue.tailIndex(SELF);
        state.mut().scratch.walkBothGuard = 0;
        state.mut().scratch.walkBothSeen = 0;
        state.mut().scratch.walkBothFirstSeen = 0;
        state.mut().scratch.walkBothLastSeen = 0;
        while (state.mut().scratch.walkBothIndex >= 0 && state.mut().scratch.walkBothGuard < 16)
        {
        if (state.mut().scratch.walkBothSeen == 0)
        {
        state.mut().scratch.walkBothFirstSeen = state.get().queue.element(state.mut().scratch.walkBothIndex);
        }
        state.mut().scratch.walkBothLastSeen = state.get().queue.element(state.mut().scratch.walkBothIndex);
        state.mut().scratch.walkBothIndex = state.get().queue.prevElementIndex(state.mut().scratch.walkBothIndex);
        state.mut().scratch.walkBothSeen++;
        state.mut().scratch.walkBothGuard++;
        }
        state.mut().backwardFirst = state.mut().scratch.walkBothFirstSeen;
        state.mut().backwardLast = state.mut().scratch.walkBothLastSeen;
        state.mut().backwardCount = state.mut().scratch.walkBothSeen;

        // The two walks must cover the same elements and mirror each other's ends.
        if (state.get().forwardCount != state.get().backwardCount)
        {
        state.mut().mismatched++;
        }
        if (state.get().forwardFirst != state.get().backwardLast)
        {
        state.mut().mismatched++;
        }
        if (state.get().forwardLast != state.get().backwardFirst)
        {
        state.mut().mismatched++;
        }
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 forwardFirst;
        uint64 forwardLast;
        uint64 backwardFirst;
        uint64 backwardLast;
        uint64 forwardCount;
        uint64 backwardCount;
        uint64 mismatched;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.forwardFirst = state.get().forwardFirst;
        output.forwardLast = state.get().forwardLast;
        output.backwardFirst = state.get().backwardFirst;
        output.backwardLast = state.get().backwardLast;
        output.forwardCount = state.get().forwardCount;
        output.backwardCount = state.get().backwardCount;
        output.mismatched = state.get().mismatched;
    }

    struct Add_input
    {
        uint64 value;
        sint64 priority;
    };

    struct Add_output {};

    PUBLIC_PROCEDURE(Add)
    {
        state.mut().scratch.addIndex = state.mut().queue.add(SELF, input.value, input.priority);
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Add, 1);
        REGISTER_USER_PROCEDURE(WalkBoth, 2);
    }

    INITIALIZE()
    {
        state.mut().queue.reset();
        state.mut().forwardFirst = 0;
        state.mut().forwardLast = 0;
        state.mut().backwardFirst = 0;
        state.mut().backwardLast = 0;
        state.mut().forwardCount = 0;
        state.mut().backwardCount = 0;
        state.mut().mismatched = 0;
    }
};
