// CollectionPriorityQueueByPov — ported from openzeppelin-contracts/contracts/utils/structs/DoubleEndedQueue.sol
// Stresses: priority ordering and the head-to-tail walk under two povs
// Port caveat: no priorities or povs in the Solidity original
// Variant: capacity=2 entryOrder=reversed entryShape=direct initStyle=absent placement=nested stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CollectionPriorityQueueByPov2
{
};

struct CollectionPriorityQueueByPov : public ContractBase
{
    struct Scratch
    {
        id addPov;
        sint64 addIndex;
        id walkPov;
        sint64 walkIndex;
        uint64 walkPrevious;
        uint64 walkGuard;
        uint64 walkSeen;
    };

    struct StateData
    {
        struct Inner
        {
        Collection<uint64, 2> queue;
        uint64 added;
        uint64 walked;
        uint64 headValue;
        uint64 tailValue;
        uint64 outOfOrder;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Walk_input
    {
        uint64 povSelector;
    };

    struct Walk_output {};

    PUBLIC_PROCEDURE(Walk)
    {
        state.mut().inner.scratch.walkPov = input.povSelector == 0 ? SELF : qpi.invocator();
        state.mut().inner.scratch.walkIndex = state.get().inner.queue.headIndex(state.mut().inner.scratch.walkPov);
        state.mut().inner.scratch.walkPrevious = 0;
        state.mut().inner.scratch.walkGuard = 0;
        state.mut().inner.scratch.walkSeen = 0;
        while (state.mut().inner.scratch.walkIndex >= 0 && state.mut().inner.scratch.walkGuard < 4)
        {
        if (state.mut().inner.scratch.walkSeen == 0)
        {
        state.mut().inner.headValue = state.get().inner.queue.element(state.mut().inner.scratch.walkIndex);
        }
        else if (state.get().inner.queue.element(state.mut().inner.scratch.walkIndex) < state.mut().inner.scratch.walkPrevious)
        {
        state.mut().inner.outOfOrder++;
        }
        state.mut().inner.scratch.walkPrevious = state.get().inner.queue.element(state.mut().inner.scratch.walkIndex);
        state.mut().inner.tailValue = state.mut().inner.scratch.walkPrevious;
        state.mut().inner.scratch.walkIndex = state.get().inner.queue.nextElementIndex(state.mut().inner.scratch.walkIndex);
        state.mut().inner.scratch.walkSeen++;
        state.mut().inner.scratch.walkGuard++;
        }
        state.mut().inner.walked += state.mut().inner.scratch.walkSeen;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 population;
        uint64 added;
        uint64 walked;
        uint64 headValue;
        uint64 tailValue;
        uint64 outOfOrder;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.population = state.get().inner.queue.population();
        output.added = state.get().inner.added;
        output.walked = state.get().inner.walked;
        output.headValue = state.get().inner.headValue;
        output.tailValue = state.get().inner.tailValue;
        output.outOfOrder = state.get().inner.outOfOrder;
    }

    struct Add_input
    {
        uint64 value;
        sint64 priority;
        uint64 povSelector;
    };

    struct Add_output {};

    PUBLIC_PROCEDURE(Add)
    {
        state.mut().inner.scratch.addPov = input.povSelector == 0 ? SELF : qpi.invocator();
        state.mut().inner.scratch.addIndex = state.mut().inner.queue.add(state.mut().inner.scratch.addPov, input.value, input.priority);
        if (state.mut().inner.scratch.addIndex >= 0)
        {
        state.mut().inner.added++;
        }
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Add, 1);
        REGISTER_USER_PROCEDURE(Walk, 2);
    }
};
