// HashMapReplaceVersusSet — ported from test/libsolidity/semanticTests/mappings/mapping_assignment.sol
// Stresses: replace (no insert) against set (insert), on present and absent keys
// Port caveat: Solidity assignment always inserts
// Variant: capacity=8 entryOrder=declared entryShape=viaPrivate initStyle=absent placement=first stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HashMapReplaceVersusSet2
{
};

struct HashMapReplaceVersusSet : public ContractBase
{
    struct Scratch
    {
        uint64 seedI;
        sint64 seedSlot;
        uint64 replaceScratch;
    };

    struct StateData
    {
        HashMap<uint64, uint64, 8> table;
        uint64 replaceHits;
        uint64 replaceMisses;
        uint64 inserts;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Read_input
    {
        uint64 key;
    };

    struct Read_output
    {
        uint64 value;
        uint64 present;
        uint64 population;
        uint64 replaceHits;
        uint64 replaceMisses;
        uint64 inserts;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        locals.forwardedInput = input;
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Replace_input
    {
        uint64 key;
        uint64 value;
    };

    struct Replace_output
    {
        uint64 ok;
    };

    struct Replace_locals
    {
        Replace_input forwardedInput;
        Replace_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Replace)
    {
        locals.forwardedInput = input;
        CALL(ReplaceBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Seed_input
    {
        uint64 count;
    };

    struct Seed_output {};

    struct Seed_locals
    {
        Seed_input forwardedInput;
        Seed_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Seed)
    {
        locals.forwardedInput = input;
        CALL(SeedBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    struct ReadBody_locals
    {
        uint64 fetched;
    };

    PRIVATE_FUNCTION_WITH_LOCALS(ReadBody)
    {
        locals.fetched = 0;
        output.present = state.get().table.get(input.key, locals.fetched) ? 1 : 0;
        output.value = locals.fetched;
        output.population = state.get().table.population();
        output.replaceHits = state.get().replaceHits;
        output.replaceMisses = state.get().replaceMisses;
        output.inserts = state.get().inserts;
    }

    using ReplaceBody_input = Replace_input;

    using ReplaceBody_output = Replace_output;

    PRIVATE_PROCEDURE(ReplaceBody)
    {
        if (state.mut().table.replace(input.key, input.value))
        {
        state.mut().replaceHits++;
        output.ok = 1;
        return;
        }
        state.mut().replaceMisses++;
        output.ok = 0;
    }

    using SeedBody_input = Seed_input;

    using SeedBody_output = Seed_output;

    PRIVATE_PROCEDURE(SeedBody)
    {
        for (state.mut().scratch.seedI = 0; state.mut().scratch.seedI < input.count; state.mut().scratch.seedI++)
        {
        state.mut().scratch.seedSlot = state.mut().table.set(state.mut().scratch.seedI, state.mut().scratch.seedI + 1);
        if (state.mut().scratch.seedSlot >= 0)
        {
        state.mut().inserts++;
        }
        }
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Seed, 1);
        REGISTER_USER_PROCEDURE(Replace, 2);
    }
};
