// HashSetRemoveAndKeyByValue — ported from openzeppelin-contracts/contracts/utils/structs/EnumerableSet.sol (remove and read back)
// Stresses: HashSet's deletion half — spelled remove() where HashMap spells removeByKey() — and its key() accessor, which returns by value where HashMap's returns by const reference, so the two go through different return conventions in the backend
// Port caveat: EnumerableSet's remove swaps and pops; QPI marks, so the surviving elements keep their slots rather than being relocated.
// Variant: entryOrder=reversed entryShape=direct initStyle=full placement=first stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HashSetRemoveAndKeyByValue2
{
};

struct HashSetRemoveAndKeyByValue : public ContractBase
{
    struct StateData
    {
        uint64 calls;
        uint64 keyOneIntact;
        uint64 population;
        uint64 idx17;
        uint64 idx9;
        uint64 idx1;
        HashSet<id, 8> set;
        uint64 placementGuard;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        id k1;
        id k9;
        id k17;
        id target;
        sint64 removed;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        state.mut().set.reset();

        locals.k1 = id(1, 0, 0, 0);
        locals.k9 = id(9, 0, 0, 0);
        locals.k17 = id(17, 0, 0, 0);

        state.mut().set.add(locals.k1);
        state.mut().set.add(locals.k9);
        state.mut().set.add(locals.k17);
        locals.target = id(input.a, 0, 0, 0);
        locals.removed = state.mut().set.remove(locals.target);
        state.mut().idx1 = state.get().set.getElementIndex(locals.k1);
        state.mut().idx9 = state.get().set.getElementIndex(locals.k9);
        state.mut().idx17 = state.get().set.getElementIndex(locals.k17);
        state.mut().population = state.get().set.population();
        state.mut().keyOneIntact = (state.get().set.key(1) == locals.k1) ? 1 : 0;

        state.mut().calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 idx1;
        uint64 idx9;
        uint64 idx17;
        uint64 population;
        uint64 keyOneIntact;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.idx1 = state.get().idx1;
        output.idx9 = state.get().idx9;
        output.idx17 = state.get().idx17;
        output.population = state.get().population;
        output.keyOneIntact = state.get().keyOneIntact;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().set.reset();
        state.mut().idx1 = 0;
        state.mut().idx9 = 0;
        state.mut().idx17 = 0;
        state.mut().population = 0;
        state.mut().keyOneIntact = 0;
        state.mut().calls = 0;
    }
};
