// HashMapRemovalCounterCountsRemovalsNotTombstones — ported from openzeppelin-contracts/contracts/utils/structs/EnumerableMap.sol (repeated add/remove of one key)
// Stresses: _markRemovalCounter is deliberately not decremented when a tombstone is reused, so churning one key drives a map with zero tombstones into needing a cleanup it cannot benefit from
// Port caveat: The Solidity original's set has no cleanup notion at all; this is a QPI-specific bookkeeping property with no Solidity counterpart.
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full placement=first stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HashMapRemovalCounterCountsRemovalsNotTombstones2
{
};

struct HashMapRemovalCounterCountsRemovalsNotTombstones : public ContractBase
{
    struct StateData
    {
        uint64 calls;
        uint64 emptyAtZero;
        uint64 needsZero;
        uint64 needsFifty;
        uint64 population;
        HashMap<id, uint64, 8> map;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 population;
        uint64 needsFifty;
        uint64 needsZero;
        uint64 emptyAtZero;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.population = state.get().population;
        output.needsFifty = state.get().needsFifty;
        output.needsZero = state.get().needsZero;
        output.emptyAtZero = state.get().emptyAtZero;
        output.calls = state.get().calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    struct RunBody_locals
    {
        id k0;
        uint64 i;
        sint64 removed;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RunBody)
    {
        state.mut().map.reset();
        locals.k0 = id(0, 0, 0, 0);
        state.mut().map.set(locals.k0, 1);
        for (locals.i = 0; locals.i < input.a; locals.i++)
        {
        locals.removed = state.mut().map.removeByKey(locals.k0);
        state.mut().map.set(locals.k0, 2);
        }
        state.mut().population = state.get().map.population();
        state.mut().needsFifty = state.get().map.needsCleanup(50) ? 1 : 0;
        state.mut().needsZero = state.get().map.needsCleanup(0) ? 1 : 0;
        state.mut().emptyAtZero = state.get().map.isEmptySlot(0) ? 1 : 0;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().map.reset();
        state.mut().population = 0;
        state.mut().needsFifty = 0;
        state.mut().needsZero = 0;
        state.mut().emptyAtZero = 0;
        state.mut().calls = 0;
    }
};
