// HashMapReplaceVersusSet — ported from test/libsolidity/semanticTests/mappings/mapping_assignment.sol
// Stresses: replace (no insert) against set (insert), on present and absent keys
// Port caveat: Solidity assignment always inserts
// Variant: capacity=1024 entryOrder=declared entryShape=viaPrivate initStyle=full placement=nested stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HashMapReplaceVersusSet2
{
};

struct HashMapReplaceVersusSet : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        HashMap<uint64, uint64, 1024> table;
        uint64 replaceHits;
        uint64 replaceMisses;
        uint64 inserts;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input
    {
        uint64 key;
    };

    struct Read_output
    {
        uint64 value;
        uint64 present;
        uint64 population;
        uint64 replaceHits;
        uint64 replaceMisses;
        uint64 inserts;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        locals.forwardedInput = input;
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Replace_input
    {
        uint64 key;
        uint64 value;
    };

    struct Replace_output
    {
        uint64 ok;
    };

    struct Replace_locals
    {
        Replace_input forwardedInput;
        Replace_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Replace)
    {
        locals.forwardedInput = input;
        CALL(ReplaceBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Seed_input
    {
        uint64 count;
    };

    struct Seed_output {};

    struct Seed_locals
    {
        Seed_input forwardedInput;
        Seed_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Seed)
    {
        locals.forwardedInput = input;
        CALL(SeedBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    struct ReadBody_locals
    {
        uint64 fetched;
    };

    PRIVATE_FUNCTION_WITH_LOCALS(ReadBody)
    {
        locals.fetched = 0;
        output.present = state.get().inner.table.get(input.key, locals.fetched) ? 1 : 0;
        output.value = locals.fetched;
        output.population = state.get().inner.table.population();
        output.replaceHits = state.get().inner.replaceHits;
        output.replaceMisses = state.get().inner.replaceMisses;
        output.inserts = state.get().inner.inserts;
    }

    using ReplaceBody_input = Replace_input;

    using ReplaceBody_output = Replace_output;

    struct ReplaceBody_locals
    {
        uint64 scratch;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(ReplaceBody)
    {
        if (state.mut().inner.table.replace(input.key, input.value))
        {
        state.mut().inner.replaceHits++;
        output.ok = 1;
        return;
        }
        state.mut().inner.replaceMisses++;
        output.ok = 0;
    }

    using SeedBody_input = Seed_input;

    using SeedBody_output = Seed_output;

    struct SeedBody_locals
    {
        uint64 i;
        sint64 slot;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(SeedBody)
    {
        for (locals.i = 0; locals.i < input.count; locals.i++)
        {
        locals.slot = state.mut().inner.table.set(locals.i, locals.i + 1);
        if (locals.slot >= 0)
        {
        state.mut().inner.inserts++;
        }
        }
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Seed, 1);
        REGISTER_USER_PROCEDURE(Replace, 2);
    }

    INITIALIZE()
    {
        state.mut().inner.table.reset();
        state.mut().inner.replaceHits = 0;
        state.mut().inner.replaceMisses = 0;
        state.mut().inner.inserts = 0;
    }
};
