// HashMapRemoveByIndexMasksItsArgument — ported from openzeppelin-contracts/contracts/utils/structs/EnumerableMap.sol (index bounds on removal)
// Stresses: removeByIndex masks its argument with (L-1) and never validates it, so an out-of-range or negative index is a silent alias for an in-range slot rather than an error
// Port caveat: The Solidity original reverts on an out-of-bounds index; QPI wraps, so the port asks which slot the wrap actually selects.
// Variant: entryOrder=reversed entryShape=direct initStyle=full placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HashMapRemoveByIndexMasksItsArgument2
{
};

struct HashMapRemoveByIndexMasksItsArgument : public ContractBase
{
    struct Scratch
    {
        id runK0;
        id runK8;
        id runK16;
        sint64 runTarget;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 calls;
        uint64 emptyAtSeven;
        uint64 emptyAtZero;
        uint64 population;
        HashMap<id, uint64, 8> map;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    PUBLIC_PROCEDURE(Run)
    {
        state.mut().inner.map.reset();
        state.mut().inner.scratch.runK0 = id(0, 0, 0, 0);
        state.mut().inner.scratch.runK8 = id(8, 0, 0, 0);
        state.mut().inner.scratch.runK16 = id(16, 0, 0, 0);
        state.mut().inner.map.set(state.mut().inner.scratch.runK0, 100);
        state.mut().inner.map.set(state.mut().inner.scratch.runK8, 200);
        state.mut().inner.map.set(state.mut().inner.scratch.runK16, 300);

        state.mut().inner.scratch.runTarget = input.a;
        state.mut().inner.map.removeByIndex(state.mut().inner.scratch.runTarget);
        state.mut().inner.population = state.get().inner.map.population();
        state.mut().inner.emptyAtZero = state.get().inner.map.isEmptySlot(0) ? 1 : 0;
        state.mut().inner.emptyAtSeven = state.get().inner.map.isEmptySlot(7) ? 1 : 0;

        state.mut().inner.calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 population;
        uint64 emptyAtZero;
        uint64 emptyAtSeven;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.population = state.get().inner.population;
        output.emptyAtZero = state.get().inner.emptyAtZero;
        output.emptyAtSeven = state.get().inner.emptyAtSeven;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.map.reset();
        state.mut().inner.population = 0;
        state.mut().inner.emptyAtZero = 0;
        state.mut().inner.emptyAtSeven = 0;
        state.mut().inner.calls = 0;
    }
};
