// HeapSiftUpDownIterative — ported from OpenZeppelin utils/structs/Heap.sol
// Stresses: parent `(i-1)/2` and children `2i+1` / `2i+2` index arithmetic through QPI::div, with the sift loops written iteratively
// Port caveat: OpenZeppelin's sift is recursive; QPI forbids recursion, so both directions are bounded loops. That rewrite is part of what is under test.
// Variant: capacity=8 entryOrder=reversed entryShape=direct initStyle=absent loopShape=constant placement=nested stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HeapSiftUpDownIterative2
{
};

struct HeapSiftUpDownIterative : public ContractBase
{
    struct Scratch
    {
        uint64 runI;
        uint64 runBound;
        uint64 runChild;
        uint64 runParent;
        uint64 runSwap;
        uint64 runBad;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 accumulator;
        uint64 calls;
        Array<uint64, 8> heap;
        uint64 size;
        uint64 violations;
        uint64 root;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Run_input
    {
        uint64 count;
        uint64 seed;
    };

    struct Run_output {};

    PUBLIC_PROCEDURE(Run)
    {
        state.mut().inner.scratch.runBound = input.count;
        if (state.mut().inner.scratch.runBound > 8)
        {
        state.mut().inner.scratch.runBound = 8;
        }
        state.mut().inner.size = 0;
        for (state.mut().inner.scratch.runI = 0; state.mut().inner.scratch.runI < state.mut().inner.scratch.runBound; state.mut().inner.scratch.runI++)
        {
        // Insert at the end, then sift up.
        state.mut().inner.heap.set(state.get().inner.size, QPI::mod(input.seed + state.mut().inner.scratch.runI * 37, 1000ULL));
        state.mut().inner.size++;
        state.mut().inner.scratch.runChild = state.get().inner.size - 1;
        while (state.mut().inner.scratch.runChild > 0)
        {
        state.mut().inner.scratch.runParent = QPI::div(state.mut().inner.scratch.runChild - 1, 2ULL);
        if (state.get().inner.heap.get(state.mut().inner.scratch.runParent) <= state.get().inner.heap.get(state.mut().inner.scratch.runChild))
        {
        break;
        }
        state.mut().inner.scratch.runSwap = state.get().inner.heap.get(state.mut().inner.scratch.runParent);
        state.mut().inner.heap.set(state.mut().inner.scratch.runParent, state.get().inner.heap.get(state.mut().inner.scratch.runChild));
        state.mut().inner.heap.set(state.mut().inner.scratch.runChild, state.mut().inner.scratch.runSwap);
        state.mut().inner.scratch.runChild = state.mut().inner.scratch.runParent;
        }
        }
        // The heap property is the assertion: no parent may exceed a child.
        state.mut().inner.scratch.runBad = 0;
        for (state.mut().inner.scratch.runI = 1; state.mut().inner.scratch.runI < state.get().inner.size; state.mut().inner.scratch.runI++)
        {
        state.mut().inner.scratch.runParent = QPI::div(state.mut().inner.scratch.runI - 1, 2ULL);
        if (state.get().inner.heap.get(state.mut().inner.scratch.runParent) > state.get().inner.heap.get(state.mut().inner.scratch.runI))
        {
        state.mut().inner.scratch.runBad++;
        }
        }
        state.mut().inner.violations = state.mut().inner.scratch.runBad;
        state.mut().inner.root = state.get().inner.size > 0 ? state.get().inner.heap.get(0) : 0;
        state.mut().inner.accumulator = state.get().inner.root * 100 + state.mut().inner.scratch.runBad;

        state.mut().inner.calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 accumulator;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.accumulator = state.get().inner.accumulator;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }
};
