// MapMissPreZeroed — ported from test/libsolidity/semanticTests/storage/mapping_state.sol
// Stresses: pre-zeroed miss vs hit on the same map
// Variant: capacity=1024 entryOrder=declared entryShape=viaPrivate initStyle=full placement=nested stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct MapMissPreZeroed2
{
};

struct MapMissPreZeroed : public ContractBase
{
    struct Scratch
    {
        uint64 probeFetched;
    };

    struct StateData
    {
        struct Inner
        {
        HashMap<uint64, uint64, 1024> book;
        uint64 hitValue;
        uint64 missValue;
        uint64 hitFlag;
        uint64 missFlag;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Probe_input
    {
        uint64 key;
    };

    struct Probe_output {};

    struct Probe_locals
    {
        Probe_input forwardedInput;
        Probe_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Probe)
    {
        locals.forwardedInput = input;
        CALL(ProbeBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 hitValue;
        uint64 missValue;
        uint64 hitFlag;
        uint64 missFlag;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using ProbeBody_input = Probe_input;

    using ProbeBody_output = Probe_output;

    PRIVATE_PROCEDURE(ProbeBody)
    {
        state.mut().inner.book.set(input.key, input.key + 77);
        state.mut().inner.scratch.probeFetched = 0;
        state.mut().inner.hitFlag = state.get().inner.book.get(input.key, state.mut().inner.scratch.probeFetched) ? 1 : 0;
        state.mut().inner.hitValue = state.mut().inner.scratch.probeFetched;
        state.mut().inner.scratch.probeFetched = 0;
        state.mut().inner.missFlag = state.get().inner.book.get(input.key + 1000000, state.mut().inner.scratch.probeFetched) ? 1 : 0;
        state.mut().inner.missValue = state.mut().inner.scratch.probeFetched;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.hitValue = state.get().inner.hitValue;
        output.missValue = state.get().inner.missValue;
        output.hitFlag = state.get().inner.hitFlag;
        output.missFlag = state.get().inner.missFlag;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Probe, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.book.reset();
        state.mut().inner.hitValue = 0;
        state.mut().inner.missValue = 0;
        state.mut().inner.hitFlag = 0;
        state.mut().inner.missFlag = 0;
    }
};
