// NestedMappingTwoLevel — ported from test/libsolidity/semanticTests/storage/mapping_of_mapping.sol
// Stresses: a folded two-level mapping key
// Port caveat: mapping(a => mapping(b => c)) is folded to a single combined key.
// Variant: capacity=64 entryOrder=reversed entryShape=direct initStyle=absent placement=first stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct NestedMappingTwoLevel2
{
};

struct NestedMappingTwoLevel : public ContractBase
{
    struct Scratch
    {
        uint64 approveKey;
        uint64 approveValue;
    };

    struct StateData
    {
        HashMap<uint64, uint64, 64> allowances;
        uint64 population;
        uint64 fetched;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 population;
        uint64 fetched;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.population = state.get().population;
        output.fetched = state.get().fetched;
    }

    struct Approve_input
    {
        uint64 owner;
        uint64 spender;
        uint64 amount;
    };

    struct Approve_output {};

    PUBLIC_PROCEDURE(Approve)
    {
        state.mut().scratch.approveKey = input.owner * 1000003 + input.spender;
        state.mut().allowances.set(state.mut().scratch.approveKey, input.amount);
        state.mut().scratch.approveValue = 0;
        state.get().allowances.get(state.mut().scratch.approveKey, state.mut().scratch.approveValue);
        state.mut().fetched = state.mut().scratch.approveValue;
        state.mut().population = state.get().allowances.population();
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Approve, 1);
    }
};
