// PairedTablesKeptConsistent — ported from test/libsolidity/semanticTests/mappings/mapping_of_mappings.sol
// Stresses: a forward and a reverse table updated together, with an audit pass that walks one and checks the other — the shape where a removal from one side leaves the other pointing at nothing
// Variant: capacity=1024 entryOrder=reversed entryShape=viaPrivate initStyle=full placement=nested stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct PairedTablesKeptConsistent2
{
};

struct PairedTablesKeptConsistent : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        HashMap<uint64, uint64, 1024> forward;
        HashMap<uint64, uint64, 1024> reverse;
        uint64 bound;
        uint64 unbound;
        uint64 orphans;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct UnbindForwardOnly_input
    {
        uint64 left;
    };

    struct UnbindForwardOnly_output {};

    struct UnbindForwardOnly_locals
    {
        UnbindForwardOnly_input forwardedInput;
        UnbindForwardOnly_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(UnbindForwardOnly)
    {
        locals.forwardedInput = input;
        CALL(UnbindForwardOnlyBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 bound;
        uint64 unbound;
        uint64 orphans;
        uint64 forwardPopulation;
        uint64 reversePopulation;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Bind_input
    {
        uint64 left;
        uint64 right;
    };

    struct Bind_output {};

    struct Bind_locals
    {
        Bind_input forwardedInput;
        Bind_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Bind)
    {
        locals.forwardedInput = input;
        CALL(BindBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Audit_input
    {
        uint64 count;
    };

    struct Audit_output {};

    struct Audit_locals
    {
        Audit_input forwardedInput;
        Audit_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Audit)
    {
        locals.forwardedInput = input;
        CALL(AuditBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using UnbindForwardOnlyBody_input = UnbindForwardOnly_input;

    using UnbindForwardOnlyBody_output = UnbindForwardOnly_output;

    struct UnbindForwardOnlyBody_locals
    {
        sint64 slot;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(UnbindForwardOnlyBody)
    {
        locals.slot = state.mut().inner.forward.removeByKey(input.left);
        if (locals.slot >= 0)
        {
        state.mut().inner.unbound++;
        }
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.bound = state.get().inner.bound;
        output.unbound = state.get().inner.unbound;
        output.orphans = state.get().inner.orphans;
        output.forwardPopulation = state.get().inner.forward.population();
        output.reversePopulation = state.get().inner.reverse.population();
    }

    using BindBody_input = Bind_input;

    using BindBody_output = Bind_output;

    struct BindBody_locals
    {
        sint64 slot;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(BindBody)
    {
        locals.slot = state.mut().inner.forward.set(input.left, input.right);
        locals.slot = state.mut().inner.reverse.set(input.right, input.left);
        state.mut().inner.bound++;
    }

    using AuditBody_input = Audit_input;

    using AuditBody_output = Audit_output;

    struct AuditBody_locals
    {
        uint64 i;
        uint64 right;
        uint64 left;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(AuditBody)
    {
        state.mut().inner.orphans = 0;
        for (locals.i = 0; locals.i < input.count; locals.i++)
        {
        locals.right = 0;
        if (state.get().inner.forward.get(locals.i, locals.right))
        {
        locals.left = 18446744073709551615ULL;
        if (!state.get().inner.reverse.get(locals.right, locals.left) || locals.left != locals.i)
        {
        state.mut().inner.orphans++;
        }
        }
        }
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Bind, 1);
        REGISTER_USER_PROCEDURE(UnbindForwardOnly, 2);
        REGISTER_USER_PROCEDURE(Audit, 3);
    }

    INITIALIZE()
    {
        state.mut().inner.forward.reset();
        state.mut().inner.reverse.reset();
        state.mut().inner.bound = 0;
        state.mut().inner.unbound = 0;
        state.mut().inner.orphans = 0;
    }
};
