// PrefixSumsAndRangeQueries — ported from no Solidity analogue (prefix sums)
// Stresses: a prefix-sum array maintained on every write, with range queries answered by subtraction — a wrong prefix shows up only when the range is queried, several calls later
// Variant: capacity=64 entryOrder=reversed entryShape=viaPrivate initStyle=full placement=last stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct PrefixSumsAndRangeQueries2
{
};

struct PrefixSumsAndRangeQueries : public ContractBase
{
    struct Scratch
    {
        uint64 setI;
        uint64 setRunning;
        uint64 rangeI;
        uint64 rangeDirect;
        uint64 rangeViaPrefix;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 mismatches;
        uint64 queries;
        uint64 lastRangeSum;
        Array<uint64, 64> prefix;
        Array<uint64, 64> values;
        Scratch scratch;
    };

    struct Set_input
    {
        uint64 index;
        uint64 value;
    };

    struct Set_output {};

    struct Set_locals
    {
        Set_input forwardedInput;
        Set_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Set)
    {
        locals.forwardedInput = input;
        CALL(SetBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 lastRangeSum;
        uint64 queries;
        uint64 mismatches;
        uint64 total;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Range_input
    {
        uint64 from;
        uint64 to;
    };

    struct Range_output
    {
        uint64 sum;
    };

    struct Range_locals
    {
        Range_input forwardedInput;
        Range_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Range)
    {
        locals.forwardedInput = input;
        CALL(RangeBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using SetBody_input = Set_input;

    using SetBody_output = Set_output;

    PRIVATE_PROCEDURE(SetBody)
    {
        state.mut().values.set(input.index, input.value);
        state.mut().scratch.setRunning = 0;
        for (state.mut().scratch.setI = 0; state.mut().scratch.setI < 64; state.mut().scratch.setI++)
        {
        state.mut().scratch.setRunning += state.get().values.get(state.mut().scratch.setI);
        state.mut().prefix.set(state.mut().scratch.setI, state.mut().scratch.setRunning);
        }
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.lastRangeSum = state.get().lastRangeSum;
        output.queries = state.get().queries;
        output.mismatches = state.get().mismatches;
        output.total = state.get().prefix.get(63);
    }

    using RangeBody_input = Range_input;

    using RangeBody_output = Range_output;

    PRIVATE_PROCEDURE(RangeBody)
    {
        state.mut().scratch.rangeDirect = 0;
        for (state.mut().scratch.rangeI = input.from; state.mut().scratch.rangeI < input.to && state.mut().scratch.rangeI < 64; state.mut().scratch.rangeI++)
        {
        state.mut().scratch.rangeDirect += state.get().values.get(state.mut().scratch.rangeI);
        }
        if (input.to == 0 || input.from >= 64)
        {
        state.mut().scratch.rangeViaPrefix = 0;
        }
        else if (input.from == 0)
        {
        state.mut().scratch.rangeViaPrefix = state.get().prefix.get(input.to - 1);
        }
        else
        {
        state.mut().scratch.rangeViaPrefix = state.get().prefix.get(input.to - 1) - state.get().prefix.get(input.from - 1);
        }
        state.mut().queries++;
        state.mut().lastRangeSum = state.mut().scratch.rangeViaPrefix;
        if (state.mut().scratch.rangeDirect != state.mut().scratch.rangeViaPrefix)
        {
        state.mut().mismatches++;
        }
        output.sum = state.mut().scratch.rangeViaPrefix;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Set, 1);
        REGISTER_USER_PROCEDURE(Range, 2);
    }

    INITIALIZE()
    {
        state.mut().values.setAll(0);
        state.mut().prefix.setAll(0);
        state.mut().lastRangeSum = 0;
        state.mut().queries = 0;
        state.mut().mismatches = 0;
    }
};
