// PriorityInsertionSorted — ported from no Solidity analogue (sorted insert)
// Stresses: insertion into a sorted array by shifting the tail — the shift runs backwards, and running it forwards instead smears one element over the rest
// Variant: capacity=8 entryOrder=declared entryShape=viaPrivate initStyle=absent placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct PriorityInsertionSorted2
{
};

struct PriorityInsertionSorted : public ContractBase
{
    struct Scratch
    {
        uint64 insertI;
        uint64 insertPosition;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 outOfOrder;
        uint64 rejected;
        uint64 shifts;
        uint64 length;
        Array<uint64, 8> values;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Insert_input
    {
        uint64 value;
    };

    struct Insert_output {};

    struct Insert_locals
    {
        Insert_input forwardedInput;
        Insert_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Insert)
    {
        locals.forwardedInput = input;
        CALL(InsertBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 length;
        uint64 shifts;
        uint64 rejected;
        uint64 outOfOrder;
        uint64 first;
        uint64 last;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using InsertBody_input = Insert_input;

    using InsertBody_output = Insert_output;

    PRIVATE_PROCEDURE(InsertBody)
    {
        if (state.get().inner.length >= 8)
        {
        state.mut().inner.rejected++;
        return;
        }
        state.mut().inner.scratch.insertPosition = state.get().inner.length;
        for (state.mut().inner.scratch.insertI = 0; state.mut().inner.scratch.insertI < state.get().inner.length; state.mut().inner.scratch.insertI++)
        {
        if (state.get().inner.values.get(state.mut().inner.scratch.insertI) > input.value && state.mut().inner.scratch.insertPosition == state.get().inner.length)
        {
        state.mut().inner.scratch.insertPosition = state.mut().inner.scratch.insertI;
        }
        }
        for (state.mut().inner.scratch.insertI = state.get().inner.length; state.mut().inner.scratch.insertI > state.mut().inner.scratch.insertPosition; state.mut().inner.scratch.insertI--)
        {
        state.mut().inner.values.set(state.mut().inner.scratch.insertI, state.get().inner.values.get(state.mut().inner.scratch.insertI - 1));
        state.mut().inner.shifts++;
        }
        state.mut().inner.values.set(state.mut().inner.scratch.insertPosition, input.value);
        state.mut().inner.length++;
        state.mut().inner.outOfOrder = 0;
        for (state.mut().inner.scratch.insertI = 1; state.mut().inner.scratch.insertI < state.get().inner.length; state.mut().inner.scratch.insertI++)
        {
        if (state.get().inner.values.get(state.mut().inner.scratch.insertI) < state.get().inner.values.get(state.mut().inner.scratch.insertI - 1))
        {
        state.mut().inner.outOfOrder++;
        }
        }
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.length = state.get().inner.length;
        output.shifts = state.get().inner.shifts;
        output.rejected = state.get().inner.rejected;
        output.outOfOrder = state.get().inner.outOfOrder;
        output.first = state.get().inner.values.get(0);
        output.last = state.get().inner.values.get(state.get().inner.length == 0 ? 0 : state.get().inner.length - 1);
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Insert, 1);
    }
};
