// RingBufferWrapAround — ported from openzeppelin-contracts/contracts/utils/structs/DoubleEndedQueue.sol
// Stresses: a ring buffer driven past its capacity so head and tail both wrap, with the count kept separately — the classic place an index is masked one element too late
// Variant: capacity=1024 entryOrder=declared entryShape=viaPrivate initStyle=full placement=nested stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct RingBufferWrapAround2
{
};

struct RingBufferWrapAround : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 popped;
        uint64 dropped;
        uint64 count;
        uint64 tail;
        uint64 head;
        Array<uint64, 1024> slots;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Pop_input {};

    struct Pop_output
    {
        uint64 value;
    };

    struct Pop_locals
    {
        Pop_input forwardedInput;
        Pop_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Pop)
    {
        CALL(PopBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Push_input
    {
        uint64 value;
    };

    struct Push_output {};

    struct Push_locals
    {
        Push_input forwardedInput;
        Push_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Push)
    {
        locals.forwardedInput = input;
        CALL(PushBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 head;
        uint64 tail;
        uint64 count;
        uint64 dropped;
        uint64 popped;
        uint64 first;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using PopBody_input = Pop_input;

    using PopBody_output = Pop_output;

    struct PopBody_locals
    {
        uint64 index;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(PopBody)
    {
        if (state.get().inner.count == 0)
        {
        output.value = 0;
        }
        else
        {
        locals.index = QPI::mod(state.get().inner.head, (uint64)1024);
        output.value = state.get().inner.slots.get(locals.index);
        state.mut().inner.head++;
        state.mut().inner.count--;
        state.mut().inner.popped++;
        }
    }

    using PushBody_input = Push_input;

    using PushBody_output = Push_output;

    struct PushBody_locals
    {
        uint64 index;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(PushBody)
    {
        if (state.get().inner.count == 1024)
        {
        state.mut().inner.dropped++;
        }
        else
        {
        locals.index = QPI::mod(state.get().inner.tail, (uint64)1024);
        state.mut().inner.slots.set(locals.index, input.value);
        state.mut().inner.tail++;
        state.mut().inner.count++;
        }
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.head = state.get().inner.head;
        output.tail = state.get().inner.tail;
        output.count = state.get().inner.count;
        output.dropped = state.get().inner.dropped;
        output.popped = state.get().inner.popped;
        output.first = state.get().inner.slots.get(QPI::mod(state.get().inner.head, (uint64)1024));
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Push, 1);
        REGISTER_USER_PROCEDURE(Pop, 2);
    }

    INITIALIZE()
    {
        state.mut().inner.slots.setAll(0);
        state.mut().inner.head = 0;
        state.mut().inner.tail = 0;
        state.mut().inner.count = 0;
        state.mut().inner.dropped = 0;
        state.mut().inner.popped = 0;
    }
};
