// StackPushPopUnderflow — ported from test/libsolidity/semanticTests/array/pop_array_storage.sol
// Stresses: a stack popped past empty, where the depth counter must not wrap and the element left behind must not be read as live
// Port caveat: Solidity's `pop()` on an empty array reverts; the port returns a sentinel and counts the attempt, since QPI has no revert.
// Variant: capacity=1024 entryOrder=declared entryShape=direct initStyle=full placement=last stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct StackPushPopUnderflow2
{
};

struct StackPushPopUnderflow : public ContractBase
{
    struct Scratch
    {
        uint64 pushScratch;
        uint64 popScratch;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 lastPopped;
        uint64 overflows;
        uint64 underflows;
        uint64 depth;
        Array<uint64, 1024> slots;
        Scratch scratch;
    };

    struct Pop_input {};

    struct Pop_output
    {
        uint64 value;
    };

    PUBLIC_PROCEDURE(Pop)
    {
        if (state.get().depth == 0)
        {
        state.mut().underflows++;
        output.value = 18446744073709551615ULL;
        }
        else
        {
        state.mut().depth--;
        state.mut().lastPopped = state.get().slots.get(state.get().depth);
        output.value = state.get().lastPopped;
        }
    }

    struct Push_input
    {
        uint64 value;
    };

    struct Push_output {};

    PUBLIC_PROCEDURE(Push)
    {
        if (state.get().depth >= 1024)
        {
        state.mut().overflows++;
        }
        else
        {
        state.mut().slots.set(state.get().depth, input.value);
        state.mut().depth++;
        }
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 depth;
        uint64 underflows;
        uint64 overflows;
        uint64 lastPopped;
        uint64 topSlot;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.depth = state.get().depth;
        output.underflows = state.get().underflows;
        output.overflows = state.get().overflows;
        output.lastPopped = state.get().lastPopped;
        output.topSlot = state.get().slots.get(state.get().depth);
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Push, 1);
        REGISTER_USER_PROCEDURE(Pop, 2);
    }

    INITIALIZE()
    {
        state.mut().slots.setAll(0);
        state.mut().depth = 0;
        state.mut().underflows = 0;
        state.mut().overflows = 0;
        state.mut().lastPopped = 0;
    }
};
