// FunctionMustNotMutate — ported from test/libsolidity/semanticTests/state/state_variables_view.sol
// Stresses: a function call must not move the state digest
// Port caveat: negative control — a digest that moves across a function call is a finding on its own
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full placement=last stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct FunctionMustNotMutate2
{
};

struct FunctionMustNotMutate : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        uint64 value;
        uint64 reads;
    };

    struct Get_input {};

    struct Get_output
    {
        uint64 value;
        uint64 doubled;
    };

    struct Get_locals
    {
        Get_input forwardedInput;
        Get_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Get)
    {
        CALL(GetBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Set_input
    {
        uint64 value;
    };

    struct Set_output {};

    struct Set_locals
    {
        Set_input forwardedInput;
        Set_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Set)
    {
        locals.forwardedInput = input;
        CALL(SetBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using GetBody_input = Get_input;

    using GetBody_output = Get_output;

    struct GetBody_locals
    {
        uint64 scratch;
    };

    PRIVATE_FUNCTION_WITH_LOCALS(GetBody)
    {
        locals.scratch = state.get().value;
        output.value = locals.scratch;
        output.doubled = locals.scratch * 2;
    }

    using SetBody_input = Set_input;

    using SetBody_output = Set_output;

    struct SetBody_locals
    {
        uint64 scratch;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(SetBody)
    {
        state.mut().value = input.value;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Get, 1);
        REGISTER_USER_PROCEDURE(Set, 1);
    }

    INITIALIZE()
    {
        state.mut().value = 0;
        state.mut().reads = 0;
    }
};
