// HookRefusesWhenStateUninitialised — ported from openzeppelin-contracts/contracts/proxy/utils/Initializable.sol
// Stresses: a tick hook that does nothing until an entry has run once — the guard lives in hook code, where a wrong initial value means the hook either never starts or starts immediately
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=absent placement=first stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HookRefusesWhenStateUninitialised2
{
};

struct HookRefusesWhenStateUninitialised : public ContractBase
{
    struct StateData
    {
        uint64 accrued;
        uint64 hookSkips;
        uint64 hookRuns;
        uint64 armed;
        uint64 placementGuard;
    };

    struct Arm_input
    {
        uint64 unused;
    };

    struct Arm_output {};

    struct Arm_locals
    {
        Arm_input forwardedInput;
        Arm_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Arm)
    {
        locals.forwardedInput = input;
        CALL(ArmBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 armed;
        uint64 hookRuns;
        uint64 hookSkips;
        uint64 accrued;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using ArmBody_input = Arm_input;

    using ArmBody_output = Arm_output;

    struct ArmBody_locals
    {
        uint64 scratch;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(ArmBody)
    {
        state.mut().armed = 1;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.armed = state.get().armed;
        output.hookRuns = state.get().hookRuns;
        output.hookSkips = state.get().hookSkips;
        output.accrued = state.get().accrued;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Arm, 1);
    }

    BEGIN_TICK()
    {
        if (state.get().armed == 0)
        {
        state.mut().hookSkips++;
        }
        else
        {
        state.mut().accrued += 7;
        state.mut().hookRuns++;
        }
    }
};
