// IdleTicksMoveOnlyHookState — ported from test/libsolidity/semanticTests/state/state_variables_view.sol
// Stresses: state that must not move while ticks pass
// Port caveat: negative control — a payload digest that moves across idle ticks is a finding on its own
// Variant: entryOrder=reversed entryShape=direct initStyle=empty placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct IdleTicksMoveOnlyHookState2
{
};

struct IdleTicksMoveOnlyHookState : public ContractBase
{
    struct Scratch
    {
        uint64 setI;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 idleTicks;
        Array<uint64, 8> table;
        uint64 payload;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Set_input
    {
        uint64 value;
    };

    struct Set_output {};

    PUBLIC_PROCEDURE(Set)
    {
        state.mut().inner.payload = input.value;
        for (state.mut().inner.scratch.setI = 0; state.mut().inner.scratch.setI < 8; state.mut().inner.scratch.setI++)
        {
        state.mut().inner.table.set(state.mut().inner.scratch.setI, input.value + state.mut().inner.scratch.setI);
        }
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 payload;
        uint64 tableSeven;
        uint64 idleTicks;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.payload = state.get().inner.payload;
        output.tableSeven = state.get().inner.table.get(7);
        output.idleTicks = state.get().inner.idleTicks;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Set, 1);
    }

    INITIALIZE()
    {

    }

    END_TICK()
    {
        state.mut().inner.idleTicks++;
    }
};
