// IdleTicksMoveOnlyHookState — ported from test/libsolidity/semanticTests/state/state_variables_view.sol
// Stresses: state that must not move while ticks pass
// Port caveat: negative control — a payload digest that moves across idle ticks is a finding on its own
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=empty placement=first stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct IdleTicksMoveOnlyHookState2
{
};

struct IdleTicksMoveOnlyHookState : public ContractBase
{
    struct Scratch
    {
        uint64 setI;
    };

    struct StateData
    {
        uint64 payload;
        Array<uint64, 8> table;
        uint64 idleTicks;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 payload;
        uint64 tableSeven;
        uint64 idleTicks;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Set_input
    {
        uint64 value;
    };

    struct Set_output {};

    struct Set_locals
    {
        Set_input forwardedInput;
        Set_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Set)
    {
        locals.forwardedInput = input;
        CALL(SetBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.payload = state.get().payload;
        output.tableSeven = state.get().table.get(7);
        output.idleTicks = state.get().idleTicks;
    }

    using SetBody_input = Set_input;

    using SetBody_output = Set_output;

    PRIVATE_PROCEDURE(SetBody)
    {
        state.mut().payload = input.value;
        for (state.mut().scratch.setI = 0; state.mut().scratch.setI < 8; state.mut().scratch.setI++)
        {
        state.mut().table.set(state.mut().scratch.setI, input.value + state.mut().scratch.setI);
        }
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Set, 1);
    }

    INITIALIZE()
    {

    }

    END_TICK()
    {
        state.mut().idleTicks++;
    }
};
