// InitializeArrayFillPattern — ported from test/libsolidity/semanticTests/constructor/constructor_static_array_argument.sol
// Stresses: a loop inside INITIALIZE, with a running checksum
// Port caveat: constructor arguments become a computed pattern
// Variant: capacity=1024 entryOrder=reversed entryShape=viaPrivate initStyle=absent placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct InitializeArrayFillPattern2
{
};

struct InitializeArrayFillPattern : public ContractBase
{
    struct Scratch
    {
        uint64 pokePrevious;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 writes;
        uint64 checksum;
        Array<uint64, 1024> pattern;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 checksum;
        uint64 writes;
        uint64 first;
        uint64 last;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Poke_input
    {
        uint64 index;
        uint64 value;
    };

    struct Poke_output {};

    struct Poke_locals
    {
        Poke_input forwardedInput;
        Poke_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Poke)
    {
        locals.forwardedInput = input;
        CALL(PokeBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.checksum = state.get().inner.checksum;
        output.writes = state.get().inner.writes;
        output.first = state.get().inner.pattern.get(0);
        output.last = state.get().inner.pattern.get(1023);
    }

    using PokeBody_input = Poke_input;

    using PokeBody_output = Poke_output;

    PRIVATE_PROCEDURE(PokeBody)
    {
        state.mut().inner.scratch.pokePrevious = state.get().inner.pattern.get(input.index);
        state.mut().inner.pattern.set(input.index, input.value);
        state.mut().inner.checksum += input.value - state.mut().inner.scratch.pokePrevious;
        state.mut().inner.writes++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Poke, 1);
    }
};
