// InitializeFillsContainerThenHooksTouchIt — ported from test/libsolidity/semanticTests/constructor/constructor_static_array_argument.sol
// Stresses: a container filled at construction and then rotated one slot per tick by the hook — construction-time state that hook code keeps moving, with no entry involved
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=absent placement=nested stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct InitializeFillsContainerThenHooksTouchIt2
{
};

struct InitializeFillsContainerThenHooksTouchIt : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 checksum;
        uint64 rotations;
        Array<uint64, 8> ring;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 rotations;
        uint64 checksum;
        uint64 first;
        uint64 last;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Peek_input
    {
        uint64 unused;
    };

    struct Peek_output {};

    struct Peek_locals
    {
        Peek_input forwardedInput;
        Peek_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Peek)
    {
        locals.forwardedInput = input;
        CALL(PeekBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.rotations = state.get().inner.rotations;
        output.checksum = state.get().inner.checksum;
        output.first = state.get().inner.ring.get(0);
        output.last = state.get().inner.ring.get(7);
    }

    using PeekBody_input = Peek_input;

    using PeekBody_output = Peek_output;

    struct PeekBody_locals
    {
        uint64 i;
        uint64 sum;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(PeekBody)
    {
        locals.sum = 0;
        for (locals.i = 0; locals.i < 8; locals.i++)
        {
        locals.sum += state.get().inner.ring.get(locals.i);
        }
        state.mut().inner.checksum = locals.sum;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Peek, 1);
    }

    struct END_TICK_locals
    {
        uint64 i;
        uint64 first;
    };

    END_TICK_WITH_LOCALS()
    {
        locals.first = state.get().inner.ring.get(0);
        for (locals.i = 0; locals.i < 7; locals.i++)
        {
        state.mut().inner.ring.set(locals.i, state.get().inner.ring.get(locals.i + 1));
        }
        state.mut().inner.ring.set(7, locals.first);
        state.mut().inner.rotations++;
    }
};
