// InitializeFillsContainerThenHooksTouchIt — ported from test/libsolidity/semanticTests/constructor/constructor_static_array_argument.sol
// Stresses: a container filled at construction and then rotated one slot per tick by the hook — construction-time state that hook code keeps moving, with no entry involved
// Variant: entryOrder=reversed entryShape=direct initStyle=empty placement=first stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct InitializeFillsContainerThenHooksTouchIt2
{
};

struct InitializeFillsContainerThenHooksTouchIt : public ContractBase
{
    struct StateData
    {
        uint64 checksum;
        uint64 rotations;
        Array<uint64, 8> ring;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 rotations;
        uint64 checksum;
        uint64 first;
        uint64 last;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.rotations = state.get().rotations;
        output.checksum = state.get().checksum;
        output.first = state.get().ring.get(0);
        output.last = state.get().ring.get(7);
    }

    struct Peek_input
    {
        uint64 unused;
    };

    struct Peek_output {};

    struct Peek_locals
    {
        uint64 i;
        uint64 sum;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Peek)
    {
        locals.sum = 0;
        for (locals.i = 0; locals.i < 8; locals.i++)
        {
        locals.sum += state.get().ring.get(locals.i);
        }
        state.mut().checksum = locals.sum;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Peek, 1);
    }

    INITIALIZE()
    {

    }

    struct END_TICK_locals
    {
        uint64 i;
        uint64 first;
    };

    END_TICK_WITH_LOCALS()
    {
        locals.first = state.get().ring.get(0);
        for (locals.i = 0; locals.i < 7; locals.i++)
        {
        state.mut().ring.set(locals.i, state.get().ring.get(locals.i + 1));
        }
        state.mut().ring.set(7, locals.first);
        state.mut().rotations++;
    }
};
