// InitializeFillsContainerThenHooksTouchIt — ported from test/libsolidity/semanticTests/constructor/constructor_static_array_argument.sol
// Stresses: a container filled at construction and then rotated one slot per tick by the hook — construction-time state that hook code keeps moving, with no entry involved
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=empty placement=nested stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct InitializeFillsContainerThenHooksTouchIt2
{
};

struct InitializeFillsContainerThenHooksTouchIt : public ContractBase
{
    struct Scratch
    {
        uint64 peekI;
        uint64 peekSum;
    };

    struct StateData
    {
        struct Inner
        {
        Array<uint64, 8> ring;
        uint64 rotations;
        uint64 checksum;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 rotations;
        uint64 checksum;
        uint64 first;
        uint64 last;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Peek_input
    {
        uint64 unused;
    };

    struct Peek_output {};

    struct Peek_locals
    {
        Peek_input forwardedInput;
        Peek_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Peek)
    {
        locals.forwardedInput = input;
        CALL(PeekBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.rotations = state.get().inner.rotations;
        output.checksum = state.get().inner.checksum;
        output.first = state.get().inner.ring.get(0);
        output.last = state.get().inner.ring.get(7);
    }

    using PeekBody_input = Peek_input;

    using PeekBody_output = Peek_output;

    PRIVATE_PROCEDURE(PeekBody)
    {
        state.mut().inner.scratch.peekSum = 0;
        for (state.mut().inner.scratch.peekI = 0; state.mut().inner.scratch.peekI < 8; state.mut().inner.scratch.peekI++)
        {
        state.mut().inner.scratch.peekSum += state.get().inner.ring.get(state.mut().inner.scratch.peekI);
        }
        state.mut().inner.checksum = state.mut().inner.scratch.peekSum;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Peek, 1);
    }

    INITIALIZE()
    {

    }

    struct END_TICK_locals
    {
        uint64 i;
        uint64 first;
    };

    END_TICK_WITH_LOCALS()
    {
        locals.first = state.get().inner.ring.get(0);
        for (locals.i = 0; locals.i < 7; locals.i++)
        {
        state.mut().inner.ring.set(locals.i, state.get().inner.ring.get(locals.i + 1));
        }
        state.mut().inner.ring.set(7, locals.first);
        state.mut().inner.rotations++;
    }
};
