// TickAndEpochHooks — ported from no Solidity analogue
// Stresses: the four lifecycle hooks
// Variant: entryOrder=declared entryShape=direct initStyle=empty placement=nested stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct TickAndEpochHooks2
{
};

struct TickAndEpochHooks : public ContractBase
{
    struct Scratch
    {
        uint64 touchScratch;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 beginTicks;
        uint64 endTicks;
        uint64 beginEpochs;
        uint64 endEpochs;
        uint64 userCalls;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 beginTicks;
        uint64 endTicks;
        uint64 beginEpochs;
        uint64 endEpochs;
        uint64 userCalls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.beginTicks = state.get().inner.beginTicks;
        output.endTicks = state.get().inner.endTicks;
        output.beginEpochs = state.get().inner.beginEpochs;
        output.endEpochs = state.get().inner.endEpochs;
        output.userCalls = state.get().inner.userCalls;
    }

    struct Touch_input
    {
        uint64 value;
    };

    struct Touch_output {};

    PUBLIC_PROCEDURE(Touch)
    {
        state.mut().inner.userCalls += input.value;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Touch, 1);
    }

    INITIALIZE()
    {

    }

    BEGIN_TICK()
    {
        state.mut().inner.beginTicks++;
    }

    END_TICK()
    {
        state.mut().inner.endTicks++;
    }

    BEGIN_EPOCH()
    {
        state.mut().inner.beginEpochs++;
    }

    END_EPOCH()
    {
        state.mut().inner.endEpochs++;
    }
};
