// TwoHooksWriteOneMember — ported from no Solidity analogue
// Stresses: BEGIN_TICK and END_TICK both writing the same member, so its value between them is only observable from an entry that runs in that window
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=absent placement=nested stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct TwoHooksWriteOneMember2
{
};

struct TwoHooksWriteOneMember : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 endRuns;
        uint64 beginRuns;
        uint64 seenInEntry;
        uint64 phase;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Observe_input
    {
        uint64 unused;
    };

    struct Observe_output {};

    struct Observe_locals
    {
        Observe_input forwardedInput;
        Observe_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Observe)
    {
        locals.forwardedInput = input;
        CALL(ObserveBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 phase;
        uint64 seenInEntry;
        uint64 beginRuns;
        uint64 endRuns;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using ObserveBody_input = Observe_input;

    using ObserveBody_output = Observe_output;

    struct ObserveBody_locals
    {
        uint64 scratch;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(ObserveBody)
    {
        state.mut().inner.seenInEntry = state.get().inner.phase;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.phase = state.get().inner.phase;
        output.seenInEntry = state.get().inner.seenInEntry;
        output.beginRuns = state.get().inner.beginRuns;
        output.endRuns = state.get().inner.endRuns;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Observe, 1);
    }

    BEGIN_TICK()
    {
        state.mut().inner.phase = 1;
        state.mut().inner.beginRuns++;
    }

    END_TICK()
    {
        state.mut().inner.phase = 2;
        state.mut().inner.endRuns++;
    }
};
