// AssetOwnershipIteratorOwnerFilterIgnored — ported from openzeppelin-contracts/contracts/token/ERC20/extensions/ERC20Snapshot.sol (per-holder balance enumeration)
// Stresses: an AssetOwnershipIterator opened with AssetOwnershipSelect::byOwner — the filter is accepted, compiles and runs, and the walk it produces is compared against the same walk opened with any()
// Port caveat: The Solidity original enumerates a mapping it controls; QPI enumerates the host's ledger, so the port mirrors what it reads into state to make the difference visible to a state digest.
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full placement=first stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct AssetOwnershipIteratorOwnerFilterIgnored2
{
};

struct AssetOwnershipIteratorOwnerFilterIgnored : public ContractBase
{
    struct StateData
    {
        uint64 calls;
        uint64 unfilteredShares;
        uint64 unfilteredCount;
        uint64 filteredShares;
        uint64 filteredCount;
        uint64 placementGuard;
    };

    struct Probe_input
    {
        uint64 a;
        uint64 b;
    };

    struct Probe_output {};

    struct Probe_locals
    {
        Probe_input forwardedInput;
        Probe_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Probe)
    {
        locals.forwardedInput = input;
        CALL(ProbeBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 filteredCount;
        uint64 filteredShares;
        uint64 unfilteredCount;
        uint64 unfilteredShares;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using ProbeBody_input = Probe_input;

    using ProbeBody_output = Probe_output;

    struct ProbeBody_locals
    {
        id other;
        Asset asset;
        AssetOwnershipIterator iter;
        uint64 guard;
        sint64 outcome;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(ProbeBody)
    {
        locals.other = id(input.a, 0, 0, 0);
        locals.outcome = qpi.issueAsset(5521745ULL, SELF, 0, 1000, 0);
        locals.outcome = qpi.transferShareOwnershipAndPossession(5521745ULL, SELF, SELF, SELF, input.b, locals.other);
        locals.asset.issuer = SELF;
        locals.asset.assetName = 5521745ULL;

        locals.iter.begin(locals.asset, AssetOwnershipSelect::byOwner(locals.other));
        locals.guard = 0;
        while (!locals.iter.reachedEnd() && locals.guard < 16)
        {
        state.mut().filteredCount++;
        state.mut().filteredShares += locals.iter.numberOfOwnedShares();
        locals.iter.next();
        locals.guard++;
        }

        // The same walk with no filter, as the control that separates "the filter was
        // dropped" from "the iteration is broken".
        locals.iter.begin(locals.asset, AssetOwnershipSelect::any());
        locals.guard = 0;
        while (!locals.iter.reachedEnd() && locals.guard < 16)
        {
        state.mut().unfilteredCount++;
        state.mut().unfilteredShares += locals.iter.numberOfOwnedShares();
        locals.iter.next();
        locals.guard++;
        }

        state.mut().calls++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.filteredCount = state.get().filteredCount;
        output.filteredShares = state.get().filteredShares;
        output.unfilteredCount = state.get().unfilteredCount;
        output.unfilteredShares = state.get().unfilteredShares;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Probe, 1);
    }

    INITIALIZE()
    {
        state.mut().filteredCount = 0;
        state.mut().filteredShares = 0;
        state.mut().unfilteredCount = 0;
        state.mut().unfilteredShares = 0;
        state.mut().calls = 0;
    }
};
