// Erc20AllowanceUnderflow — ported from test/libsolidity/semanticTests/various/erc20.sol
// Stresses: allowance decrement at and below zero
// Port caveat: Solidity reverts on the underflow; the port records both the guarded and the wrapped result
// Variant: capacity=2 entryOrder=reversed entryShape=viaPrivate initStyle=absent placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct Erc20AllowanceUnderflow2
{
};

struct Erc20AllowanceUnderflow : public ContractBase
{
    struct Scratch
    {
        uint64 approveScratch;
        uint64 spendAllowed;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 rejections;
        uint64 wrapped;
        uint64 guarded;
        HashMap<uint64, uint64, 2> allowances;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Spend_input
    {
        uint64 key;
        uint64 amount;
    };

    struct Spend_output
    {
        uint64 ok;
    };

    struct Spend_locals
    {
        Spend_input forwardedInput;
        Spend_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Spend)
    {
        locals.forwardedInput = input;
        CALL(SpendBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 guarded;
        uint64 wrapped;
        uint64 rejections;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Approve_input
    {
        uint64 key;
        uint64 amount;
    };

    struct Approve_output {};

    struct Approve_locals
    {
        Approve_input forwardedInput;
        Approve_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Approve)
    {
        locals.forwardedInput = input;
        CALL(ApproveBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using SpendBody_input = Spend_input;

    using SpendBody_output = Spend_output;

    PRIVATE_PROCEDURE(SpendBody)
    {
        state.mut().inner.scratch.spendAllowed = 0;
        state.get().inner.allowances.get(input.key, state.mut().inner.scratch.spendAllowed);
        // What the unguarded Solidity subtraction would leave behind, recorded for comparison.
        state.mut().inner.wrapped = state.mut().inner.scratch.spendAllowed - input.amount;
        if (state.mut().inner.scratch.spendAllowed < input.amount)
        {
        state.mut().inner.rejections++;
        output.ok = 0;
        return;
        }
        state.mut().inner.guarded = state.mut().inner.scratch.spendAllowed - input.amount;
        state.mut().inner.allowances.set(input.key, state.get().inner.guarded);
        output.ok = 1;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.guarded = state.get().inner.guarded;
        output.wrapped = state.get().inner.wrapped;
        output.rejections = state.get().inner.rejections;
    }

    using ApproveBody_input = Approve_input;

    using ApproveBody_output = Approve_output;

    PRIVATE_PROCEDURE(ApproveBody)
    {
        state.mut().inner.allowances.set(input.key, input.amount);
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Approve, 1);
        REGISTER_USER_PROCEDURE(Spend, 2);
    }
};
