// InvocatorAndReward — ported from test/libsolidity/semanticTests/payable/payable_receive.sol
// Stresses: invocator / originator / invocationReward
// Variant: entryOrder=declared entryShape=direct initStyle=empty placement=first stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct InvocatorAndReward2
{
};

struct InvocatorAndReward : public ContractBase
{
    struct Scratch
    {
        id payWho;
    };

    struct StateData
    {
        id lastInvocator;
        id lastOriginator;
        sint64 totalReward;
        uint64 sameCount;
        uint64 selfCount;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Pay_input
    {
        uint64 unused;
    };

    struct Pay_output {};

    PUBLIC_PROCEDURE(Pay)
    {
        state.mut().scratch.payWho = qpi.invocator();
        state.mut().lastInvocator = state.mut().scratch.payWho;
        state.mut().lastOriginator = qpi.originator();
        state.mut().totalReward += qpi.invocationReward();
        if (state.mut().scratch.payWho == qpi.originator())
        {
        state.mut().sameCount++;
        }
        if (state.mut().scratch.payWho == SELF)
        {
        state.mut().selfCount++;
        }
    }

    struct Read_input {};

    struct Read_output
    {
        sint64 totalReward;
        uint64 sameCount;
        uint64 selfCount;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.totalReward = state.get().totalReward;
        output.sameCount = state.get().sameCount;
        output.selfCount = state.get().selfCount;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Pay, 1);
    }

    INITIALIZE()
    {

    }
};
