// SharesTransferToIssuerAndSelf — ported from openzeppelin-contracts/contracts/token/ERC20/ERC20.sol (self-transfer)
// Stresses: a transfer whose destination is the sender, and one whose destination is the issuer — the aliasing cases where a naive implementation debits before crediting and loses the shares
// Variant: entryOrder=declared entryShape=direct initStyle=absent placement=first stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SharesTransferToIssuerAndSelf2
{
};

struct SharesTransferToIssuerAndSelf : public ContractBase
{
    struct Scratch
    {
        sint64 runIssued;
        sint64 runBefore;
    };

    struct StateData
    {
        uint64 calls;
        uint64 preserved;
        sint64 balanceAfter;
        sint64 issuerTransfer;
        sint64 selfTransfer;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        sint64 selfTransfer;
        sint64 issuerTransfer;
        sint64 balanceAfter;
        uint64 preserved;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.selfTransfer = state.get().selfTransfer;
        output.issuerTransfer = state.get().issuerTransfer;
        output.balanceAfter = state.get().balanceAfter;
        output.preserved = state.get().preserved;
        output.calls = state.get().calls;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    PUBLIC_PROCEDURE(Run)
    {
        state.mut().scratch.runIssued = qpi.issueAsset(5525825ULL, SELF, 0, (sint64)QPI::mod(input.a, 100000ULL), 0);
        state.mut().scratch.runBefore = qpi.numberOfPossessedShares(5525825ULL, SELF, SELF, SELF, SELF_INDEX, SELF_INDEX);
        state.mut().selfTransfer = qpi.transferShareOwnershipAndPossession(5525825ULL, SELF, SELF, SELF, (sint64)QPI::mod(input.b, 100ULL), SELF);
        state.mut().issuerTransfer = qpi.transferShareOwnershipAndPossession(5525825ULL, SELF, SELF, SELF, (sint64)QPI::mod(input.b, 100ULL), SELF);
        state.mut().balanceAfter = qpi.numberOfPossessedShares(5525825ULL, SELF, SELF, SELF, SELF_INDEX, SELF_INDEX);
        state.mut().preserved = state.get().balanceAfter == state.mut().scratch.runBefore ? 1 : 0;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }
};
