// SharesUnitOfMeasurementRoundTrip — ported from openzeppelin-contracts/contracts/token/ERC20/extensions/ERC20Metadata.sol (decimals)
// Stresses: the unit-of-measurement word carried through issuance — an eight-byte field the host stores and the contract never reads back, so its only effect is on whether the issuance is accepted
// Variant: entryOrder=declared entryShape=direct initStyle=empty placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SharesUnitOfMeasurementRoundTrip2
{
};

struct SharesUnitOfMeasurementRoundTrip : public ContractBase
{
    struct Scratch
    {
        sint64 runOutcome;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 calls;
        uint64 lastUnit;
        uint64 distinctUnits;
        uint64 accepted;
        sint64 result;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        sint64 result;
        uint64 accepted;
        uint64 distinctUnits;
        uint64 lastUnit;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.result = state.get().inner.result;
        output.accepted = state.get().inner.accepted;
        output.distinctUnits = state.get().inner.distinctUnits;
        output.lastUnit = state.get().inner.lastUnit;
        output.calls = state.get().inner.calls;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    PUBLIC_PROCEDURE(Run)
    {
        state.mut().inner.scratch.runOutcome = qpi.issueAsset(5525825ULL + QPI::mod(input.b, 8ULL), SELF, 0, 100, input.a);
        state.mut().inner.result = state.mut().inner.scratch.runOutcome;
        if (state.mut().inner.scratch.runOutcome > 0)
        {
        state.mut().inner.accepted++;
        }
        if (input.a != state.get().inner.lastUnit)
        {
        state.mut().inner.distinctUnits++;
        }
        state.mut().inner.lastUnit = input.a;

        state.mut().inner.calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
