// SharesMultipleAssetsOneContract — ported from openzeppelin-contracts/contracts/token/ERC1155/ERC1155.sol
// Stresses: three assets issued by one contract and counted separately — the multi-token case, where a query for one name must not see another's shares
// Variant: base
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SharesMultipleAssetsOneContract2
{
};

struct SharesMultipleAssetsOneContract : public ContractBase
{
    struct StateData
    {
        sint64 firstCount;
        sint64 secondCount;
        sint64 thirdCount;
        uint64 issued;
        uint64 calls;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        sint64 firstCount;
        sint64 secondCount;
        sint64 thirdCount;
        uint64 issued;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.firstCount = state.get().firstCount;
        output.secondCount = state.get().secondCount;
        output.thirdCount = state.get().thirdCount;
        output.issued = state.get().issued;
        output.calls = state.get().calls;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        sint64 outcome;
        uint64 amount;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.amount = QPI::mod(input.a, 10000ULL) + 1;
        locals.outcome = qpi.issueAsset(5525825ULL, SELF, 0, (sint64)locals.amount, 0);
        if (locals.outcome > 0)
        {
        state.mut().issued++;
        }
        locals.outcome = qpi.issueAsset(5525825ULL + 1, SELF, 0, (sint64)(locals.amount * 2), 0);
        if (locals.outcome > 0)
        {
        state.mut().issued++;
        }
        locals.outcome = qpi.issueAsset(5525825ULL + 2, SELF, 0, (sint64)(locals.amount * 3), 0);
        if (locals.outcome > 0)
        {
        state.mut().issued++;
        }
        state.mut().firstCount = qpi.numberOfPossessedShares(5525825ULL, SELF, SELF, SELF, SELF_INDEX, SELF_INDEX);
        state.mut().secondCount = qpi.numberOfPossessedShares(5525825ULL + 1, SELF, SELF, SELF, SELF_INDEX, SELF_INDEX);
        state.mut().thirdCount = qpi.numberOfPossessedShares(5525825ULL + 2, SELF, SELF, SELF, SELF_INDEX, SELF_INDEX);

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().firstCount = 0;
        state.mut().secondCount = 0;
        state.mut().thirdCount = 0;
        state.mut().issued = 0;
        state.mut().calls = 0;
    }
};
