// SharesIssueTwiceSameName — ported from openzeppelin-contracts/contracts/token/ERC20/ERC20.sol
// Stresses: a duplicate issuance and the code it returns
// Port caveat: no Solidity analogue for a name registry
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SharesIssueTwiceSameName2
{
};

struct SharesIssueTwiceSameName : public ContractBase
{
    struct Scratch
    {
        sint64 issueTwiceResult;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 attempts;
        sint64 possessedAfter;
        sint64 secondResult;
        sint64 firstResult;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct IssueTwice_input
    {
        uint64 name;
        sint64 shares;
    };

    struct IssueTwice_output {};

    struct IssueTwice_locals
    {
        IssueTwice_input forwardedInput;
        IssueTwice_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(IssueTwice)
    {
        locals.forwardedInput = input;
        CALL(IssueTwiceBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        sint64 firstResult;
        sint64 secondResult;
        sint64 possessedAfter;
        uint64 attempts;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using IssueTwiceBody_input = IssueTwice_input;

    using IssueTwiceBody_output = IssueTwice_output;

    PRIVATE_PROCEDURE(IssueTwiceBody)
    {
        state.mut().inner.scratch.issueTwiceResult = qpi.issueAsset(input.name, SELF, 0, input.shares, 0);
        if (state.get().inner.attempts == 0)
        {
        state.mut().inner.firstResult = state.mut().inner.scratch.issueTwiceResult;
        }
        else
        {
        state.mut().inner.secondResult = state.mut().inner.scratch.issueTwiceResult;
        }
        state.mut().inner.attempts++;
        state.mut().inner.possessedAfter = qpi.numberOfPossessedShares(input.name, SELF, SELF, SELF, SELF_INDEX, SELF_INDEX);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.firstResult = state.get().inner.firstResult;
        output.secondResult = state.get().inner.secondResult;
        output.possessedAfter = state.get().inner.possessedAfter;
        output.attempts = state.get().inner.attempts;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(IssueTwice, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.firstResult = 0;
        state.mut().inner.secondResult = 0;
        state.mut().inner.possessedAfter = 0;
        state.mut().inner.attempts = 0;
    }
};
