// SharesIssueEdgeCounts — ported from openzeppelin-contracts/contracts/token/ERC20/ERC20.sol (_mint)
// Stresses: issuance at zero, one, the maximum and a negative count — four share counts the host validates differently, with the returned code stored each time
// Port caveat: Solidity's _mint takes an unsigned amount; QPI's issueAsset takes a signed one, so the negative half of the range exists only in the port.
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=absent placement=last stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SharesIssueEdgeCounts2
{
};

struct SharesIssueEdgeCounts : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        uint64 calls;
        uint64 refused;
        uint64 accepted;
        sint64 possessed;
        sint64 result;
    };

    struct Read_input {};

    struct Read_output
    {
        sint64 result;
        sint64 possessed;
        uint64 accepted;
        uint64 refused;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.result = state.get().result;
        output.possessed = state.get().possessed;
        output.accepted = state.get().accepted;
        output.refused = state.get().refused;
        output.calls = state.get().calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    struct RunBody_locals
    {
        sint64 outcome;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RunBody)
    {
        locals.outcome = qpi.issueAsset(5525825ULL, SELF, 0, (sint64)input.a, 0);
        state.mut().result = locals.outcome;
        if (locals.outcome > 0)
        {
        state.mut().accepted++;
        }
        else
        {
        state.mut().refused++;
        }
        state.mut().possessed = qpi.numberOfPossessedShares(5525825ULL, SELF, SELF, SELF, SELF_INDEX, SELF_INDEX);

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }
};
