// SharesIssueAndCount — ported from openzeppelin-contracts/contracts/token/ERC20/ERC20.sol
// Stresses: issueAsset and numberOfPossessedShares, mirrored into state
// Port caveat: the asset universe is host state; only the mirror is in the digest
// Variant: entryOrder=reversed entryShape=direct initStyle=empty placement=nested stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SharesIssueAndCount2
{
};

struct SharesIssueAndCount : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        sint64 issueResult;
        sint64 possessed;
        sint64 issuedFlag;
        uint64 calls;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        sint64 issueResult;
        sint64 possessed;
        sint64 issuedFlag;
        uint64 calls;
    };

    struct Read_locals
    {
        sint64 shares;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        locals.shares = qpi.numberOfPossessedShares(5521745ULL, SELF, SELF, SELF, SELF_INDEX, SELF_INDEX);
        output.issueResult = state.get().inner.issueResult;
        output.possessed = locals.shares;
        output.issuedFlag = qpi.isAssetIssued(SELF, 5521745ULL) ? 1 : 0;
        output.calls = state.get().inner.calls;
    }

    struct Mirror_input {};

    struct Mirror_output {};

    struct Mirror_locals
    {
        sint64 shares;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Mirror)
    {
        locals.shares = qpi.numberOfPossessedShares(5521745ULL, SELF, SELF, SELF, SELF_INDEX, SELF_INDEX);
        state.mut().inner.possessed = locals.shares;
        state.mut().inner.issuedFlag = qpi.isAssetIssued(SELF, 5521745ULL) ? 1 : 0;
    }

    struct Issue_input
    {
        uint64 name;
        sint64 shares;
    };

    struct Issue_output {};

    struct Issue_locals
    {
        sint64 result;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Issue)
    {
        locals.result = qpi.issueAsset(input.name, SELF, 0, input.shares, 0);
        state.mut().inner.issueResult = locals.result;
        state.mut().inner.calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Issue, 1);
        REGISTER_USER_PROCEDURE(Mirror, 2);
    }

    INITIALIZE()
    {

    }
};
