// VestingLinearRelease — ported from openzeppelin-contracts/contracts/finance/VestingWallet.sol
// Stresses: multiply-then-divide vesting with a monotonic release invariant
// Port caveat: timestamps become ticks; uint256 becomes uint64
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=absent placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct VestingLinearRelease2
{
};

struct VestingLinearRelease : public ContractBase
{
    struct Scratch
    {
        uint64 releaseNow;
        uint64 releaseElapsed;
        uint64 releaseVested;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 nonMonotonic;
        uint64 lastVested;
        uint64 released;
        uint64 duration;
        uint64 start;
        uint64 total;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Release_input {};

    struct Release_output
    {
        uint64 amount;
    };

    struct Release_locals
    {
        Release_input forwardedInput;
        Release_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Release)
    {
        CALL(ReleaseBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 released;
        uint64 lastVested;
        uint64 nonMonotonic;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using ReleaseBody_input = Release_input;

    using ReleaseBody_output = Release_output;

    PRIVATE_PROCEDURE(ReleaseBody)
    {
        state.mut().inner.scratch.releaseNow = (uint64)qpi.tick();
        if (state.mut().inner.scratch.releaseNow <= state.get().inner.start)
        {
        output.amount = 0;
        return;
        }
        state.mut().inner.scratch.releaseElapsed = state.mut().inner.scratch.releaseNow - state.get().inner.start;
        if (state.mut().inner.scratch.releaseElapsed >= state.get().inner.duration)
        {
        state.mut().inner.scratch.releaseVested = state.get().inner.total;
        }
        else
        {
        state.mut().inner.scratch.releaseVested = QPI::div(state.get().inner.total * state.mut().inner.scratch.releaseElapsed, state.get().inner.duration);
        }
        if (state.mut().inner.scratch.releaseVested < state.get().inner.lastVested)
        {
        state.mut().inner.nonMonotonic++;
        }
        state.mut().inner.lastVested = state.mut().inner.scratch.releaseVested;
        if (state.mut().inner.scratch.releaseVested <= state.get().inner.released)
        {
        output.amount = 0;
        return;
        }
        output.amount = state.mut().inner.scratch.releaseVested - state.get().inner.released;
        state.mut().inner.released = state.mut().inner.scratch.releaseVested;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.released = state.get().inner.released;
        output.lastVested = state.get().inner.lastVested;
        output.nonMonotonic = state.get().inner.nonMonotonic;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Release, 1);
    }
};
