// EnumMembersInStruct — ported from enums/enum_explicit_overflow.sol
// Stresses: underlying width of three differently ranged enums
// Port caveat: Solidity enums are one byte; C++ chooses
// Variant: entryOrder=reversed entryShape=direct initStyle=absent layout=declared placement=first stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

enum Tiny { A = 0, B = 1 };

enum Medium { C = 0, D = 300 };

enum Large { E = 0, F = 70000 };

struct Mixed
{
    Tiny tiny;
    Medium medium;
    Large large;
    uint8 tail;
};

struct EnumMembersInStruct2
{
};

struct EnumMembersInStruct : public ContractBase
{
    struct StateData
    {
        Mixed mixed;
        uint64 mixedSize;
        uint64 tinySize;
        uint64 mediumSize;
        uint64 largeSize;
        uint64 writes;
        uint64 placementGuard;
    };

    struct Write_input
    {
        uint64 value;
    };

    struct Write_output {};

    struct Write_locals
    {
        uint64 scratch;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Write)
    {
        locals.scratch = input.value;
        state.mut().mixed.tiny = locals.scratch > 0 ? B : A;
        state.mut().mixed.medium = locals.scratch > 1 ? D : C;
        state.mut().mixed.large = locals.scratch > 2 ? F : E;
        state.mut().mixed.tail = (uint8)locals.scratch;
        state.mut().mixedSize = sizeof(Mixed);
        state.mut().tinySize = sizeof(Tiny);
        state.mut().mediumSize = sizeof(Medium);
        state.mut().largeSize = sizeof(Large);
        state.mut().writes++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 mixedSize;
        uint64 tinySize;
        uint64 mediumSize;
        uint64 largeSize;
        uint64 tinyValue;
        uint64 largeValue;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.mixedSize = state.get().mixedSize;
        output.tinySize = state.get().tinySize;
        output.mediumSize = state.get().mediumSize;
        output.largeSize = state.get().largeSize;
        output.tinyValue = (uint64)state.get().mixed.tiny;
        output.largeValue = (uint64)state.get().mixed.large;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Write, 1);
    }
};
