// EnumUnderlyingWidth — ported from test/libsolidity/semanticTests/enums/enum_with_underlying_type.sol
// Stresses: explicit, implicit and aliased enum underlying types side by side
// Variant: entryOrder=declared entryShape=direct initStyle=absent placement=nested stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

enum Implicit { A = 0, B = 1, C = 2 };
enum Explicit : uint8 { D = 0, E = 1, F = 2 };
enum Wide : uint64 { G = 0, H = 1, I = 2 };
using AliasedWide = Wide;

struct EnumUnderlyingWidth2
{
};

struct EnumUnderlyingWidth : public ContractBase
{
    struct Scratch
    {
        uint64 setSlot;
    };

    struct StateData
    {
        struct Inner
        {
        Implicit implicitValue;
        Explicit explicitValue;
        AliasedWide aliasedValue;
        uint64 implicitSize;
        uint64 explicitSize;
        uint64 aliasedSize;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 implicitSize;
        uint64 explicitSize;
        uint64 aliasedSize;
        uint64 observed;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.implicitSize = state.get().inner.implicitSize;
        output.explicitSize = state.get().inner.explicitSize;
        output.aliasedSize = state.get().inner.aliasedSize;
        output.observed = (uint64)state.get().inner.aliasedValue;
    }

    struct Set_input
    {
        uint64 value;
    };

    struct Set_output {};

    PUBLIC_PROCEDURE(Set)
    {
        state.mut().inner.scratch.setSlot = QPI::mod(input.value, 3ULL);
        state.mut().inner.implicitValue = (Implicit)state.mut().inner.scratch.setSlot;
        state.mut().inner.explicitValue = (Explicit)state.mut().inner.scratch.setSlot;
        state.mut().inner.aliasedValue = (AliasedWide)state.mut().inner.scratch.setSlot;
        state.mut().inner.implicitSize = sizeof(Implicit);
        state.mut().inner.explicitSize = sizeof(Explicit);
        state.mut().inner.aliasedSize = sizeof(AliasedWide);
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Set, 1);
    }
};
