// IdFieldAlignmentProbe — ported from getters/value_types.sol
// Stresses: id alignment between narrow neighbours
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=absent layout=declared placement=last stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct Holder
{
    uint8 before;
    id middle;
    uint16 after;
};

struct IdFieldAlignmentProbe2
{
};

struct IdFieldAlignmentProbe : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        uint64 sameAsSelf;
        uint64 holderSize;
        Holder holder;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 before;
        uint64 after;
        uint64 holderSize;
        uint64 sameAsSelf;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Write_input
    {
        uint64 seed;
    };

    struct Write_output {};

    struct Write_locals
    {
        Write_input forwardedInput;
        Write_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Write)
    {
        locals.forwardedInput = input;
        CALL(WriteBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.before = (uint64)state.get().holder.before;
        output.after = (uint64)state.get().holder.after;
        output.holderSize = state.get().holderSize;
        output.sameAsSelf = state.get().sameAsSelf;
    }

    using WriteBody_input = Write_input;

    using WriteBody_output = Write_output;

    struct WriteBody_locals
    {
        uint64 scratch;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(WriteBody)
    {
        state.mut().holder.before = (uint8)input.seed;
        state.mut().holder.middle = qpi.invocator();
        state.mut().holder.after = (uint16)input.seed;
        state.mut().holderSize = sizeof(Holder);
        state.mut().sameAsSelf = (state.get().holder.middle == qpi.invocator()) ? 1 : 0;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Write, 1);
    }
};
