// IdFieldAlignmentProbe — ported from getters/value_types.sol
// Stresses: id alignment between narrow neighbours
// Variant: entryOrder=reversed entryShape=direct initStyle=empty layout=declared placement=first stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct Holder
{
    uint8 before;
    id middle;
    uint16 after;
};

struct IdFieldAlignmentProbe2
{
};

struct IdFieldAlignmentProbe : public ContractBase
{
    struct Scratch
    {
        uint64 writeScratch;
    };

    struct StateData
    {
        uint64 sameAsSelf;
        uint64 holderSize;
        Holder holder;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Write_input
    {
        uint64 seed;
    };

    struct Write_output {};

    PUBLIC_PROCEDURE(Write)
    {
        state.mut().holder.before = (uint8)input.seed;
        state.mut().holder.middle = qpi.invocator();
        state.mut().holder.after = (uint16)input.seed;
        state.mut().holderSize = sizeof(Holder);
        state.mut().sameAsSelf = (state.get().holder.middle == qpi.invocator()) ? 1 : 0;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 before;
        uint64 after;
        uint64 holderSize;
        uint64 sameAsSelf;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.before = (uint64)state.get().holder.before;
        output.after = (uint64)state.get().holder.after;
        output.holderSize = state.get().holderSize;
        output.sameAsSelf = state.get().sameAsSelf;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Write, 1);
    }

    INITIALIZE()
    {

    }
};
