// IdFieldAlignmentProbe — ported from getters/value_types.sol
// Stresses: id alignment between narrow neighbours
// Variant: layout=widestFirst initStyle=full
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct Holder
{
    id middle;
    uint16 after;
    uint8 before;
};

struct IdFieldAlignmentProbe2
{
};

struct IdFieldAlignmentProbe : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        Holder holder;
        uint64 holderSize;
        uint64 sameAsSelf;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 before;
        uint64 after;
        uint64 holderSize;
        uint64 sameAsSelf;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.before = (uint64)state.get().inner.holder.before;
        output.after = (uint64)state.get().inner.holder.after;
        output.holderSize = state.get().inner.holderSize;
        output.sameAsSelf = state.get().inner.sameAsSelf;
    }

    struct Write_input
    {
        uint64 seed;
    };

    struct Write_output {};

    struct Write_locals
    {
        uint64 scratch;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Write)
    {
        state.mut().inner.holder.before = (uint8)input.seed;
        state.mut().inner.holder.middle = qpi.invocator();
        state.mut().inner.holder.after = (uint16)input.seed;
        state.mut().inner.holderSize = sizeof(Holder);
        state.mut().inner.sameAsSelf = (state.get().inner.holder.middle == qpi.invocator()) ? 1 : 0;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Write, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.holderSize = 0;
        state.mut().inner.sameAsSelf = 0;
    }
};
