// MixedWidthStructArrayStride — ported from storage/storage_boundary_struct_array_mixed_types.sol
// Stresses: stride of an array of wide mixed-width structs
// Variant: capacity=1024 entryOrder=reversed entryShape=direct initStyle=empty layout=padded placement=nested stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct Element
{
    id owner;
    uint8 hole;
    uint128 huge;
    uint64 wide;
    uint32 medium;
    bit flag;
};

struct MixedWidthStructArrayStride2
{
};

struct MixedWidthStructArrayStride : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        Array<Element, 4> elements;
        Array<uint64, 4> neighbours;
        uint64 elementSize;
        uint64 checksum;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 elementSize;
        uint64 checksum;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.elementSize = state.get().inner.elementSize;
        output.checksum = state.get().inner.checksum;
    }

    struct Fill_input
    {
        uint64 count;
    };

    struct Fill_output {};

    struct Fill_locals
    {
        uint64 i;
        uint64 bound;
        Element scratch;
        uint64 total;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Fill)
    {
        locals.bound = input.count;
        if (locals.bound > 4)
        {
        locals.bound = 4;
        }
        for (locals.i = 0; locals.i < 4; locals.i++)
        {
        state.mut().inner.neighbours.set(locals.i, 0x7777777777777777ULL);
        }
        for (locals.i = 0; locals.i < locals.bound; locals.i++)
        {
        locals.scratch.owner = qpi.invocator();
        locals.scratch.huge = (uint128)(locals.i + 1);
        locals.scratch.wide = locals.i + 2;
        locals.scratch.medium = (uint32)(locals.i + 3);
        locals.scratch.flag = 1;
        state.mut().inner.elements.set(locals.i, locals.scratch);
        }
        locals.total = 0;
        for (locals.i = 0; locals.i < 4; locals.i++)
        {
        locals.total += state.get().inner.elements.get(locals.i).wide;
        locals.total += (uint64)state.get().inner.elements.get(locals.i).medium;
        locals.total += state.get().inner.neighbours.get(locals.i);
        }
        state.mut().inner.checksum = locals.total;
        state.mut().inner.elementSize = sizeof(Element);
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Fill, 1);
    }

    INITIALIZE()
    {

    }
};
