// PackWithIdField — ported from test/libsolidity/semanticTests/types/address_types.sol
// Stresses: a 32-byte id among narrow fields — the alignment case where reordering changes size the most
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=empty layout=padded placement=last stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct Packed
{
    id owner;
    uint8 hole;
    uint64 wide;
    uint8 tiny;
};

struct PackWithIdField2
{
};

struct PackWithIdField : public ContractBase
{
    struct Scratch
    {
        uint64 writeScratch;
    };

    struct StateData
    {
        uint64 placementGuard;
        Packed packed;
        uint64 packedSize;
        uint64 stateSize;
        Scratch scratch;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 packedSize;
        uint64 stateSize;
        uint64 probe;
        uint64 guard;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Write_input
    {
        uint64 value;
    };

    struct Write_output {};

    struct Write_locals
    {
        Write_input forwardedInput;
        Write_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Write)
    {
        locals.forwardedInput = input;
        CALL(WriteBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.packedSize = state.get().packedSize;
        output.stateSize = state.get().stateSize;
        output.probe = (uint64)state.get().packed.wide;
        output.guard = state.get().placementGuard;
    }

    using WriteBody_input = Write_input;

    using WriteBody_output = Write_output;

    PRIVATE_PROCEDURE(WriteBody)
    {
        state.mut().packed.wide = input.value;
        state.mut().packedSize = sizeof(Packed);
        state.mut().stateSize = sizeof(StateData);
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Write, 1);
    }

    INITIALIZE()
    {

    }
};
