// PackedUint128PairSum — ported from OpenZeppelin DoubleEndedQueue begin/end
// Stresses: adjacent uint128 fields
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=empty layout=widestFirst placement=first stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct Cursor
{
    uint128 begin;
    uint128 end;
};

struct PackedUint128PairSum2
{
};

struct PackedUint128PairSum : public ContractBase
{
    struct StateData
    {
        Cursor cursor;
        uint128 span;
        uint64 cursorSize;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint128 span;
        uint64 cursorSize;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Advance_input
    {
        uint128 beginDelta;
        uint128 endDelta;
    };

    struct Advance_output {};

    struct Advance_locals
    {
        Advance_input forwardedInput;
        Advance_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Advance)
    {
        locals.forwardedInput = input;
        CALL(AdvanceBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.span = state.get().span;
        output.cursorSize = state.get().cursorSize;
    }

    using AdvanceBody_input = Advance_input;

    using AdvanceBody_output = Advance_output;

    struct AdvanceBody_locals
    {
        uint128 scratch;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(AdvanceBody)
    {
        state.mut().cursor.begin += input.beginDelta;
        state.mut().cursor.end += input.endDelta;
        locals.scratch = state.get().cursor.end - state.get().cursor.begin;
        state.mut().span = locals.scratch;
        state.mut().cursorSize = sizeof(Cursor);
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Advance, 1);
    }

    INITIALIZE()
    {

    }
};
