// PackWithBitField — ported from test/libsolidity/semanticTests/storage/packed_storage_structs_bytes.sol
// Stresses: QPI's `bit` (a char wrapper, not a bool) adjacent to wide fields
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=absent layout=padded placement=nested stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct Packed
{
    uint64 wide;
    uint8 hole;
    uint32 medium;
    bit flag;
};

struct PackWithBitField2
{
};

struct PackWithBitField : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        Packed packed;
        uint64 packedSize;
        uint64 stateSize;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Write_input
    {
        uint64 value;
    };

    struct Write_output {};

    struct Write_locals
    {
        Write_input forwardedInput;
        Write_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Write)
    {
        locals.forwardedInput = input;
        CALL(WriteBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 packedSize;
        uint64 stateSize;
        uint64 probe;
        uint64 guard;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using WriteBody_input = Write_input;

    using WriteBody_output = Write_output;

    struct WriteBody_locals
    {
        uint64 scratch;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(WriteBody)
    {
        state.mut().inner.packed.wide = input.value;
        state.mut().inner.packedSize = sizeof(Packed);
        state.mut().inner.stateSize = sizeof(StateData);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.packedSize = state.get().inner.packedSize;
        output.stateSize = state.get().inner.stateSize;
        output.probe = (uint64)state.get().inner.packed.wide;
        output.guard = state.get().placementGuard;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Write, 1);
    }
};
