// PackedNeighbourOverflowCanary — ported from test/libsolidity/semanticTests/storage/packed_storage_overflow.sol
// Stresses: wraparound confined to its own field
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=full layout=padded placement=last stateOrder=declared temporaries=locals width=sint64
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct PackedNeighbourOverflowCanary2
{
};

struct PackedNeighbourOverflowCanary : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        sint64 x;
        sint64 a;
        sint64 b;
        uint64 captured;
    };

    struct Wrap_input
    {
        uint64 seed;
    };

    struct Wrap_output {};

    struct Wrap_locals
    {
        Wrap_input forwardedInput;
        Wrap_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Wrap)
    {
        locals.forwardedInput = input;
        CALL(WrapBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        sint64 x;
        sint64 a;
        sint64 b;
        uint64 captured;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using WrapBody_input = Wrap_input;

    using WrapBody_output = Wrap_output;

    struct WrapBody_locals
    {
        uint64 scratch;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(WrapBody)
    {
        state.mut().x = (sint64)0x1234;
        state.mut().a = (sint64)input.seed;
        state.mut().b = 0;
        state.mut().a++;
        locals.scratch = (uint64)state.get().b;
        state.mut().b = 0;
        state.mut().a -= 2;
        state.mut().captured = locals.scratch;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.x = state.get().x;
        output.a = state.get().a;
        output.b = state.get().b;
        output.captured = state.get().captured;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Wrap, 1);
    }

    INITIALIZE()
    {
        state.mut().x = 0;
        state.mut().a = 0;
        state.mut().b = 0;
        state.mut().captured = 0;
    }
};
