// PackedNeighbourOverflowCanary — ported from test/libsolidity/semanticTests/storage/packed_storage_overflow.sol
// Stresses: wraparound confined to its own field
// Variant: entryOrder=declared entryShape=direct initStyle=full layout=declared placement=first stateOrder=reversed temporaries=stateScratch width=sint64
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct PackedNeighbourOverflowCanary2
{
};

struct PackedNeighbourOverflowCanary : public ContractBase
{
    struct Scratch
    {
        uint64 wrapScratch;
    };

    struct StateData
    {
        uint64 captured;
        sint64 b;
        sint64 a;
        sint64 x;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        sint64 x;
        sint64 a;
        sint64 b;
        uint64 captured;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.x = state.get().x;
        output.a = state.get().a;
        output.b = state.get().b;
        output.captured = state.get().captured;
    }

    struct Wrap_input
    {
        uint64 seed;
    };

    struct Wrap_output {};

    PUBLIC_PROCEDURE(Wrap)
    {
        state.mut().x = (sint64)0x1234;
        state.mut().a = (sint64)input.seed;
        state.mut().b = 0;
        state.mut().a++;
        state.mut().scratch.wrapScratch = (uint64)state.get().b;
        state.mut().b = 0;
        state.mut().a -= 2;
        state.mut().captured = state.mut().scratch.wrapScratch;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Wrap, 1);
    }

    INITIALIZE()
    {
        state.mut().x = 0;
        state.mut().a = 0;
        state.mut().b = 0;
        state.mut().captured = 0;
    }
};
