// PackingTwentyFourEight — ported from structs/struct_packing.sol
// Stresses: id + uint32 + uint64 in one struct, with a canary either side
// Port caveat: C++ alignment, not Solidity slot packing
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=empty layout=widestLast placement=nested stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct Record
{
    id who;
    uint32 small;
    uint64 large;
};

struct Reordered
{
    uint32 small;
    uint64 large;
    id who;
};

struct PackingTwentyFourEight2
{
};

struct PackingTwentyFourEight : public ContractBase
{
    struct Scratch
    {
        uint64 writeScratch;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 canaryBefore;
        Record straight;
        Reordered reordered;
        uint64 canaryAfter;
        uint64 sizesAgree;
        uint64 writes;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint32 straightSmall;
        uint64 straightLarge;
        uint32 reorderedSmall;
        uint64 reorderedLarge;
        uint64 canaryBefore;
        uint64 canaryAfter;
        uint64 sizesAgree;
        uint64 recordSize;
        uint64 reorderedSize;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Write_input
    {
        uint32 small;
        uint64 large;
    };

    struct Write_output {};

    struct Write_locals
    {
        Write_input forwardedInput;
        Write_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Write)
    {
        locals.forwardedInput = input;
        CALL(WriteBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.straightSmall = state.get().inner.straight.small;
        output.straightLarge = state.get().inner.straight.large;
        output.reorderedSmall = state.get().inner.reordered.small;
        output.reorderedLarge = state.get().inner.reordered.large;
        output.canaryBefore = state.get().inner.canaryBefore;
        output.canaryAfter = state.get().inner.canaryAfter;
        output.sizesAgree = state.get().inner.sizesAgree;
        output.recordSize = sizeof(Record);
        output.reorderedSize = sizeof(Reordered);
    }

    using WriteBody_input = Write_input;

    using WriteBody_output = Write_output;

    PRIVATE_PROCEDURE(WriteBody)
    {
        state.mut().inner.straight.who = qpi.invocator();
        state.mut().inner.straight.small = input.small;
        state.mut().inner.straight.large = input.large;
        state.mut().inner.reordered.who = qpi.invocator();
        state.mut().inner.reordered.small = input.small;
        state.mut().inner.reordered.large = input.large;
        state.mut().inner.scratch.writeScratch = sizeof(Record) == sizeof(Reordered) ? 1 : 0;
        state.mut().inner.sizesAgree = state.mut().inner.scratch.writeScratch;
        state.mut().inner.writes++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Write, 1);
    }

    INITIALIZE()
    {

    }
};
