// SizeofNestedArrayGrid — ported from test/libsolidity/semanticTests/array/multidim_array.sol
// Stresses: sizeof of Array, Array of Array and Array of Array of Array — the product rule, checked at three depths and two element widths
// Variant: entryOrder=reversed entryShape=direct initStyle=absent layout=widestLast placement=first stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

using Flat = Array<uint64, 8>;
using Nested = Array<Flat, 4>;
using Cube = Array<Nested, 2>;
using NarrowFlat = Array<uint16, 8>;
using NarrowNested = Array<NarrowFlat, 4>;
using NarrowCube = Array<NarrowNested, 2>;

struct SizeofNestedArrayGrid2
{
};

struct SizeofNestedArrayGrid : public ContractBase
{
    struct StateData
    {
        uint64 narrowCube;
        uint64 narrowFlat;
        uint64 cube;
        uint64 nested;
        uint64 flat;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 flat;
        uint64 nested;
        uint64 cube;
        uint64 narrowFlat;
        uint64 narrowCube;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.flat = state.get().flat;
        output.nested = state.get().nested;
        output.cube = state.get().cube;
        output.narrowFlat = state.get().narrowFlat;
        output.narrowCube = state.get().narrowCube;
    }

    struct Measure_input
    {
        uint64 seed;
    };

    struct Measure_output {};

    struct Measure_locals
    {
        uint64 scratch;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Measure)
    {
        state.mut().flat = sizeof(Flat);
        state.mut().nested = sizeof(Nested);
        state.mut().cube = sizeof(Cube);
        state.mut().narrowFlat = sizeof(NarrowFlat);
        state.mut().narrowCube = sizeof(NarrowCube);
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Measure, 1);
    }
};
