// SpacerFieldsThenArrayClear — ported from array/fixed_array_cleanup.sol
// Stresses: bounded clear between two spacers
// Variant: capacity=64 entryOrder=reversed entryShape=viaPrivate initStyle=absent loopShape=zero placement=nested stateOrder=declared temporaries=stateScratch width=uint8
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SpacerFieldsThenArrayClear2
{
};

struct SpacerFieldsThenArrayClear : public ContractBase
{
    struct Scratch
    {
        uint64 fillThenClearI;
        uint64 fillThenClearTotal;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 spacerBefore;
        Array<uint8, 64> data;
        uint64 spacerAfter;
        uint64 checksum;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 spacerBefore;
        uint64 spacerAfter;
        uint64 checksum;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct FillThenClear_input
    {
        uint64 value;
        uint64 clear;
    };

    struct FillThenClear_output {};

    struct FillThenClear_locals
    {
        FillThenClear_input forwardedInput;
        FillThenClear_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(FillThenClear)
    {
        locals.forwardedInput = input;
        CALL(FillThenClearBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.spacerBefore = state.get().inner.spacerBefore;
        output.spacerAfter = state.get().inner.spacerAfter;
        output.checksum = state.get().inner.checksum;
    }

    using FillThenClearBody_input = FillThenClear_input;

    using FillThenClearBody_output = FillThenClear_output;

    PRIVATE_PROCEDURE(FillThenClearBody)
    {
        state.mut().inner.spacerBefore = 0x3333333333333333ULL;
        state.mut().inner.spacerAfter = 0x4444444444444444ULL;
        for (state.mut().inner.scratch.fillThenClearI = 0; state.mut().inner.scratch.fillThenClearI < 64; state.mut().inner.scratch.fillThenClearI++)
        {
        state.mut().inner.data.set(state.mut().inner.scratch.fillThenClearI, (uint8)(input.value + state.mut().inner.scratch.fillThenClearI));
        }
        if (input.clear != 0)
        {
        for (state.mut().inner.scratch.fillThenClearI = 0; state.mut().inner.scratch.fillThenClearI < 64; state.mut().inner.scratch.fillThenClearI++)
        {
        state.mut().inner.data.set(state.mut().inner.scratch.fillThenClearI, 0);
        }
        }
        state.mut().inner.scratch.fillThenClearTotal = 0;
        for (state.mut().inner.scratch.fillThenClearI = 0; state.mut().inner.scratch.fillThenClearI < 64; state.mut().inner.scratch.fillThenClearI++)
        {
        state.mut().inner.scratch.fillThenClearTotal += (uint64)state.get().inner.data.get(state.mut().inner.scratch.fillThenClearI);
        }
        state.mut().inner.checksum = state.mut().inner.scratch.fillThenClearTotal;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(FillThenClear, 1);
    }
};
