// SpacerFieldsThenArrayClear — ported from array/fixed_array_cleanup.sol
// Stresses: bounded clear between two spacers
// Variant: capacity=8 entryOrder=declared entryShape=direct initStyle=full loopShape=constant placement=nested stateOrder=reversed temporaries=locals width=uint16
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SpacerFieldsThenArrayClear2
{
};

struct SpacerFieldsThenArrayClear : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 checksum;
        uint64 spacerAfter;
        Array<uint16, 8> data;
        uint64 spacerBefore;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct FillThenClear_input
    {
        uint64 value;
        uint64 clear;
    };

    struct FillThenClear_output {};

    struct FillThenClear_locals
    {
        uint64 i;
        uint64 total;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(FillThenClear)
    {
        state.mut().inner.spacerBefore = 0x3333333333333333ULL;
        state.mut().inner.spacerAfter = 0x4444444444444444ULL;
        for (locals.i = 0; locals.i < 8; locals.i++)
        {
        state.mut().inner.data.set(locals.i, (uint16)(input.value + locals.i));
        }
        if (input.clear != 0)
        {
        for (locals.i = 0; locals.i < 8; locals.i++)
        {
        state.mut().inner.data.set(locals.i, 0);
        }
        }
        locals.total = 0;
        for (locals.i = 0; locals.i < 8; locals.i++)
        {
        locals.total += (uint64)state.get().inner.data.get(locals.i);
        }
        state.mut().inner.checksum = locals.total;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 spacerBefore;
        uint64 spacerAfter;
        uint64 checksum;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.spacerBefore = state.get().inner.spacerBefore;
        output.spacerAfter = state.get().inner.spacerAfter;
        output.checksum = state.get().inner.checksum;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(FillThenClear, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.data.setAll(0);
        state.mut().inner.spacerBefore = 0;
        state.mut().inner.spacerAfter = 0;
        state.mut().inner.checksum = 0;
    }
};
