// StructWithTrailingBitArray — ported from structs/struct_packing.sol
// Stresses: element stride over a struct ending in a BitArray
// Port caveat: packed bools become a BitArray
// Variant: capacity=64 entryOrder=reversed entryShape=viaPrivate initStyle=absent layout=padded placement=last stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct Entry
{
    uint64 amount;
    uint16 tag;
    BitArray<64> flags;
    uint8 kind;
};

struct StructWithTrailingBitArray2
{
};

struct StructWithTrailingBitArray : public ContractBase
{
    struct Scratch
    {
        Entry writeEntry;
    };

    struct StateData
    {
        uint64 placementGuard;
        Array<Entry, 8> entries;
        uint64 canary;
        uint64 writes;
        Scratch scratch;
    };

    struct Write_input
    {
        uint64 index;
        uint64 amount;
        uint64 bit;
    };

    struct Write_output {};

    struct Write_locals
    {
        Write_input forwardedInput;
        Write_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Write)
    {
        locals.forwardedInput = input;
        CALL(WriteBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input
    {
        uint64 index;
    };

    struct Read_output
    {
        uint64 amount;
        uint16 tag;
        uint8 kind;
        uint64 bitZero;
        uint64 bit63;
        uint64 neighbourAmount;
        uint64 canary;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        locals.forwardedInput = input;
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using WriteBody_input = Write_input;

    using WriteBody_output = Write_output;

    PRIVATE_PROCEDURE(WriteBody)
    {
        state.mut().scratch.writeEntry = state.get().entries.get(input.index);
        state.mut().scratch.writeEntry.amount = input.amount;
        state.mut().scratch.writeEntry.tag = (uint16)input.bit;
        state.mut().scratch.writeEntry.kind = (uint8)QPI::mod(input.amount, 251ULL);
        state.mut().scratch.writeEntry.flags.set(input.bit, 1);
        state.mut().entries.set(input.index, state.mut().scratch.writeEntry);
        state.mut().writes++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.amount = state.get().entries.get(input.index).amount;
        output.tag = state.get().entries.get(input.index).tag;
        output.kind = state.get().entries.get(input.index).kind;
        output.bitZero = state.get().entries.get(input.index).flags.get(0);
        output.bit63 = state.get().entries.get(input.index).flags.get(63);
        output.neighbourAmount = state.get().entries.get(input.index + 1).amount;
        output.canary = state.get().canary;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Write, 1);
    }
};
