// Uint128ArrayStride — ported from test/libsolidity/semanticTests/structs/struct_packing.sol
// Stresses: an Array of uint128 written at both ends, with the neighbour read back — the widest scalar element stride QPI has
// Variant: entryOrder=reversed entryShape=direct initStyle=absent layout=padded placement=nested stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

using WideArray = Array<uint128, 4>;

struct Uint128ArrayStride2
{
};

struct Uint128ArrayStride : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 canary;
        uint64 lastLow;
        uint64 firstLow;
        uint64 elementSize;
        uint64 arraySize;
        Array<uint128, 4> wide;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 arraySize;
        uint64 elementSize;
        uint64 firstLow;
        uint64 lastLow;
        uint64 canary;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.arraySize = state.get().inner.arraySize;
        output.elementSize = state.get().inner.elementSize;
        output.firstLow = state.get().inner.firstLow;
        output.lastLow = state.get().inner.lastLow;
        output.canary = state.get().inner.canary;
    }

    struct Measure_input
    {
        uint64 seed;
    };

    struct Measure_output {};

    struct Measure_locals
    {
        uint128 value;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Measure)
    {
        locals.value = (uint128)input.seed;
        locals.value = locals.value * (uint128)18446744073709551615ULL;
        state.mut().inner.wide.set(0, locals.value);
        state.mut().inner.wide.set(3, locals.value + (uint128)1);
        state.mut().inner.arraySize = sizeof(WideArray);
        state.mut().inner.elementSize = sizeof(uint128);
        state.mut().inner.firstLow = (uint64)state.get().inner.wide.get(0);
        state.mut().inner.lastLow = (uint64)state.get().inner.wide.get(3);
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Measure, 1);
    }
};
