import { INPUT_BUFFER_BYTES, LOCALS_BUFFER_BYTES } from "@qinit/core/wasm/sizing";

export const USER_FUNCTION_KIND = 0;
export const USER_PROCEDURE_KIND = 1;
export type UserEntryKind = typeof USER_FUNCTION_KIND | typeof USER_PROCEDURE_KIND;

export const MIN_USER_INPUT_TYPE = 1;
export const USER_ENTRY_IO_BUFFER_SIZE_BYTES = INPUT_BUFFER_BYTES;
export const USER_ENTRY_LOCALS_BUFFER_SIZE_BYTES = LOCALS_BUFFER_BYTES;
export const MAX_USER_INPUT_TYPE = USER_ENTRY_IO_BUFFER_SIZE_BYTES - 1;
export const MAX_PROCEDURE_INPUT_SIZE_BYTES = 1024;
export const MAX_ENTRY_OUTPUT_SIZE_BYTES = USER_ENTRY_IO_BUFFER_SIZE_BYTES - 1;
export const MAX_ENTRY_LOCALS_SIZE_BYTES = USER_ENTRY_LOCALS_BUFFER_SIZE_BYTES;
