export const SCALAR_SIZE: Record<string, number> = {
    bool: 1,
    bit: 1,
    sint8: 1,
    uint8: 1,
    "signed char": 1,
    "unsigned char": 1,
    sint16: 2,
    uint16: 2,
    "signed short": 2,
    "unsigned short": 2,
    sint32: 4,
    uint32: 4,
    "signed int": 4,
    "unsigned int": 4,
    sint64: 8,
    uint64: 8,
    "signed long long": 8,
    "unsigned long long": 8,
    "long long": 8,
    uint128: 16,
    id: 32,
    m256i: 32,
    __m256i: 32,
    auto: 8, // `auto` locals in qpi.h bodies are integer counters (pointer cases carry a trailing *)
    char: 1,
    // Native C spellings. Widths are the wasm32-wasi ones a contract actually builds against, which is
    // ILP32 — `long` is 4 bytes here, not the 8 an x86 habit would assume.
    short: 2,
    "short int": 2,
    "signed short int": 2,
    "unsigned short int": 2,
    int: 4,
    signed: 4,
    unsigned: 4,
    long: 4,
    "long int": 4,
    "signed long": 4,
    "signed long int": 4,
    "unsigned long": 4,
    "unsigned long int": 4,
    size_t: 4,
    wchar_t: 4,
};
