// HostEntityOfSelfAndCaller — ported from test/libsolidity/semanticTests/various/balance.sol
// Stresses: getEntity on SELF and on the caller in one procedure, with the two records' fields compared — the contract's own balance against the caller's
// Variant: base
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HostEntityOfSelfAndCaller2
{
};

struct HostEntityOfSelfAndCaller : public ContractBase
{
    struct StateData
    {
        sint64 selfIncoming;
        sint64 callerIncoming;
        uint64 bothFound;
        uint64 selfHasMore;
        uint64 calls;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        sint64 selfIncoming;
        sint64 callerIncoming;
        uint64 bothFound;
        uint64 selfHasMore;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.selfIncoming = state.get().selfIncoming;
        output.callerIncoming = state.get().callerIncoming;
        output.bothFound = state.get().bothFound;
        output.selfHasMore = state.get().selfHasMore;
        output.calls = state.get().calls;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Entity own;
        Entity caller;
        bit foundOwn;
        bit foundCaller;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.foundOwn = qpi.getEntity(SELF, locals.own);
        locals.foundCaller = qpi.getEntity(qpi.invocator(), locals.caller);
        state.mut().selfIncoming = locals.foundOwn ? locals.own.incomingAmount : -1;
        state.mut().callerIncoming = locals.foundCaller ? locals.caller.incomingAmount : -1;
        state.mut().bothFound = locals.foundOwn && locals.foundCaller ? 1 : 0;
        state.mut().selfHasMore = state.get().selfIncoming > state.get().callerIncoming ? 1 : 0;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().selfIncoming = 0;
        state.mut().callerIncoming = 0;
        state.mut().bothFound = 0;
        state.mut().selfHasMore = 0;
        state.mut().calls = 0;
    }
};
