// HostEntityOfSelfAndCaller — ported from test/libsolidity/semanticTests/various/balance.sol
// Stresses: getEntity on SELF and on the caller in one procedure, with the two records' fields compared — the contract's own balance against the caller's
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=empty placement=nested stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HostEntityOfSelfAndCaller2
{
};

struct HostEntityOfSelfAndCaller : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        sint64 selfIncoming;
        sint64 callerIncoming;
        uint64 bothFound;
        uint64 selfHasMore;
        uint64 calls;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        sint64 selfIncoming;
        sint64 callerIncoming;
        uint64 bothFound;
        uint64 selfHasMore;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    struct RunBody_locals
    {
        Entity own;
        Entity caller;
        bit foundOwn;
        bit foundCaller;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RunBody)
    {
        locals.foundOwn = qpi.getEntity(SELF, locals.own);
        locals.foundCaller = qpi.getEntity(qpi.invocator(), locals.caller);
        state.mut().inner.selfIncoming = locals.foundOwn ? locals.own.incomingAmount : -1;
        state.mut().inner.callerIncoming = locals.foundCaller ? locals.caller.incomingAmount : -1;
        state.mut().inner.bothFound = locals.foundOwn && locals.foundCaller ? 1 : 0;
        state.mut().inner.selfHasMore = state.get().inner.selfIncoming > state.get().inner.callerIncoming ? 1 : 0;

        state.mut().inner.calls++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.selfIncoming = state.get().inner.selfIncoming;
        output.callerIncoming = state.get().inner.callerIncoming;
        output.bothFound = state.get().inner.bothFound;
        output.selfHasMore = state.get().inner.selfHasMore;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
