// HostPreviousDigestsAreStable — ported from no Solidity analogue (blockhash)
// Stresses: the three previous-state digests — spectrum, universe and computer — read twice in one call and compared, which is the property a contract using them for randomness depends on
// Port caveat: Ethereum's nearest equivalent is `blockhash`, which is one value; QPI exposes three, and none of them is a hash of the block.
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=empty placement=first stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HostPreviousDigestsAreStable2
{
};

struct HostPreviousDigestsAreStable : public ContractBase
{
    struct StateData
    {
        uint64 spectrumWord;
        uint64 universeWord;
        uint64 computerWord;
        uint64 stableWithinCall;
        uint64 allDistinct;
        uint64 calls;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 spectrumWord;
        uint64 universeWord;
        uint64 computerWord;
        uint64 stableWithinCall;
        uint64 allDistinct;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.spectrumWord = state.get().spectrumWord;
        output.universeWord = state.get().universeWord;
        output.computerWord = state.get().computerWord;
        output.stableWithinCall = state.get().stableWithinCall;
        output.allDistinct = state.get().allDistinct;
        output.calls = state.get().calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    struct RunBody_locals
    {
        id spectrum;
        id universe;
        id computer;
        id again;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RunBody)
    {
        locals.spectrum = qpi.getPrevSpectrumDigest();
        locals.universe = qpi.getPrevUniverseDigest();
        locals.computer = qpi.getPrevComputerDigest();
        locals.again = qpi.getPrevSpectrumDigest();
        state.mut().spectrumWord = locals.spectrum.u64._0;
        state.mut().universeWord = locals.universe.u64._0;
        state.mut().computerWord = locals.computer.u64._0;
        state.mut().stableWithinCall = locals.spectrum == locals.again ? 1 : 0;
        state.mut().allDistinct = !(locals.spectrum == locals.universe) && !(locals.universe == locals.computer) ? 1 : 0;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
