// HostK12ExpressionVersusVariable — ported from openzeppelin-contracts/contracts/utils/cryptography/MerkleProof.sol
// Stresses: K12 of a computed expression next to K12 of a named local holding the same value — the exact pair F203 is about, kept as a live probe so a fix shows up here first
// Port caveat: This archetype is expected to diverge while F203 is open: the TypeScript backend hashes different bytes for the expression spelling. It is deliberately *not* pinned with expectedVerdict, because F203 is a defect to be fixed rather than an asymmetry to be documented — these rows should go green when it is.
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=empty placement=nested stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HostK12ExpressionVersusVariable2
{
};

struct HostK12ExpressionVersusVariable : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 calls;
        uint64 agree;
        uint64 fromVariable;
        uint64 fromExpression;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 fromExpression;
        uint64 fromVariable;
        uint64 agree;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    struct RunBody_locals
    {
        uint64 value;
        id fromExpr;
        id fromVar;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RunBody)
    {
        locals.value = input.a + input.b;
        locals.fromExpr = qpi.K12(input.a + input.b);
        locals.fromVar = qpi.K12(locals.value);
        state.mut().inner.fromExpression = locals.fromExpr.u64._0;
        state.mut().inner.fromVariable = locals.fromVar.u64._0;
        state.mut().inner.agree = locals.fromExpr == locals.fromVar ? 1 : 0;

        state.mut().inner.calls++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.fromExpression = state.get().inner.fromExpression;
        output.fromVariable = state.get().inner.fromVariable;
        output.agree = state.get().inner.agree;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
