// HostComputorIndexRange — ported from no Solidity analogue
// Stresses: computor(i) at 0, 1, 337 and 675
// Port caveat: out-of-range indices excluded — the simulator cannot pin them (F208)
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=absent loopShape=zero placement=first stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HostComputorIndexRange2
{
};

struct HostComputorIndexRange : public ContractBase
{
    struct Scratch
    {
        id probeFetched;
    };

    struct StateData
    {
        uint64 probes;
        id firstComputor;
        id lastComputor;
        uint64 nullResults;
        uint64 distinct;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 distinct;
        uint64 nullResults;
        uint64 probes;
        uint64 firstIsLast;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Probe_input
    {
        uint64 index;
    };

    struct Probe_output {};

    struct Probe_locals
    {
        Probe_input forwardedInput;
        Probe_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Probe)
    {
        locals.forwardedInput = input;
        CALL(ProbeBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.distinct = state.get().distinct;
        output.nullResults = state.get().nullResults;
        output.probes = state.get().probes;
        output.firstIsLast = state.get().firstComputor == state.get().lastComputor ? 1 : 0;
    }

    using ProbeBody_input = Probe_input;

    using ProbeBody_output = Probe_output;

    PRIVATE_PROCEDURE(ProbeBody)
    {
        state.mut().scratch.probeFetched = qpi.computor((uint16)input.index);
        if (state.mut().scratch.probeFetched == NULL_ID)
        {
        state.mut().nullResults++;
        }
        if (!(state.mut().scratch.probeFetched == state.get().lastComputor))
        {
        state.mut().distinct++;
        }
        if (state.get().probes == 0)
        {
        state.mut().firstComputor = state.mut().scratch.probeFetched;
        }
        state.mut().lastComputor = state.mut().scratch.probeFetched;
        state.mut().probes++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Probe, 1);
    }
};
