// HostSignatureValidity — ported from test/libsolidity/semanticTests/various/ecrecover.sol
// Stresses: a 64-byte signature argument and the digest it is checked against
// Port caveat: no signer recovery — a yes/no answer
// Variant: entryOrder=declared entryShape=direct initStyle=empty placement=last stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HostSignatureValidity2
{
};

struct HostSignatureValidity : public ContractBase
{
    struct Scratch
    {
        Array<sint8, 64> checkSignature;
        id checkDigest;
        uint64 checkI;
        bit checkOk;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 valid;
        uint64 invalid;
        uint64 checks;
        id lastDigest;
        Scratch scratch;
    };

    struct Check_input
    {
        uint64 seed;
    };

    struct Check_output {};

    PUBLIC_PROCEDURE(Check)
    {
        state.mut().scratch.checkDigest = qpi.K12(input.seed);
        for (state.mut().scratch.checkI = 0; state.mut().scratch.checkI < 64; state.mut().scratch.checkI++)
        {
        state.mut().scratch.checkSignature.set(state.mut().scratch.checkI, (sint8)(input.seed + state.mut().scratch.checkI));
        }
        state.mut().scratch.checkOk = qpi.signatureValidity(qpi.invocator(), state.mut().scratch.checkDigest, state.mut().scratch.checkSignature);
        if (state.mut().scratch.checkOk)
        {
        state.mut().valid++;
        }
        else
        {
        state.mut().invalid++;
        }
        state.mut().lastDigest = state.mut().scratch.checkDigest;
        state.mut().checks++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 valid;
        uint64 invalid;
        uint64 checks;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.valid = state.get().valid;
        output.invalid = state.get().invalid;
        output.checks = state.get().checks;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Check, 1);
    }

    INITIALIZE()
    {

    }
};
