// HostDividendDistribution — ported from PaymentSplitter
// Stresses: distributeDividends accept/refuse across amounts
// Port caveat: the payee set is the shareholder set, not a registered list
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full placement=nested stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HostDividendDistribution2
{
};

struct HostDividendDistribution : public ContractBase
{
    struct Scratch
    {
        bit payOk;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 accepted;
        uint64 refused;
        sint64 lastAmount;
        sint64 rewardTotal;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Pay_input
    {
        sint64 amountPerShare;
    };

    struct Pay_output
    {
        uint64 ok;
    };

    struct Pay_locals
    {
        Pay_input forwardedInput;
        Pay_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Pay)
    {
        locals.forwardedInput = input;
        CALL(PayBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 accepted;
        uint64 refused;
        sint64 lastAmount;
        sint64 rewardTotal;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using PayBody_input = Pay_input;

    using PayBody_output = Pay_output;

    PRIVATE_PROCEDURE(PayBody)
    {
        state.mut().inner.rewardTotal += qpi.invocationReward();
        state.mut().inner.scratch.payOk = qpi.distributeDividends(input.amountPerShare);
        state.mut().inner.lastAmount = input.amountPerShare;
        if (state.mut().inner.scratch.payOk)
        {
        state.mut().inner.accepted++;
        output.ok = 1;
        return;
        }
        state.mut().inner.refused++;
        output.ok = 0;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.accepted = state.get().inner.accepted;
        output.refused = state.get().inner.refused;
        output.lastAmount = state.get().inner.lastAmount;
        output.rewardTotal = state.get().inner.rewardTotal;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Pay, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.accepted = 0;
        state.mut().inner.refused = 0;
        state.mut().inner.lastAmount = 0;
        state.mut().inner.rewardTotal = 0;
    }
};
