// HostTickDerivedSeedQuality — ported from not-so-smart-contracts/bad_randomness
// Stresses: a seed built from the tick, the epoch and the spectrum digest, hashed and reduced — the shape a contract reaches for when it wants randomness, with the reduction bias measured
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=absent placement=last stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HostTickDerivedSeedQuality2
{
};

struct HostTickDerivedSeedQuality : public ContractBase
{
    struct Seed
    {
        uint64 tick;
        uint64 epoch;
        id digest;
        uint64 nonce;
    };
    struct Scratch
    {
        Seed runSeed;
        id runHashed;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 reduced;
        uint64 rawWord;
        uint64 inTopHalf;
        uint64 draws;
        uint64 calls;
        Scratch scratch;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 reduced;
        uint64 rawWord;
        uint64 inTopHalf;
        uint64 draws;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    PRIVATE_PROCEDURE(RunBody)
    {
        state.mut().scratch.runSeed.tick = (uint64)qpi.tick();
        state.mut().scratch.runSeed.epoch = (uint64)qpi.epoch();
        state.mut().scratch.runSeed.digest = qpi.getPrevSpectrumDigest();
        state.mut().scratch.runSeed.nonce = input.a;
        state.mut().scratch.runHashed = qpi.K12(state.mut().scratch.runSeed);
        state.mut().rawWord = state.mut().scratch.runHashed.u64._0;
        state.mut().reduced = QPI::mod(state.mut().scratch.runHashed.u64._0, 100ULL);
        state.mut().inTopHalf = state.mut().scratch.runHashed.u64._0 > 9223372036854775807ULL ? 1 : 0;
        state.mut().draws++;

        state.mut().calls++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.reduced = state.get().reduced;
        output.rawWord = state.get().rawWord;
        output.inTopHalf = state.get().inTopHalf;
        output.draws = state.get().draws;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }
};
