// TimeTickEpochRelations — ported from test/libsolidity/semanticTests/various/block_number.sol
// Stresses: tick versus initialTick versus epoch, and the per-tick transaction counter
// Port caveat: no epoch or initial tick in Solidity
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=absent placement=last stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct TimeTickEpochRelations2
{
};

struct TimeTickEpochRelations : public ContractBase
{
    struct Scratch
    {
        uint64 sampleScratch;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 samples;
        uint64 transactions;
        uint64 sinceInitial;
        uint64 epoch;
        uint64 initialTick;
        uint64 tick;
        Scratch scratch;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 tick;
        uint64 initialTick;
        uint64 epoch;
        uint64 sinceInitial;
        uint64 transactions;
        uint64 samples;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Sample_input {};

    struct Sample_output {};

    struct Sample_locals
    {
        Sample_input forwardedInput;
        Sample_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Sample)
    {
        CALL(SampleBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.tick = state.get().tick;
        output.initialTick = state.get().initialTick;
        output.epoch = state.get().epoch;
        output.sinceInitial = state.get().sinceInitial;
        output.transactions = state.get().transactions;
        output.samples = state.get().samples;
    }

    using SampleBody_input = Sample_input;

    using SampleBody_output = Sample_output;

    PRIVATE_PROCEDURE(SampleBody)
    {
        state.mut().tick = (uint64)qpi.tick();
        state.mut().initialTick = (uint64)qpi.initialTick();
        state.mut().epoch = (uint64)qpi.epoch();
        state.mut().sinceInitial = (uint64)qpi.tick() - (uint64)qpi.initialTick();
        state.mut().transactions = (uint64)qpi.numberOfTickTransactions();
        state.mut().samples++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Sample, 1);
    }
};
