// TimeEpochRolloverSchedule — ported from Governor voting periods
// Stresses: a window opened and closed by the epoch hooks
// Port caveat: epochs are protocol-level, not contract-chosen
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=empty placement=nested stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct TimeEpochRolloverSchedule2
{
};

struct TimeEpochRolloverSchedule : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 windowOpen;
        uint64 accepted;
        uint64 rejected;
        uint64 epochsSeen;
        uint64 lastEpoch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 windowOpen;
        uint64 accepted;
        uint64 rejected;
        uint64 epochsSeen;
        uint64 lastEpoch;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Vote_input {};

    struct Vote_output
    {
        uint64 ok;
    };

    struct Vote_locals
    {
        Vote_input forwardedInput;
        Vote_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Vote)
    {
        CALL(VoteBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.windowOpen = state.get().inner.windowOpen;
        output.accepted = state.get().inner.accepted;
        output.rejected = state.get().inner.rejected;
        output.epochsSeen = state.get().inner.epochsSeen;
        output.lastEpoch = state.get().inner.lastEpoch;
    }

    using VoteBody_input = Vote_input;

    using VoteBody_output = Vote_output;

    struct VoteBody_locals
    {
        uint64 scratch;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(VoteBody)
    {
        if (state.get().inner.windowOpen == 0)
        {
        state.mut().inner.rejected++;
        output.ok = 0;
        return;
        }
        state.mut().inner.accepted++;
        output.ok = 1;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Vote, 1);
    }

    INITIALIZE()
    {

    }

    BEGIN_EPOCH()
    {
        state.mut().inner.windowOpen = 1;
        state.mut().inner.lastEpoch = (uint64)qpi.epoch();
        state.mut().inner.epochsSeen++;
    }

    END_EPOCH()
    {
        state.mut().inner.windowOpen = 0;
    }
};
