// TimeDeadlineComparison — ported from EIP712 deadline check
// Stresses: a deadline compared at two widths
// Port caveat: uint256 deadline becomes uint64 and uint32
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=full placement=first stateOrder=reversed temporaries=locals width=sint16
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct TimeDeadlineComparison2
{
};

struct TimeDeadlineComparison : public ContractBase
{
    struct StateData
    {
        uint64 disagreements;
        uint64 narrowRejected;
        uint64 narrowAccepted;
        uint64 wideRejected;
        uint64 wideAccepted;
        uint64 deadline;
        uint64 placementGuard;
    };

    struct SetDeadline_input
    {
        uint64 deadline;
    };

    struct SetDeadline_output {};

    struct SetDeadline_locals
    {
        SetDeadline_input forwardedInput;
        SetDeadline_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(SetDeadline)
    {
        locals.forwardedInput = input;
        CALL(SetDeadlineBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 wideAccepted;
        uint64 wideRejected;
        uint64 narrowAccepted;
        uint64 narrowRejected;
        uint64 disagreements;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Attempt_input {};

    struct Attempt_output
    {
        uint64 ok;
    };

    struct Attempt_locals
    {
        Attempt_input forwardedInput;
        Attempt_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Attempt)
    {
        CALL(AttemptBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using SetDeadlineBody_input = SetDeadline_input;

    using SetDeadlineBody_output = SetDeadline_output;

    struct SetDeadlineBody_locals
    {
        uint64 scratch;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(SetDeadlineBody)
    {
        state.mut().deadline = input.deadline;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.wideAccepted = state.get().wideAccepted;
        output.wideRejected = state.get().wideRejected;
        output.narrowAccepted = state.get().narrowAccepted;
        output.narrowRejected = state.get().narrowRejected;
        output.disagreements = state.get().disagreements;
    }

    using AttemptBody_input = Attempt_input;

    using AttemptBody_output = Attempt_output;

    struct AttemptBody_locals
    {
        uint64 now;
        uint32 nowNarrow;
        uint32 deadlineNarrow;
        uint64 wide;
        uint64 narrow;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(AttemptBody)
    {
        locals.now = (uint64)qpi.tick() * 1000ULL + (uint64)qpi.millisecond();
        locals.nowNarrow = (uint32)locals.now;
        locals.deadlineNarrow = (uint32)state.get().deadline;
        locals.wide = locals.now <= state.get().deadline ? 1 : 0;
        locals.narrow = locals.nowNarrow <= locals.deadlineNarrow ? 1 : 0;
        if (locals.wide != locals.narrow)
        {
        state.mut().disagreements++;
        }
        if (locals.wide != 0)
        {
        state.mut().wideAccepted++;
        }
        else
        {
        state.mut().wideRejected++;
        }
        if (locals.narrow != 0)
        {
        state.mut().narrowAccepted++;
        }
        else
        {
        state.mut().narrowRejected++;
        }
        output.ok = locals.wide;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(SetDeadline, 1);
        REGISTER_USER_PROCEDURE(Attempt, 2);
    }

    INITIALIZE()
    {
        state.mut().deadline = 0;
        state.mut().wideAccepted = 0;
        state.mut().wideRejected = 0;
        state.mut().narrowAccepted = 0;
        state.mut().narrowRejected = 0;
        state.mut().disagreements = 0;
    }
};
