import type { Lexer, Token, TokenKind } from "../../lexer";
import type { ClassTemplateDecl, Declaration, EmptyDecl, EnumDecl, EnumeratorDecl, Expression, ExternBlockDecl, FriendDecl, FunctionDecl, FunctionTemplateDecl, NamespaceDecl, ParamDecl, Span, Statement, StaticAssertDecl, StructDecl, TemplateParam, TranslationUnit, TypedefDeclNode, TypeSpec, VariableDecl } from "../../ast";
export interface ParserDiagnostic {
    severity: "error" | "warning";
    message: string;
    span: Span;
    category?: "fidelity";
}
type Diagnostic = ParserDiagnostic;

export interface ParserInternals {
  lex: Lexer;
  diagnostics: ParserDiagnostic[];
  bodyDiagnostics: ParserDiagnostic[];
  gtDisabled: number;
  pending: Declaration[];
  _last: Token | null;
  parseTranslationUnit(): TranslationUnit;
  getDiagnostics(): Diagnostic[];
  parseFunctionBody(): Statement;
  peek(offset?: number): Token;
  next(): Token;
  last(): Token;
  eof(): boolean;
  expect(kind: TokenKind, context: string): Token | null;
  tryConsume(kind: TokenKind): Token | null;
  tryConsumeKw(kw: string): Token | null;
  consumeAngleClose(): void;
  parseDeclaration(): Declaration | null;
  parseNamespace(): NamespaceDecl;
  parseStruct(): StructDecl;
  declaratorFollows(): boolean;
  parseSpecializationArgs(): TypeSpec[];
  parseUnion(): StructDecl;
  parseClassOrTemplate(): StructDecl | ClassTemplateDecl;
  parseTemplateDeclaration(): Declaration;
  parseTemplateParams(): TemplateParam[];
  parseFunctionTemplate(params: TemplateParam[]): FunctionTemplateDecl;
  parseEnum(): EnumDecl;
  parseEnumeratorList(): EnumeratorDecl[];
  parseTypedef(): TypedefDeclNode;
  parseUsing(): Declaration;
  parseStaticAssertDecl(): StaticAssertDecl;
  parseExternBlock(): ExternBlockDecl | FunctionDecl;
  parseFriend(): FriendDecl;
  parseAccessSpec(): EmptyDecl;
  parseFunctionOrVariable(): Declaration;
  parseFunctionOrVariablePeekType(): Declaration;
  parseIdentifierDeclaration(): Declaration;
  parseAfterModifiers(isConstexpr: boolean, isStatic: boolean, isInline: boolean, isVirtual: boolean, isExtern: boolean): Declaration;
  looksLikeDirectInit(): boolean;
  parseDirectInitVar(name: string, type: TypeSpec, isConstexpr: boolean, isStatic: boolean): VariableDecl;
  parseFunctionAfterReturnType(retType: TypeSpec, isExternC: boolean): FunctionDecl;
  parseFunctionRest(name: string, retType: TypeSpec, isConstexpr: boolean, isStatic: boolean, isInline: boolean, isVirtual: boolean, isExternC: boolean): FunctionDecl;
  parseVariableRest(name: string, type: TypeSpec, isConstexpr: boolean, isStatic: boolean): Declaration;
  parseDeclaratorList(baseType: TypeSpec, firstName: string, isConstexpr: boolean, isStatic: boolean): VariableDecl[];
  parseFunctionParams(): ParamDecl[];
  parseTypeSpec(): TypeSpec;
  parseBaseType(): TypeSpec;
  templateArgIsExpr(): boolean;
  parseBuiltinType(): TypeSpec;
  parseAccessAndType(): TypeSpec;
  parseExpression(): Expression;
  parseAssignment(): Expression;
  parseTernary(): Expression;
  parseLogicalOr(): Expression;
  parseLogicalAnd(): Expression;
  parseBitwiseOr(): Expression;
  parseBitwiseXor(): Expression;
  parseBitwiseAnd(): Expression;
  parseEquality(): Expression;
  parseComparison(): Expression;
  parseShift(): Expression;
  parseAdditive(): Expression;
  parseMultiplicative(): Expression;
  parseUnary(): Expression;
  parsePostfix(): Expression;
  looksLikeTemplateArgs(): boolean;
  parseBraceArg(): Expression;
  parsePrimaryExpression(): Expression;
  parseQualifiedName(stopAtAngle?: boolean): string;
  parseMaybeQualifiedName(): string;
  parseCommaSequence(): Expression;
  looksLikeLocalDecl(): boolean;
  skipAngleArgs(): boolean;
  isTypeCast(): boolean;
  parseCast(): Expression;
  parseSizeof(): Expression;
  parseArgList(): Expression[];
  parseStatement(): Statement;
  parseCompoundStatement(): Statement;
  parseIf(): Statement;
  parseFor(): Statement;
  parseWhile(): Statement;
  parseDoWhile(): Statement;
  parseSwitch(): Statement;
  parseCase(): Statement;
  parseDefault(): Statement;
  parseReturn(): Statement;
  parsePreprocessorLine(): Declaration;
  skipBalanced(open: TokenKind, close: TokenKind): void;
  parseDeclarationList(): Declaration[];
  parseClassMembers(): Declaration[];
  recover(beforeIndex: number, errsBefore: number): void;
  parseCharValue(text: string): number;
  makeSpan(start: Span): Span;
  extractIdl(translationUnit: TranslationUnit): Record<string, {
        inputType: number;
        kind: number;
        inSize: number;
        outSize: number;
    }>;
  extractIdlFromNode(node: Declaration, idl: Record<string, any>): void;
  extractIdlFromStmt(statement: Statement, idl: Record<string, any>): void;
  checkRegistrationCall(call: any, idl: Record<string, any>): void;
}
