// NsBaseMemberVersusFileConstant — ported from test/libsolidity/semanticTests/inheritance/inherited_state_var_shadowing.sol
// Stresses: a base-class member and a file-scope constant sharing a name: the member read through the object must not pick up the constant, and the bare name must not pick up the member
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=absent placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

static constexpr uint64 ceiling = 11;

struct Holder
{
uint64 ceiling;
};

struct NsBaseMemberVersusFileConstant2
{
};

struct NsBaseMemberVersusFileConstant : public ContractBase
{
    struct Scratch
    {
        uint64 snapScratch;
        Holder snapHolder;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 calls;
        uint64 witness;
        uint64 sum;
        uint64 fromMember;
        uint64 fromConstant;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Snap_input
    {
        uint64 seed;
    };

    struct Snap_output {};

    struct Snap_locals
    {
        Snap_input forwardedInput;
        Snap_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Snap)
    {
        locals.forwardedInput = input;
        CALL(SnapBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 fromConstant;
        uint64 fromMember;
        uint64 sum;
        uint64 witness;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using SnapBody_input = Snap_input;

    using SnapBody_output = Snap_output;

    PRIVATE_PROCEDURE(SnapBody)
    {
        state.mut().inner.scratch.snapHolder.ceiling = 640;
        state.mut().inner.fromConstant = ceiling;
        state.mut().inner.fromMember = state.mut().inner.scratch.snapHolder.ceiling;
        state.mut().inner.sum = ceiling + state.mut().inner.scratch.snapHolder.ceiling;
        state.mut().inner.witness = 1;

        state.mut().inner.calls++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.fromConstant = state.get().inner.fromConstant;
        output.fromMember = state.get().inner.fromMember;
        output.sum = state.get().inner.sum;
        output.witness = state.get().inner.witness;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Snap, 1);
    }
};
