// NsEnumConstantHiddenByMember — ported from test/libsolidity/semanticTests/scoping/name_shadowing.sol
// Stresses: an enum constant hidden by a member function of the same name
// Port caveat: documented divergence: clang rejects, the TypeScript backend accepts
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=full placement=first stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

enum Kind { Helper = 3, Other = 4 };

struct NsEnumConstantHiddenByMember2
{
};

struct NsEnumConstantHiddenByMember : public ContractBase
{
    struct StateData
    {
        uint64 kind;
        uint64 helperCalls;
        uint64 placementGuard;
    };

    struct Helper_input
    {
        uint64 value;
    };

    struct Helper_output
    {
        uint64 doubled;
    };

    PRIVATE_FUNCTION(Helper)
    {
        output.doubled = input.value * 2;
    }

    struct Assign_input
    {
        uint64 seed;
    };

    struct Assign_output {};

    struct Assign_locals
    {
        Assign_input forwardedInput;
        Assign_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Assign)
    {
        locals.forwardedInput = input;
        CALL(AssignBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 kind;
        uint64 helperCalls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using AssignBody_input = Assign_input;

    using AssignBody_output = Assign_output;

    struct AssignBody_locals
    {
        Helper_input request;
        Helper_output reply;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(AssignBody)
    {
        locals.request.value = input.seed;
        CALL(Helper, locals.request, locals.reply);
        state.mut().helperCalls += locals.reply.doubled;
        // Unqualified: the enum constant at file scope, or the member declared above?
        state.mut().kind = Helper;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.kind = state.get().kind;
        output.helperCalls = state.get().helperCalls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Assign, 1);
    }

    INITIALIZE()
    {
        state.mut().kind = 0;
        state.mut().helperCalls = 0;
    }
};
