// NsInheritedNamespacedTypedef — ported from test/libsolidity/semanticTests/inheritance/inherited_type.sol
// Stresses: sizeof of a struct inheriting from a namespaced typedef
// Port caveat: the historical failure returned 2 for a 24-byte type while every self-consistency check passed
// Variant: entryOrder=reversed entryShape=direct initStyle=absent ns=collision placement=last stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

namespace Alpha
{
struct Base
{
    uint64 a;
    uint64 b;
    uint64 c;
};
}

namespace Beta
{
struct Base
{
    uint16 a;
};
}

struct Derived : public Alpha::Base
{
    uint64 d;
};

struct NsInheritedNamespacedTypedef2
{
};

struct NsInheritedNamespacedTypedef : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        uint64 baseSize;
        uint64 derivedSize;
        Derived derived;
    };

    struct Write_input
    {
        uint64 value;
    };

    struct Write_output {};

    struct Write_locals
    {
        uint64 scratch;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Write)
    {
        state.mut().derived.a = input.value;
        state.mut().derived.d = input.value + 1;
        state.mut().derivedSize = sizeof(Derived);
        state.mut().baseSize = sizeof(Alpha::Base);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 derivedSize;
        uint64 baseSize;
        uint64 a;
        uint64 d;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.derivedSize = state.get().derivedSize;
        output.baseSize = state.get().baseSize;
        output.a = (uint64)state.get().derived.a;
        output.d = state.get().derived.d;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Write, 1);
    }
};
