// NsLocalsMemberNamedLikeNamespace — ported from test/libsolidity/semanticTests/scoping/name_shadowing.sol
// Stresses: a locals member named like a namespace
// Port caveat: library-name shadowing in the original
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=absent placement=last stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

namespace Port
{
static constexpr uint64 base = 1000;
struct Config
{
    uint64 limit;
};
}

struct NsLocalsMemberNamedLikeNamespace2
{
};

struct NsLocalsMemberNamedLikeNamespace : public ContractBase
{
    struct Scratch
    {
        uint64 usePort;
        Port::Config useConfig;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 calls;
        uint64 fromNamespace;
        uint64 fromLocal;
        Scratch scratch;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 fromLocal;
        uint64 fromNamespace;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Use_input
    {
        uint64 value;
    };

    struct Use_output {};

    struct Use_locals
    {
        Use_input forwardedInput;
        Use_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Use)
    {
        locals.forwardedInput = input;
        CALL(UseBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.fromLocal = state.get().fromLocal;
        output.fromNamespace = state.get().fromNamespace;
        output.calls = state.get().calls;
    }

    using UseBody_input = Use_input;

    using UseBody_output = Use_output;

    PRIVATE_PROCEDURE(UseBody)
    {
        state.mut().scratch.usePort = input.value + 1;
        state.mut().scratch.useConfig.limit = Port::base;
        state.mut().fromLocal = state.mut().scratch.usePort;
        state.mut().fromNamespace = state.mut().scratch.useConfig.limit;
        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Use, 1);
    }
};
