// NsMemberShadowsStateField — ported from test/libsolidity/semanticTests/inheritance/inherited_state.sol
// Stresses: a `_locals` member named exactly like a state member, written and read in the same entry — the QPI-specific form of SWC-119 shadowing
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=empty placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct NsMemberShadowsStateField2
{
};

struct NsMemberShadowsStateField : public ContractBase
{
    struct Scratch
    {
        uint64 runBalance;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 witness;
        uint64 balance;
        uint64 calls;
        uint64 accumulator;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 accumulator;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        uint64 amount;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.accumulator = state.get().inner.accumulator;
        output.calls = state.get().inner.calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    PRIVATE_PROCEDURE(RunBody)
    {
        state.mut().inner.scratch.runBalance = state.get().inner.balance + input.amount;
        state.mut().inner.witness = state.mut().inner.scratch.runBalance;
        state.mut().inner.balance = state.mut().inner.scratch.runBalance;
        state.mut().inner.accumulator = state.get().inner.balance;

        state.mut().inner.calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
