// NsOverloadResolveByArity — ported from test/libsolidity/semanticTests/inheritance/overloaded_function_call_resolve_to_first.sol
// Stresses: arity-based overload resolution
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=absent placement=nested stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

namespace Helpers
{
static constexpr uint64 ONE_ARG_TAG = 100;
static constexpr uint64 TWO_ARG_TAG = 200;
}

struct NsOverloadResolveByArity2
{
};

struct NsOverloadResolveByArity : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 total;
        uint64 fromTwo;
        uint64 fromOne;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct OneArg_input
    {
        uint64 a;
    };

    struct OneArg_output
    {
        uint64 result;
    };

    PRIVATE_FUNCTION(OneArg)
    {
        output.result = input.a + Helpers::ONE_ARG_TAG;
    }

    struct TwoArg_input
    {
        uint64 a;
        uint64 b;
    };

    struct TwoArg_output
    {
        uint64 result;
    };

    PRIVATE_FUNCTION(TwoArg)
    {
        output.result = input.a + input.b + Helpers::TWO_ARG_TAG;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 fromOne;
        uint64 fromTwo;
        uint64 total;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Resolve_input
    {
        uint64 a;
        uint64 b;
    };

    struct Resolve_output {};

    struct Resolve_locals
    {
        Resolve_input forwardedInput;
        Resolve_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Resolve)
    {
        locals.forwardedInput = input;
        CALL(ResolveBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.fromOne = state.get().inner.fromOne;
        output.fromTwo = state.get().inner.fromTwo;
        output.total = state.get().inner.total;
    }

    using ResolveBody_input = Resolve_input;

    using ResolveBody_output = Resolve_output;

    struct ResolveBody_locals
    {
        OneArg_input oneIn;
        OneArg_output oneOut;
        TwoArg_input twoIn;
        TwoArg_output twoOut;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(ResolveBody)
    {
        locals.oneIn.a = input.a;
        CALL(OneArg, locals.oneIn, locals.oneOut);
        locals.twoIn.a = input.a;
        locals.twoIn.b = input.b;
        CALL(TwoArg, locals.twoIn, locals.twoOut);
        state.mut().inner.fromOne = locals.oneOut.result;
        state.mut().inner.fromTwo = locals.twoOut.result;
        state.mut().inner.total = locals.oneOut.result + locals.twoOut.result;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Resolve, 1);
    }
};
