// NsQualifiedAndUnqualifiedInOneExpression — ported from test/libsolidity/semanticTests/using/using_for_function_on_int.sol
// Stresses: two spellings of one name in a single expression
// Variant: constSource=input entryOrder=reversed entryShape=viaPrivate initStyle=full placement=last stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

namespace Port
{
static constexpr uint64 factor = 3;
}

using namespace Port;

static constexpr uint64 offset = 11;

struct NsQualifiedAndUnqualifiedInOneExpression2
{
};

struct NsQualifiedAndUnqualifiedInOneExpression : public ContractBase
{
    struct Scratch
    {
        uint64 computeScratch;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 calls;
        uint64 viaUnqualified;
        uint64 viaQualified;
        uint64 product;
        Scratch scratch;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 product;
        uint64 viaQualified;
        uint64 viaUnqualified;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Compute_input
    {
        uint64 value;
    };

    struct Compute_output {};

    struct Compute_locals
    {
        Compute_input forwardedInput;
        Compute_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Compute)
    {
        locals.forwardedInput = input;
        CALL(ComputeBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.product = state.get().product;
        output.viaQualified = state.get().viaQualified;
        output.viaUnqualified = state.get().viaUnqualified;
        output.calls = state.get().calls;
    }

    using ComputeBody_input = Compute_input;

    using ComputeBody_output = Compute_output;

    PRIVATE_PROCEDURE(ComputeBody)
    {
        state.mut().scratch.computeScratch = input.value;
        state.mut().viaQualified = state.mut().scratch.computeScratch * Port::factor + offset;
        state.mut().viaUnqualified = state.mut().scratch.computeScratch * factor + offset;
        state.mut().product = state.get().viaQualified * state.get().viaUnqualified;
        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Compute, 1);
    }

    INITIALIZE()
    {
        state.mut().product = 0;
        state.mut().viaQualified = 0;
        state.mut().viaUnqualified = 0;
        state.mut().calls = 0;
    }
};
