// NsQualifiedAndUnqualifiedInOneExpression — ported from test/libsolidity/semanticTests/using/using_for_function_on_int.sol
// Stresses: two spellings of one name in a single expression
// Variant: constSource=constexpr entryOrder=declared entryShape=direct initStyle=full placement=nested stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

namespace Port
{
static constexpr uint64 factor = 3;
}

using namespace Port;

static constexpr uint64 offset = 11;

struct NsQualifiedAndUnqualifiedInOneExpression2
{
};

struct NsQualifiedAndUnqualifiedInOneExpression : public ContractBase
{
    struct Scratch
    {
        uint64 computeScratch;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 product;
        uint64 viaQualified;
        uint64 viaUnqualified;
        uint64 calls;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Compute_input
    {
        uint64 value;
    };

    struct Compute_output {};

    PUBLIC_PROCEDURE(Compute)
    {
        state.mut().inner.scratch.computeScratch = input.value;
        state.mut().inner.viaQualified = state.mut().inner.scratch.computeScratch * Port::factor + offset;
        state.mut().inner.viaUnqualified = state.mut().inner.scratch.computeScratch * factor + offset;
        state.mut().inner.product = state.get().inner.viaQualified * state.get().inner.viaUnqualified;
        state.mut().inner.calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 product;
        uint64 viaQualified;
        uint64 viaUnqualified;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.product = state.get().inner.product;
        output.viaQualified = state.get().inner.viaQualified;
        output.viaUnqualified = state.get().inner.viaUnqualified;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Compute, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.product = 0;
        state.mut().inner.viaQualified = 0;
        state.mut().inner.viaUnqualified = 0;
        state.mut().inner.calls = 0;
    }
};
