// NsSameNamedStructsDifferentFieldValues — ported from test/libsolidity/semanticTests/libraries/library_struct_size.sol
// Stresses: two same-named structs whose fields have the same names and the same widths but are written with different values through each spelling — identical layouts, so only the values can tell the resolution apart
// Port caveat: This is deliberately the case round 1's twin-struct archetypes could not catch: the sizes match, so a size comparison sees nothing.
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=absent placement=last stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

namespace Alpha
{
struct Record
{
    uint64 a;
    uint64 b;
};
}

namespace Beta
{
struct Record
{
    uint64 a;
    uint64 b;
};
}

struct NsSameNamedStructsDifferentFieldValues2
{
};

struct NsSameNamedStructsDifferentFieldValues : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        uint64 alphaA;
        uint64 alphaB;
        uint64 betaA;
        uint64 betaB;
        uint64 sizesEqual;
        uint64 calls;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 alphaA;
        uint64 alphaB;
        uint64 betaA;
        uint64 betaB;
        uint64 sizesEqual;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Snap_input
    {
        uint64 seed;
    };

    struct Snap_output {};

    struct Snap_locals
    {
        Snap_input forwardedInput;
        Snap_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Snap)
    {
        locals.forwardedInput = input;
        CALL(SnapBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.alphaA = state.get().alphaA;
        output.alphaB = state.get().alphaB;
        output.betaA = state.get().betaA;
        output.betaB = state.get().betaB;
        output.sizesEqual = state.get().sizesEqual;
        output.calls = state.get().calls;
    }

    using SnapBody_input = Snap_input;

    using SnapBody_output = Snap_output;

    struct SnapBody_locals
    {
        Alpha::Record alpha;
        Beta::Record beta;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(SnapBody)
    {
        locals.alpha.a = 11;
        locals.alpha.b = 22;
        locals.beta.a = 33;
        locals.beta.b = 44;
        state.mut().alphaA = locals.alpha.a;
        state.mut().alphaB = locals.alpha.b;
        state.mut().betaA = locals.beta.a;
        state.mut().betaB = locals.beta.b;
        state.mut().sizesEqual = sizeof(Alpha::Record) == sizeof(Beta::Record) ? 1 : 0;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Snap, 1);
    }
};
