// NsSameNameAcrossEnumAndStruct — ported from test/libsolidity/semanticTests/scoping/name_shadowing.sol
// Stresses: one name declared as an enum constant in one namespace and as a struct in another, so the two live in different declaration kinds and only the use site says which was meant
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full placement=last stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

namespace AsEnum
{
enum Tags { Marker = 77 };
}

namespace AsStruct
{
struct Marker
{
    uint64 a;
    uint64 b;
};
}

struct NsSameNameAcrossEnumAndStruct2
{
};

struct NsSameNameAcrossEnumAndStruct : public ContractBase
{
    struct Scratch
    {
        AsStruct::Marker snapMarker;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 calls;
        uint64 structField;
        uint64 structSize;
        uint64 enumValue;
        Scratch scratch;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 enumValue;
        uint64 structSize;
        uint64 structField;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Snap_input
    {
        uint64 seed;
    };

    struct Snap_output {};

    struct Snap_locals
    {
        Snap_input forwardedInput;
        Snap_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Snap)
    {
        locals.forwardedInput = input;
        CALL(SnapBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.enumValue = state.get().enumValue;
        output.structSize = state.get().structSize;
        output.structField = state.get().structField;
        output.calls = state.get().calls;
    }

    using SnapBody_input = Snap_input;

    using SnapBody_output = Snap_output;

    PRIVATE_PROCEDURE(SnapBody)
    {
        state.mut().enumValue = (uint64)AsEnum::Marker;
        state.mut().scratch.snapMarker.a = 5;
        state.mut().scratch.snapMarker.b = 6;
        state.mut().structSize = sizeof(AsStruct::Marker);
        state.mut().structField = state.mut().scratch.snapMarker.a + state.mut().scratch.snapMarker.b;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Snap, 1);
    }

    INITIALIZE()
    {
        state.mut().enumValue = 0;
        state.mut().structSize = 0;
        state.mut().structField = 0;
        state.mut().calls = 0;
    }
};
