// NsTwinWithIdField — ported from test/libsolidity/semanticTests/types/address_types.sol
// Stresses: a namespaced struct carrying a 32-byte id, where a wrong resolution changes alignment as well as size
// Variant: entryOrder=reversed entryShape=direct initStyle=full ns=aliasOfAlias placement=last stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

namespace Port
{
struct Entry
{
    id owner;
    uint64 wide;
};
using EntryA = Entry;
using EntryB = EntryA;
using EntryC = EntryB;
}

struct PlainEntry
{
    id owner;
    uint64 wide;
};

struct NsTwinWithIdField2
{
};

struct NsTwinWithIdField : public ContractBase
{
    struct Scratch
    {
        uint64 writeScratch;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 plainSize;
        uint64 qualifiedSize;
        PlainEntry plain;
        Port::EntryC qualified;
        Scratch scratch;
    };

    struct Write_input
    {
        uint64 value;
    };

    struct Write_output {};

    PUBLIC_PROCEDURE(Write)
    {
        state.mut().qualified.wide = input.value;
        state.mut().plain.wide = input.value;
        state.mut().qualifiedSize = sizeof(Port::EntryC);
        state.mut().plainSize = sizeof(PlainEntry);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 qualifiedSize;
        uint64 plainSize;
        uint64 payload;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.qualifiedSize = state.get().qualifiedSize;
        output.plainSize = state.get().plainSize;
        output.payload = (uint64)state.get().qualified.wide;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Write, 1);
    }

    INITIALIZE()
    {
        state.mut().qualifiedSize = 0;
        state.mut().plainSize = 0;
    }
};
