// NsTwinStruct — ported from test/libsolidity/semanticTests/libraries/library_struct.sol
// Stresses: two namespaces declaring the same struct name with different layouts; only the qualification picks the right one
// Port caveat: Solidity libraries stand in for namespaces; the collision is expressible in C++ and not in Solidity.
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=absent ns=aliasOfAlias placement=last stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

namespace Port
{
struct Entry
{
    uint64 wide;
    uint32 narrow;
    uint8 tag;
};
using EntryA = Entry;
using EntryB = EntryA;
using EntryC = EntryB;
}

struct PlainEntry
{
    uint64 wide;
    uint32 narrow;
    uint8 tag;
};

struct NsTwinStruct2
{
};

struct NsTwinStruct : public ContractBase
{
    struct Scratch
    {
        uint64 writeScratch;
    };

    struct StateData
    {
        uint64 placementGuard;
        Port::EntryC qualified;
        PlainEntry plain;
        uint64 qualifiedSize;
        uint64 plainSize;
        Scratch scratch;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 qualifiedSize;
        uint64 plainSize;
        uint64 payload;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Write_input
    {
        uint64 value;
    };

    struct Write_output {};

    struct Write_locals
    {
        Write_input forwardedInput;
        Write_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Write)
    {
        locals.forwardedInput = input;
        CALL(WriteBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.qualifiedSize = state.get().qualifiedSize;
        output.plainSize = state.get().plainSize;
        output.payload = (uint64)state.get().qualified.wide;
    }

    using WriteBody_input = Write_input;

    using WriteBody_output = Write_output;

    PRIVATE_PROCEDURE(WriteBody)
    {
        state.mut().qualified.wide = input.value;
        state.mut().plain.wide = input.value;
        state.mut().qualifiedSize = sizeof(Port::EntryC);
        state.mut().plainSize = sizeof(PlainEntry);
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Write, 1);
    }
};
