// NsTwinEnumsAcrossFourNamespaces — ported from test/libsolidity/semanticTests/enums/using_enums.sol
// Stresses: four enums sharing one constant name across four namespaces, so the last-declared-wins rule F213 describes is visible at every position rather than only the last
// Port caveat: This is the F213 shape widened: the earlier archetype used two namespaces, this one uses four so a resolution that picks the first, the last or any middle declaration is distinguishable.
// Variant: entryOrder=declared entryShape=direct initStyle=absent placement=last stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

namespace K1
{
enum Kind { Tag = 1 };
}

namespace K2
{
enum Kind { Tag = 2 };
}

namespace K3
{
enum Kind { Tag = 4 };
}

namespace K4
{
enum Kind { Tag = 8 };
}

struct NsTwinEnumsAcrossFourNamespaces2
{
};

struct NsTwinEnumsAcrossFourNamespaces : public ContractBase
{
    struct Scratch
    {
        uint64 snapScratch;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 first;
        uint64 second;
        uint64 third;
        uint64 fourth;
        uint64 mask;
        uint64 calls;
        Scratch scratch;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 first;
        uint64 second;
        uint64 third;
        uint64 fourth;
        uint64 mask;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.first = state.get().first;
        output.second = state.get().second;
        output.third = state.get().third;
        output.fourth = state.get().fourth;
        output.mask = state.get().mask;
        output.calls = state.get().calls;
    }

    struct Snap_input
    {
        uint64 seed;
    };

    struct Snap_output {};

    PUBLIC_PROCEDURE(Snap)
    {
        state.mut().first = (uint64)K1::Tag;
        state.mut().second = (uint64)K2::Tag;
        state.mut().third = (uint64)K3::Tag;
        state.mut().fourth = (uint64)K4::Tag;
        state.mut().mask = (uint64)K1::Tag | (uint64)K2::Tag | (uint64)K3::Tag | (uint64)K4::Tag;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Snap, 1);
    }
};
