// NsTwinEnum — ported from test/libsolidity/semanticTests/enums/enum_explicit_overflow.sol
// Stresses: namespaced enum underlying width
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=absent ns=collision placement=nested stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

namespace Alpha
{
enum Status : uint64 { Idle = 0, Busy = 1, Done = 2 };
}

namespace Beta
{
enum Status : uint8 { Idle = 0, Busy = 1, Done = 2 };
}

struct NsTwinEnum2
{
};

struct NsTwinEnum : public ContractBase
{
    struct Scratch
    {
        uint64 advanceScratch;
    };

    struct StateData
    {
        struct Inner
        {
        Alpha::Status status;
        uint64 statusSize;
        uint64 observed;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 statusSize;
        uint64 observed;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Advance_input
    {
        uint64 value;
    };

    struct Advance_output {};

    struct Advance_locals
    {
        Advance_input forwardedInput;
        Advance_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Advance)
    {
        locals.forwardedInput = input;
        CALL(AdvanceBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.statusSize = state.get().inner.statusSize;
        output.observed = state.get().inner.observed;
    }

    using AdvanceBody_input = Advance_input;

    using AdvanceBody_output = Advance_output;

    PRIVATE_PROCEDURE(AdvanceBody)
    {
        state.mut().inner.status = (Alpha::Status)QPI::mod(input.value, 3ULL);
        state.mut().inner.statusSize = sizeof(Alpha::Status);
        state.mut().inner.observed = (uint64)state.get().inner.status;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Advance, 1);
    }
};
