// NsUnderscoreNamedMember — ported from test/libsolidity/semanticTests/underscore/as_function.sol
// Stresses: single-underscore identifiers
// Variant: placement=last
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct NsUnderscoreNamedMember2
{
};

struct NsUnderscoreNamedMember : public ContractBase
{
    struct Scratch
    {
        uint64 assign_scratch;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 _;
        uint64 _value;
        uint64 value_;
        uint64 combined;
        Scratch scratch;
    };

    struct Assign_input
    {
        uint64 seed;
    };

    struct Assign_output {};

    PUBLIC_PROCEDURE(Assign)
    {
        state.mut().scratch.assign_scratch = input.seed;
        state.mut()._ = state.mut().scratch.assign_scratch;
        state.mut()._value = state.mut().scratch.assign_scratch + 1;
        state.mut().value_ = state.mut().scratch.assign_scratch + 2;
        state.mut().combined = state.get()._ + state.get()._value + state.get().value_;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 combined;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.combined = state.get().combined;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Assign, 1);
    }

    INITIALIZE()
    {
        state.mut()._ = 0;
        state.mut()._value = 0;
        state.mut().value_ = 0;
        state.mut().combined = 0;
    }
};
