// LogCountMatchesLoopTrips — ported from test/libsolidity/semanticTests/events/event_emit.sol
// Stresses: one log per loop iteration with the index in the payload — the log count is the trip count, so an unrolled loop that emits once too often is visible without touching state
// Variant: entryOrder=declared entryShape=direct initStyle=full placement=nested stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

enum LogKind { Iteration = 71 };

struct LogCountMatchesLoopTrips2
{
};

struct LogCountMatchesLoopTrips : public ContractBase
{
    struct LogMsg
    {
        uint32 _contractIndex;
        uint32 _type;
        uint64 value;
        sint8 _terminator;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 calls;
        uint64 sum;
        uint64 trips;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 trips;
        uint64 sum;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.trips = state.get().inner.trips;
        output.sum = state.get().inner.sum;
        output.calls = state.get().inner.calls;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        LogMsg message;
        uint64 i;
        uint64 bounded;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.bounded = input.a > 8 ? 8 : input.a;
        locals.message._contractIndex = 0;
        locals.message._type = Iteration;
        locals.message._terminator = 0;
        for (locals.i = 0; locals.i < locals.bounded; locals.i++)
        {
        locals.message.value = locals.i;
        LOG_INFO(locals.message);
        state.mut().inner.sum += locals.i;
        }
        state.mut().inner.trips = locals.bounded;

        state.mut().inner.calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.trips = 0;
        state.mut().inner.sum = 0;
        state.mut().inner.calls = 0;
    }
};
