// LogPackedBitFields — ported from test/libsolidity/semanticTests/events/event_various_types.sol
// Stresses: a payload whose fields are packed by hand into one uint64 and also carried as separate narrow members — the same information twice, so a padding difference between them shows up
// Variant: entryOrder=reversed entryShape=direct initStyle=empty placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

enum LogKind { Packed = 73 };

struct LogPackedBitFields2
{
};

struct LogPackedBitFields : public ContractBase
{
    struct LogMsg
    {
        uint32 _contractIndex;
        uint32 _type;
        uint64 packed;
        uint8 flag;
        uint16 medium;
        uint32 wide;
        sint8 _terminator;
    };
    struct Scratch
    {
        LogMsg runMessage;
        uint64 runValue;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 calls;
        uint64 emitted;
        uint64 packed;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    PUBLIC_PROCEDURE(Run)
    {
        state.mut().inner.scratch.runValue = ((input.a & 255ULL) << 48) | ((input.b & 65535ULL) << 32) | (input.a & 4294967295ULL);
        state.mut().inner.scratch.runMessage._contractIndex = 0;
        state.mut().inner.scratch.runMessage._type = Packed;
        state.mut().inner.scratch.runMessage._terminator = 0;
        state.mut().inner.scratch.runMessage.packed = state.mut().inner.scratch.runValue;
        state.mut().inner.scratch.runMessage.flag = (uint8)input.a;
        state.mut().inner.scratch.runMessage.medium = (uint16)input.b;
        state.mut().inner.scratch.runMessage.wide = (uint32)input.a;
        LOG_INFO(state.mut().inner.scratch.runMessage);
        state.mut().inner.packed = state.mut().inner.scratch.runValue;
        state.mut().inner.emitted++;

        state.mut().inner.calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 packed;
        uint64 emitted;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.packed = state.get().inner.packed;
        output.emitted = state.get().inner.emitted;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
