// LogPayloadWithIdField — ported from test/libsolidity/semanticTests/events/event_indexed_address.sol
// Stresses: an id member inside a log payload
// Port caveat: no indexed topics — the id is inline
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full layout=widestFirst placement=last stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

enum LogKind { Transfer = 40 };

struct LogPayloadWithIdField2
{
};

struct LogPayloadWithIdField : public ContractBase
{
                        struct LogMsg
                        {
                            uint32 _contractIndex;
                            uint32 _type;
                            id from;
                            id to;
                            uint64 amount;
                            sint8 _terminator;
                        };

    struct Scratch
    {
        LogMsg emitMessage;
        uint64 emitI;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 emitted;
        uint64 lastAmount;
        Scratch scratch;
    };

    struct Emit_input
    {
        uint64 count;
    };

    struct Emit_output {};

    struct Emit_locals
    {
        Emit_input forwardedInput;
        Emit_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Emit)
    {
        locals.forwardedInput = input;
        CALL(EmitBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 emitted;
        uint64 lastAmount;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using EmitBody_input = Emit_input;

    using EmitBody_output = Emit_output;

    PRIVATE_PROCEDURE(EmitBody)
    {
        state.mut().scratch.emitMessage._contractIndex = 0;
        state.mut().scratch.emitMessage._type = Transfer;
        state.mut().scratch.emitMessage._terminator = 0;
        state.mut().scratch.emitMessage.from = qpi.invocator();
        for (state.mut().scratch.emitI = 0; state.mut().scratch.emitI < input.count; state.mut().scratch.emitI++)
        {
        state.mut().scratch.emitMessage.to = qpi.K12(state.mut().scratch.emitI);
        state.mut().scratch.emitMessage.amount = state.mut().scratch.emitI * 1000;
        LOG_INFO(state.mut().scratch.emitMessage);
        state.mut().emitted++;
        state.mut().lastAmount = state.mut().scratch.emitMessage.amount;
        }
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.emitted = state.get().emitted;
        output.lastAmount = state.get().lastAmount;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Emit, 1);
    }

    INITIALIZE()
    {
        state.mut().emitted = 0;
        state.mut().lastAmount = 0;
    }
};
