// LogSkippedByEarlyReturn — ported from test/libsolidity/semanticTests/events/event_emit_in_branch.sol
// Stresses: a log on the far side of an early return
// Variant: entryOrder=declared entryShape=direct initStyle=full placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

enum LogKind { Accepted = 50, Rejected = 51 };

struct LogSkippedByEarlyReturn2
{
};

struct LogSkippedByEarlyReturn : public ContractBase
{
    struct LogMsg
    {
        uint32 _contractIndex;
        uint32 _type;
        uint64 value;
        sint8 _terminator;
    };
    struct Scratch
    {
        LogMsg submitMessage;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 logged;
        uint64 rejected;
        uint64 accepted;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 accepted;
        uint64 rejected;
        uint64 logged;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.accepted = state.get().inner.accepted;
        output.rejected = state.get().inner.rejected;
        output.logged = state.get().inner.logged;
    }

    struct Submit_input
    {
        uint64 amount;
    };

    struct Submit_output
    {
        uint64 ok;
    };

    PUBLIC_PROCEDURE(Submit)
    {
        state.mut().inner.scratch.submitMessage._contractIndex = 0;
        state.mut().inner.scratch.submitMessage._terminator = 0;
        state.mut().inner.scratch.submitMessage.value = input.amount;
        if (input.amount == 0 || input.amount > 1000)
        {
        state.mut().inner.scratch.submitMessage._type = Rejected;
        LOG_INFO(state.mut().inner.scratch.submitMessage);
        state.mut().inner.rejected++;
        state.mut().inner.logged++;
        output.ok = 0;
        return;
        }
        state.mut().inner.accepted++;
        state.mut().inner.scratch.submitMessage._type = Accepted;
        LOG_INFO(state.mut().inner.scratch.submitMessage);
        state.mut().inner.logged++;
        output.ok = 1;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Submit, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.accepted = 0;
        state.mut().inner.rejected = 0;
        state.mut().inner.logged = 0;
    }
};
