// CalleeSharedStructDefinition — ported from multiSource/
// Stresses: a struct defined identically in caller and callee
// Variant: layout=declared placement=first
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CalleeSharedStructDefinition2
{
};

struct CalleeSharedStructDefinition : public ContractBase
{
    struct StateData
    {
        uint64 echoed;
        uint64 envelopeSize;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 echoed;
        uint64 envelopeSize;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.echoed = state.get().echoed;
        output.envelopeSize = state.get().envelopeSize;
    }

    struct Send_input
    {
        uint64 wide;
        uint64 medium;
        uint64 tiny;
    };

    struct Send_output {};

    struct Send_locals
    {
        EnvelopeLedger::Accept_input request;
        EnvelopeLedger::Accept_output reply;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Send)
    {
        locals.request.envelope.wide = input.wide;
        locals.request.envelope.medium = (uint32)input.medium;
        locals.request.envelope.tiny = (uint8)input.tiny;
        INVOKE_OTHER_CONTRACT_PROCEDURE(EnvelopeLedger, Accept, locals.request, locals.reply, 0);
        state.mut().echoed = locals.reply.echoed;
        state.mut().envelopeSize = sizeof(locals.request.envelope);
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Send, 1);
    }

    INITIALIZE()
    {
        state.mut().echoed = 0;
        state.mut().envelopeSize = 0;
    }
};
