// CalleeOutputPartiallyRead — ported from test/libsolidity/semanticTests/functionCall/external_call_return_struct.sol
// Stresses: a wide callee output of which one member is used
// Variant: entryOrder=reversed entryShape=direct initStyle=absent placement=last stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CalleeOutputPartiallyRead2
{
};

struct CalleeOutputPartiallyRead : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        uint64 valueOnly;
        uint64 presentCount;
        uint64 populationSum;
        uint64 reads;
    };

    struct Seed_input
    {
        uint64 key;
        uint64 value;
    };

    struct Seed_output {};

    struct Seed_locals
    {
        WideLedger::Put_input request;
        WideLedger::Put_output reply;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Seed)
    {
        locals.request.key = input.key;
        locals.request.value = input.value;
        INVOKE_OTHER_CONTRACT_PROCEDURE(WideLedger, Put, locals.request, locals.reply, 0);
    }

    struct ReadOne_input
    {
        uint64 key;
    };

    struct ReadOne_output {};

    struct ReadOne_locals
    {
        WideLedger::Get_input query;
        WideLedger::Get_output answer;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(ReadOne)
    {
        locals.query.key = input.key;
        CALL_OTHER_CONTRACT_FUNCTION(WideLedger, Get, locals.query, locals.answer);
        // Only the value member is used here; present and population still crossed the call.
        state.mut().valueOnly = locals.answer.value;
        state.mut().presentCount += locals.answer.present;
        state.mut().populationSum += locals.answer.population;
        state.mut().reads++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 valueOnly;
        uint64 presentCount;
        uint64 populationSum;
        uint64 reads;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.valueOnly = state.get().valueOnly;
        output.presentCount = state.get().presentCount;
        output.populationSum = state.get().populationSum;
        output.reads = state.get().reads;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Seed, 1);
        REGISTER_USER_PROCEDURE(ReadOne, 2);
    }
};
