// CalleeInvokedWithReward — ported from test/libsolidity/semanticTests/functionCall/external_call_value.sol
// Stresses: a reward attached to a cross-contract invocation
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=absent placement=first stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CalleeInvokedWithReward2
{
};

struct CalleeInvokedWithReward : public ContractBase
{
    struct StateData
    {
        sint64 ownReward;
        uint64 seen;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 seen;
        sint64 ownReward;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Pay_input
    {
        uint64 amount;
        uint64 unused;
        uint64 alsoUnused;
    };

    struct Pay_output {};

    struct Pay_locals
    {
        Pay_input forwardedInput;
        Pay_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Pay)
    {
        locals.forwardedInput = input;
        CALL(PayBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.seen = state.get().seen;
        output.ownReward = state.get().ownReward;
    }

    using PayBody_input = Pay_input;

    using PayBody_output = Pay_output;

    struct PayBody_locals
    {
        RewardLedger::Touch_input request;
        RewardLedger::Touch_output reply;
        sint64 reward;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(PayBody)
    {
        locals.reward = qpi.invocationReward();
        state.mut().ownReward += locals.reward;
        locals.request.amount = input.amount;
        INVOKE_OTHER_CONTRACT_PROCEDURE(RewardLedger, Touch, locals.request, locals.reply, 1000);
        state.mut().seen = locals.reply.seen;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Pay, 1);
    }
};
