// CalleeIndexMaskedAcrossBoundary — ported from test/libsolidity/semanticTests/functionCall/external_call_array_index.sol
// Stresses: index masking inside the callee against a bounds check in the caller
// Port caveat: an out-of-range index masks rather than reverting
// Variant: entryOrder=reversed entryShape=direct initStyle=empty placement=nested stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CalleeIndexMaskedAcrossBoundary2
{
};

struct CalleeIndexMaskedAcrossBoundary : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 forwarded;
        uint64 refusedByCaller;
        uint64 lastSlotAsked;
        uint64 lastBalance;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Deposit_input
    {
        uint64 slot;
        uint64 amount;
    };

    struct Deposit_output
    {
        uint64 ok;
    };

    struct Deposit_locals
    {
        MaskVault::Deposit_input request;
        MaskVault::Deposit_output reply;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Deposit)
    {
        state.mut().inner.lastSlotAsked = input.slot;
        if (input.slot >= 8)
        {
        state.mut().inner.refusedByCaller++;
        output.ok = 0;
        return;
        }
        locals.request.slot = input.slot;
        locals.request.amount = input.amount;
        INVOKE_OTHER_CONTRACT_PROCEDURE(MaskVault, Deposit, locals.request, locals.reply, 0);
        state.mut().inner.lastBalance = locals.reply.newBalance;
        state.mut().inner.forwarded++;
        output.ok = 1;
    }

    struct DepositUnchecked_input
    {
        uint64 slot;
        uint64 amount;
    };

    struct DepositUnchecked_output
    {
        uint64 balance;
    };

    struct DepositUnchecked_locals
    {
        MaskVault::Deposit_input request;
        MaskVault::Deposit_output reply;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(DepositUnchecked)
    {
        locals.request.slot = input.slot;
        locals.request.amount = input.amount;
        INVOKE_OTHER_CONTRACT_PROCEDURE(MaskVault, Deposit, locals.request, locals.reply, 0);
        state.mut().inner.lastBalance = locals.reply.newBalance;
        state.mut().inner.forwarded++;
        output.balance = locals.reply.newBalance;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 forwarded;
        uint64 refusedByCaller;
        uint64 lastSlotAsked;
        uint64 lastBalance;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.forwarded = state.get().inner.forwarded;
        output.refusedByCaller = state.get().inner.refusedByCaller;
        output.lastSlotAsked = state.get().inner.lastSlotAsked;
        output.lastBalance = state.get().inner.lastBalance;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Deposit, 1);
        REGISTER_USER_PROCEDURE(DepositUnchecked, 2);
    }

    INITIALIZE()
    {

    }
};
