// CalleeResultFeedsSecondCall — ported from test/libsolidity/semanticTests/functionCall/external_call_chain.sol
// Stresses: two calls where the second's argument is computed from the first's return — the reply buffer is read, transformed and written back into the request in the same scope
// Port caveat: The two calls sit in separate blocks: the plain macro declares its own error variable, and two in one scope collide.
// Variant: entryOrder=declared entryShape=direct initStyle=empty placement=first stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CalleeResultFeedsSecondCall2
{
};

struct CalleeResultFeedsSecondCall : public ContractBase
{
    struct StateData
    {
        uint64 calls;
        uint64 chained;
        uint64 secondSum;
        uint64 firstSum;
        uint64 placementGuard;
    };

    struct Chain_input
    {
        uint64 seed;
    };

    struct Chain_output {};

    struct Chain_locals
    {
        EchoThree::Accept_input request;
        EchoThree::Accept_output reply;
        uint64 i;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Chain)
    {
        locals.request.amount = input.seed;
        locals.request.tag = 1;
        locals.request.flag = 0;
        locals.request.who = SELF;
        for (locals.i = 0; locals.i < 4; locals.i++)
        {
        locals.request.values.set(locals.i, input.seed + locals.i);
        }
        {
        INVOKE_OTHER_CONTRACT_PROCEDURE(EchoThree, Accept, locals.request, locals.reply, 0);
        state.mut().firstSum = locals.reply.sum;
        }
        locals.request.amount = locals.reply.sum;
        locals.request.tag = 2;
        for (locals.i = 0; locals.i < 4; locals.i++)
        {
        locals.request.values.set(locals.i, locals.reply.sum + locals.i);
        }
        {
        INVOKE_OTHER_CONTRACT_PROCEDURE(EchoThree, Accept, locals.request, locals.reply, 0);
        state.mut().secondSum = locals.reply.sum;
        }
        state.mut().chained = state.get().secondSum - state.get().firstSum;
        state.mut().calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 firstSum;
        uint64 secondSum;
        uint64 chained;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.firstSum = state.get().firstSum;
        output.secondSum = state.get().secondSum;
        output.chained = state.get().chained;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Chain, 1);
    }

    INITIALIZE()
    {

    }
};
