// CalleeOutputPartiallySet — ported from test/libsolidity/semanticTests/functionCall/multiple_return_values.sol
// Stresses: unwritten callee output fields
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=absent placement=first stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CalleeOutputPartiallySet2
{
};

struct CalleeOutputPartiallySet : public ContractBase
{
    struct StateData
    {
        uint64 third;
        uint64 second;
        uint64 first;
        uint64 placementGuard;
    };

    struct Fetch_input
    {
        uint64 which;
        uint64 unused;
        uint64 alsoUnused;
    };

    struct Fetch_output {};

    struct Fetch_locals
    {
        Fetch_input forwardedInput;
        Fetch_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Fetch)
    {
        locals.forwardedInput = input;
        CALL(FetchBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 first;
        uint64 second;
        uint64 third;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using FetchBody_input = Fetch_input;

    using FetchBody_output = Fetch_output;

    struct FetchBody_locals
    {
        PartialLedger::Partial_input query;
        PartialLedger::Partial_output answer;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(FetchBody)
    {
        locals.query.which = input.which;
        CALL_OTHER_CONTRACT_FUNCTION(PartialLedger, Partial, locals.query, locals.answer);
        state.mut().first = locals.answer.first;
        state.mut().second = locals.answer.second;
        state.mut().third = locals.answer.third;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.first = state.get().first;
        output.second = state.get().second;
        output.third = state.get().third;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Fetch, 1);
    }
};
