// CallerStateUnchangedByCallee — ported from test/libsolidity/semanticTests/functionCall/external_call.sol
// Stresses: a caller that hands everything to the callee and keeps only a counter — the negative control for the pair comparison, where all the movement must be on the callee's side
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=empty placement=last stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CallerStateUnchangedByCallee2
{
};

struct CallerStateUnchangedByCallee : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        uint64 canary;
        uint64 calls;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 calls;
        uint64 canary;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Push_input
    {
        uint64 amount;
    };

    struct Push_output {};

    struct Push_locals
    {
        Push_input forwardedInput;
        Push_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Push)
    {
        locals.forwardedInput = input;
        CALL(PushBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.calls = state.get().calls;
        output.canary = state.get().canary;
    }

    using PushBody_input = Push_input;

    using PushBody_output = Push_output;

    struct PushBody_locals
    {
        EchoTwelve::Accept_input request;
        EchoTwelve::Accept_output reply;
        uint64 i;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(PushBody)
    {
        locals.request.amount = input.amount;
        locals.request.tag = (uint32)input.amount;
        locals.request.flag = 0;
        locals.request.who = qpi.invocator();
        for (locals.i = 0; locals.i < 4; locals.i++)
        {
        locals.request.values.set(locals.i, input.amount + locals.i);
        }
        INVOKE_OTHER_CONTRACT_PROCEDURE(EchoTwelve, Accept, locals.request, locals.reply, 0);
        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Push, 1);
    }

    INITIALIZE()
    {

    }
};
