// CalleeOutputPartiallySet — ported from test/libsolidity/semanticTests/functionCall/multiple_return_values.sol
// Stresses: unwritten callee output fields
// Variant: placement=last
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CalleeOutputPartiallySet2
{
};

struct CalleeOutputPartiallySet : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        uint64 first;
        uint64 second;
        uint64 third;
    };

    struct Fetch_input
    {
        uint64 which;
        uint64 unused;
        uint64 alsoUnused;
    };

    struct Fetch_output {};

    struct Fetch_locals
    {
        PartialLedger::Partial_input query;
        PartialLedger::Partial_output answer;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Fetch)
    {
        locals.query.which = input.which;
        CALL_OTHER_CONTRACT_FUNCTION(PartialLedger, Partial, locals.query, locals.answer);
        state.mut().first = locals.answer.first;
        state.mut().second = locals.answer.second;
        state.mut().third = locals.answer.third;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 first;
        uint64 second;
        uint64 third;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.first = state.get().first;
        output.second = state.get().second;
        output.third = state.get().third;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Fetch, 1);
    }

    INITIALIZE()
    {
        state.mut().first = 0;
        state.mut().second = 0;
        state.mut().third = 0;
    }
};
