// CalleeReadThenWriteSameTick — ported from test/libsolidity/semanticTests/functionCall/calling_other_functions.sol
// Stresses: read-before-write and read-after-write against one callee
// Port caveat: the second call sits in its own block so the error variables do not collide
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=absent placement=first stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CalleeReadThenWriteSameTick2
{
};

struct CalleeReadThenWriteSameTick : public ContractBase
{
    struct StateData
    {
        uint64 balanceBefore;
        uint64 balanceAfter;
        uint64 reported;
        uint64 rounds;
        uint64 placementGuard;
    };

    struct Round_input
    {
        uint64 slot;
        uint64 amount;
    };

    struct Round_output {};

    struct Round_locals
    {
        Round_input forwardedInput;
        Round_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Round)
    {
        locals.forwardedInput = input;
        CALL(RoundBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 balanceBefore;
        uint64 balanceAfter;
        uint64 reported;
        uint64 rounds;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using RoundBody_input = Round_input;

    using RoundBody_output = Round_output;

    struct RoundBody_locals
    {
        ReadWriteVault::Balance_input query;
        ReadWriteVault::Balance_output answer;
        ReadWriteVault::Deposit_input request;
        ReadWriteVault::Deposit_output reply;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RoundBody)
    {
        locals.query.slot = input.slot;
        CALL_OTHER_CONTRACT_FUNCTION(ReadWriteVault, Balance, locals.query, locals.answer);
        state.mut().balanceBefore = locals.answer.balance;
        {
        locals.request.slot = input.slot;
        locals.request.amount = input.amount;
        INVOKE_OTHER_CONTRACT_PROCEDURE(ReadWriteVault, Deposit, locals.request, locals.reply, 0);
        state.mut().reported = locals.reply.newBalance;
        }
        {
        locals.query.slot = input.slot;
        CALL_OTHER_CONTRACT_FUNCTION(ReadWriteVault, Balance, locals.query, locals.answer);
        state.mut().balanceAfter = locals.answer.balance;
        }
        state.mut().rounds++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.balanceBefore = state.get().balanceBefore;
        output.balanceAfter = state.get().balanceAfter;
        output.reported = state.get().reported;
        output.rounds = state.get().rounds;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Round, 1);
    }
};
