// EffectsAfterInteractionOrdering — ported from checks-effects-interactions
// Stresses: zero-before-pay against pay-before-zero
// Port caveat: no real re-entry is possible; the flag is the residue
// Variant: entryOrder=declared entryShape=direct initStyle=empty placement=last stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct EffectsAfterInteractionOrdering2
{
};

struct EffectsAfterInteractionOrdering : public ContractBase
{
    struct Scratch
    {
        uint64 depositScratch;
        uint64 withdrawSafeHeld;
        uint64 withdrawUnsafeHeld;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 safeBalance;
        uint64 unsafeBalance;
        uint64 observedDuringPay;
        uint64 paidSafe;
        uint64 paidUnsafe;
        Scratch scratch;
    };

    struct Deposit_input
    {
        uint64 amount;
    };

    struct Deposit_output {};

    PUBLIC_PROCEDURE(Deposit)
    {
        state.mut().safeBalance += input.amount;
        state.mut().unsafeBalance += input.amount;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 safeBalance;
        uint64 unsafeBalance;
        uint64 observedDuringPay;
        uint64 paidSafe;
        uint64 paidUnsafe;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.safeBalance = state.get().safeBalance;
        output.unsafeBalance = state.get().unsafeBalance;
        output.observedDuringPay = state.get().observedDuringPay;
        output.paidSafe = state.get().paidSafe;
        output.paidUnsafe = state.get().paidUnsafe;
    }

    struct WithdrawSafe_input
    {
        uint64 amount;
    };

    struct WithdrawSafe_output
    {
        uint64 ok;
    };

    PUBLIC_PROCEDURE(WithdrawSafe)
    {
        state.mut().scratch.withdrawSafeHeld = state.get().safeBalance;
        if (state.mut().scratch.withdrawSafeHeld < input.amount)
        {
        output.ok = 0;
        return;
        }
        state.mut().safeBalance = state.mut().scratch.withdrawSafeHeld - input.amount;
        state.mut().paidSafe += input.amount;
        output.ok = 1;
    }

    struct WithdrawUnsafe_input
    {
        uint64 amount;
    };

    struct WithdrawUnsafe_output
    {
        uint64 ok;
    };

    PUBLIC_PROCEDURE(WithdrawUnsafe)
    {
        state.mut().scratch.withdrawUnsafeHeld = state.get().unsafeBalance;
        if (state.mut().scratch.withdrawUnsafeHeld < input.amount)
        {
        output.ok = 0;
        return;
        }
        state.mut().paidUnsafe += input.amount;
        // What a re-entrant caller would read here: the balance is still the old one.
        state.mut().observedDuringPay = state.get().unsafeBalance;
        state.mut().unsafeBalance = state.mut().scratch.withdrawUnsafeHeld - input.amount;
        output.ok = 1;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Deposit, 1);
        REGISTER_USER_PROCEDURE(WithdrawSafe, 2);
        REGISTER_USER_PROCEDURE(WithdrawUnsafe, 3);
    }

    INITIALIZE()
    {

    }
};
