// HoneypotUnreachableBranch — ported from varloop honeypot
// Stresses: provably dead code next to live code
// Port caveat: unreachability is arithmetic rather than shadowing
// Variant: constSource=constexpr entryOrder=reversed entryShape=viaPrivate initStyle=empty placement=nested stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct HoneypotUnreachableBranch2
{
};

struct HoneypotUnreachableBranch : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 paid;
        uint64 refused;
        uint64 deadBranchTaken;
        uint64 calls;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Withdraw_input
    {
        uint64 amount;
    };

    struct Withdraw_output
    {
        uint64 ok;
    };

    struct Withdraw_locals
    {
        Withdraw_input forwardedInput;
        Withdraw_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Withdraw)
    {
        locals.forwardedInput = input;
        CALL(WithdrawBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 paid;
        uint64 refused;
        uint64 deadBranchTaken;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using WithdrawBody_input = Withdraw_input;

    using WithdrawBody_output = Withdraw_output;

    struct WithdrawBody_locals
    {
        uint64 doubled;
        uint64 halved;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(WithdrawBody)
    {
        state.mut().inner.calls++;
        locals.doubled = input.amount * 2;
        locals.halved = QPI::div(locals.doubled, 2ULL);
        // Unreachable for every even doubled value, which is all of them.
        if (QPI::mod(locals.doubled, 2ULL) == 1)
        {
        state.mut().inner.deadBranchTaken++;
        state.mut().inner.paid += input.amount;
        output.ok = 1;
        return;
        }
        if (locals.halved == input.amount && input.amount < 9223372036854775808ULL)
        {
        state.mut().inner.paid += QPI::div(input.amount, 2ULL);
        output.ok = 1;
        return;
        }
        state.mut().inner.refused++;
        output.ok = 0;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.paid = state.get().inner.paid;
        output.refused = state.get().inner.refused;
        output.deadBranchTaken = state.get().inner.deadBranchTaken;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Withdraw, 1);
    }

    INITIALIZE()
    {

    }
};
