// OracleMedianOfThree — ported from rekt: single-source oracle manipulation
// Stresses: a median of three prices against their mean — the median resists one manipulated feed and the mean does not, and the two are computed on the same inputs
// Variant: entryOrder=declared entryShape=direct initStyle=absent placement=first stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct OracleMedianOfThree2
{
};

struct OracleMedianOfThree : public ContractBase
{
    struct StateData
    {
        uint64 calls;
        uint64 medianResisted;
        uint64 spread;
        uint64 mean;
        uint64 median;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 median;
        uint64 mean;
        uint64 spread;
        uint64 medianResisted;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.median = state.get().median;
        output.mean = state.get().mean;
        output.spread = state.get().spread;
        output.medianResisted = state.get().medianResisted;
        output.calls = state.get().calls;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        uint64 first;
        uint64 second;
        uint64 third;
        uint64 low;
        uint64 high;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.first = 1000;
        locals.second = 1010;
        locals.third = input.a;
        locals.low = locals.first < locals.second ? locals.first : locals.second;
        locals.high = locals.first < locals.second ? locals.second : locals.first;
        if (locals.third < locals.low)
        {
        state.mut().median = locals.low;
        }
        else if (locals.third > locals.high)
        {
        state.mut().median = locals.high;
        }
        else
        {
        state.mut().median = locals.third;
        }
        state.mut().mean = QPI::div(locals.first + locals.second + locals.third, 3ULL);
        state.mut().spread = state.get().mean > state.get().median ? state.get().mean - state.get().median : state.get().median - state.get().mean;
        state.mut().medianResisted = state.get().spread > 100 ? 1 : 0;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }
};
