// UnboundedIterationCostCounter — ported from denial of service by unbounded loop (SWC-128)
// Stresses: caller-controlled trip count, bounded and counted
// Port caveat: no gas meter to run out of
// Variant: capacity=8 entryOrder=declared entryShape=viaPrivate initStyle=empty loopShape=zero placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct UnboundedIterationCostCounter2
{
};

struct UnboundedIterationCostCounter : public ContractBase
{
    struct Scratch
    {
        uint64 registerI;
        uint64 registerBounded;
        uint64 sweepI;
        uint64 sweepBounded;
        uint64 sweepTotal;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 clamped;
        uint64 workRequested;
        uint64 workDone;
        uint64 filled;
        Array<uint64, 8> entries;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 filled;
        uint64 workDone;
        uint64 workRequested;
        uint64 clamped;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Register_input
    {
        uint64 count;
    };

    struct Register_output {};

    struct Register_locals
    {
        Register_input forwardedInput;
        Register_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Register)
    {
        locals.forwardedInput = input;
        CALL(RegisterBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Sweep_input
    {
        uint64 requested;
    };

    struct Sweep_output {};

    struct Sweep_locals
    {
        Sweep_input forwardedInput;
        Sweep_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Sweep)
    {
        locals.forwardedInput = input;
        CALL(SweepBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.filled = state.get().inner.filled;
        output.workDone = state.get().inner.workDone;
        output.workRequested = state.get().inner.workRequested;
        output.clamped = state.get().inner.clamped;
    }

    using RegisterBody_input = Register_input;

    using RegisterBody_output = Register_output;

    PRIVATE_PROCEDURE(RegisterBody)
    {
        state.mut().inner.scratch.registerBounded = input.count > 8 ? 8 : input.count;
        for (state.mut().inner.scratch.registerI = 0; state.mut().inner.scratch.registerI < state.mut().inner.scratch.registerBounded; state.mut().inner.scratch.registerI++)
        {
        state.mut().inner.entries.set(state.mut().inner.scratch.registerI, state.mut().inner.scratch.registerI + 1);
        }
        state.mut().inner.filled = state.mut().inner.scratch.registerBounded;
    }

    using SweepBody_input = Sweep_input;

    using SweepBody_output = Sweep_output;

    PRIVATE_PROCEDURE(SweepBody)
    {
        state.mut().inner.workRequested += input.requested;
        state.mut().inner.scratch.sweepBounded = input.requested;
        if (state.mut().inner.scratch.sweepBounded > state.get().inner.filled)
        {
        state.mut().inner.scratch.sweepBounded = state.get().inner.filled;
        state.mut().inner.clamped++;
        }
        state.mut().inner.scratch.sweepTotal = 0;
        for (state.mut().inner.scratch.sweepI = 0; state.mut().inner.scratch.sweepI < state.mut().inner.scratch.sweepBounded; state.mut().inner.scratch.sweepI++)
        {
        state.mut().inner.scratch.sweepTotal += state.get().inner.entries.get(state.mut().inner.scratch.sweepI);
        state.mut().inner.workDone++;
        }
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Register, 1);
        REGISTER_USER_PROCEDURE(Sweep, 2);
    }

    INITIALIZE()
    {

    }
};
