// UnboundedIterationCostCounter — ported from denial of service by unbounded loop (SWC-128)
// Stresses: caller-controlled trip count, bounded and counted
// Port caveat: no gas meter to run out of
// Variant: capacity=64 entryOrder=reversed entryShape=direct initStyle=absent loopShape=clamped placement=first stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct UnboundedIterationCostCounter2
{
};

struct UnboundedIterationCostCounter : public ContractBase
{
    struct Scratch
    {
        uint64 registerI;
        uint64 registerBounded;
        uint64 sweepI;
        uint64 sweepBounded;
        uint64 sweepTotal;
    };

    struct StateData
    {
        Array<uint64, 64> entries;
        uint64 filled;
        uint64 workDone;
        uint64 workRequested;
        uint64 clamped;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Sweep_input
    {
        uint64 requested;
    };

    struct Sweep_output {};

    PUBLIC_PROCEDURE(Sweep)
    {
        state.mut().workRequested += input.requested;
        state.mut().scratch.sweepBounded = input.requested;
        if (state.mut().scratch.sweepBounded > state.get().filled)
        {
        state.mut().scratch.sweepBounded = state.get().filled;
        state.mut().clamped++;
        }
        state.mut().scratch.sweepTotal = 0;
        for (state.mut().scratch.sweepI = 0; state.mut().scratch.sweepI < state.mut().scratch.sweepBounded; state.mut().scratch.sweepI++)
        {
        state.mut().scratch.sweepTotal += state.get().entries.get(state.mut().scratch.sweepI);
        state.mut().workDone++;
        }
    }

    struct Register_input
    {
        uint64 count;
    };

    struct Register_output {};

    PUBLIC_PROCEDURE(Register)
    {
        state.mut().scratch.registerBounded = input.count > 64 ? 64 : input.count;
        for (state.mut().scratch.registerI = 0; state.mut().scratch.registerI < state.mut().scratch.registerBounded; state.mut().scratch.registerI++)
        {
        state.mut().entries.set(state.mut().scratch.registerI, state.mut().scratch.registerI + 1);
        }
        state.mut().filled = state.mut().scratch.registerBounded;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 filled;
        uint64 workDone;
        uint64 workRequested;
        uint64 clamped;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.filled = state.get().filled;
        output.workDone = state.get().workDone;
        output.workRequested = state.get().workRequested;
        output.clamped = state.get().clamped;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Register, 1);
        REGISTER_USER_PROCEDURE(Sweep, 2);
    }
};
