// UnboundedLoopBounded — ported from denial of service by unbounded loop (SWC-113/128)
// Stresses: a bounded payout loop and the entries it cannot reach
// Port caveat: no gas in QPI; the DoS becomes truncation past the capacity bound
// Variant: capacity=64 entryOrder=declared entryShape=viaPrivate initStyle=full loopShape=constant placement=last stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct UnboundedLoopBounded2
{
};

struct UnboundedLoopBounded : public ContractBase
{
    struct Scratch
    {
        uint64 registerI;
        uint64 registerBounded;
        uint64 payAllI;
        uint64 payAllTotal;
    };

    struct StateData
    {
        uint64 placementGuard;
        Array<uint64, 64> claims;
        uint64 paid;
        uint64 skipped;
        uint64 registered;
        Scratch scratch;
    };

    struct PayAll_input
    {
        uint64 unused;
    };

    struct PayAll_output {};

    struct PayAll_locals
    {
        PayAll_input forwardedInput;
        PayAll_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(PayAll)
    {
        locals.forwardedInput = input;
        CALL(PayAllBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 paid;
        uint64 skipped;
        uint64 registered;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Register_input
    {
        uint64 count;
        uint64 amount;
    };

    struct Register_output {};

    struct Register_locals
    {
        Register_input forwardedInput;
        Register_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Register)
    {
        locals.forwardedInput = input;
        CALL(RegisterBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using PayAllBody_input = PayAll_input;

    using PayAllBody_output = PayAll_output;

    PRIVATE_PROCEDURE(PayAllBody)
    {
        state.mut().scratch.payAllTotal = 0;
        for (state.mut().scratch.payAllI = 0; state.mut().scratch.payAllI < 64; state.mut().scratch.payAllI++)
        {
        state.mut().scratch.payAllTotal += state.get().claims.get(state.mut().scratch.payAllI);
        state.mut().claims.set(state.mut().scratch.payAllI, 0);
        }
        state.mut().paid += state.mut().scratch.payAllTotal;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.paid = state.get().paid;
        output.skipped = state.get().skipped;
        output.registered = state.get().registered;
    }

    using RegisterBody_input = Register_input;

    using RegisterBody_output = Register_output;

    PRIVATE_PROCEDURE(RegisterBody)
    {
        state.mut().scratch.registerBounded = input.count;
        if (state.mut().scratch.registerBounded > 64)
        {
        state.mut().skipped += state.mut().scratch.registerBounded - 64;
        state.mut().scratch.registerBounded = 64;
        }
        for (state.mut().scratch.registerI = 0; state.mut().scratch.registerI < state.mut().scratch.registerBounded; state.mut().scratch.registerI++)
        {
        state.mut().claims.set(state.mut().scratch.registerI, input.amount);
        }
        state.mut().registered += state.mut().scratch.registerBounded;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Register, 1);
        REGISTER_USER_PROCEDURE(PayAll, 2);
    }

    INITIALIZE()
    {
        state.mut().claims.setAll(0);
        state.mut().paid = 0;
        state.mut().skipped = 0;
        state.mut().registered = 0;
    }
};
