// UnboundedLoopBounded — ported from denial of service by unbounded loop (SWC-113/128)
// Stresses: a bounded payout loop and the entries it cannot reach
// Port caveat: no gas in QPI; the DoS becomes truncation past the capacity bound
// Variant: capacity=2 entryOrder=declared entryShape=viaPrivate initStyle=empty loopShape=clamped placement=last stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct UnboundedLoopBounded2
{
};

struct UnboundedLoopBounded : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        uint64 registered;
        uint64 skipped;
        uint64 paid;
        Array<uint64, 2> claims;
    };

    struct PayAll_input
    {
        uint64 unused;
    };

    struct PayAll_output {};

    struct PayAll_locals
    {
        PayAll_input forwardedInput;
        PayAll_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(PayAll)
    {
        locals.forwardedInput = input;
        CALL(PayAllBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 paid;
        uint64 skipped;
        uint64 registered;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Register_input
    {
        uint64 count;
        uint64 amount;
    };

    struct Register_output {};

    struct Register_locals
    {
        Register_input forwardedInput;
        Register_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Register)
    {
        locals.forwardedInput = input;
        CALL(RegisterBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using PayAllBody_input = PayAll_input;

    using PayAllBody_output = PayAll_output;

    struct PayAllBody_locals
    {
        uint64 i;
        uint64 total;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(PayAllBody)
    {
        locals.total = 0;
        for (locals.i = 0; locals.i < 2; locals.i++)
        {
        locals.total += state.get().claims.get(locals.i);
        state.mut().claims.set(locals.i, 0);
        }
        state.mut().paid += locals.total;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.paid = state.get().paid;
        output.skipped = state.get().skipped;
        output.registered = state.get().registered;
    }

    using RegisterBody_input = Register_input;

    using RegisterBody_output = Register_output;

    struct RegisterBody_locals
    {
        uint64 i;
        uint64 bounded;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RegisterBody)
    {
        locals.bounded = input.count;
        if (locals.bounded > 2)
        {
        state.mut().skipped += locals.bounded - 2;
        locals.bounded = 2;
        }
        for (locals.i = 0; locals.i < locals.bounded; locals.i++)
        {
        state.mut().claims.set(locals.i, input.amount);
        }
        state.mut().registered += locals.bounded;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Register, 1);
        REGISTER_USER_PROCEDURE(PayAll, 2);
    }

    INITIALIZE()
    {

    }
};
