// UninitialisedOwnerTakeover — ported from Parity multisig uninitialised owner (SWC-118)
// Stresses: a state field left out of INITIALIZE and then compared against
// Port caveat: the port asserts whatever construction leaves the field as; both backends must agree on it
// Variant: entryOrder=reversed entryShape=direct initStyle=empty placement=first stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct UninitialisedOwnerTakeover2
{
};

struct UninitialisedOwnerTakeover : public ContractBase
{
    struct Scratch
    {
        uint64 initialiseScratch;
        uint64 drainScratch;
    };

    struct StateData
    {
        uint64 vault;
        uint64 takeovers;
        id owner;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 takeovers;
        uint64 vault;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.takeovers = state.get().takeovers;
        output.vault = state.get().vault;
    }

    struct Initialise_input
    {
        uint64 unused;
    };

    struct Initialise_output
    {
        uint64 claimed;
    };

    PUBLIC_PROCEDURE(Initialise)
    {
        if (state.get().owner == NULL_ID)
        {
        state.mut().owner = qpi.invocator();
        state.mut().takeovers++;
        output.claimed = 1;
        return;
        }
        output.claimed = 0;
    }

    struct Drain_input
    {
        uint64 amount;
    };

    struct Drain_output
    {
        uint64 ok;
    };

    PUBLIC_PROCEDURE(Drain)
    {
        if (qpi.invocator() != state.get().owner)
        {
        output.ok = 0;
        return;
        }
        if (state.get().vault < input.amount)
        {
        output.ok = 0;
        return;
        }
        state.mut().vault -= input.amount;
        output.ok = 1;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Initialise, 1);
        REGISTER_USER_PROCEDURE(Drain, 2);
    }

    INITIALIZE()
    {

    }
};
