// WithdrawalQueueOrdering — ported from lido/WithdrawalQueue.sol (checkpoint ordering)
// Stresses: a withdrawal queue where the claim is priced at the *request* rate or at the *current* rate — the two differ once the rate moves, and one of them lets a claimant pick the better one
// Variant: entryOrder=reversed entryShape=direct initStyle=empty placement=first stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct WithdrawalQueueOrdering2
{
};

struct WithdrawalQueueOrdering : public ContractBase
{
    struct StateData
    {
        uint64 atRequestRate;
        uint64 atCurrentRate;
        uint64 favourable;
        uint64 difference;
        uint64 calls;
        uint64 placementGuard;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        uint64 shares;
        uint64 requestRate;
        uint64 currentRate;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.shares = input.a;
        locals.requestRate = 1000;
        locals.currentRate = QPI::mod(input.b, 2001ULL);
        state.mut().atRequestRate = QPI::div(locals.shares * locals.requestRate, 1000ULL);
        state.mut().atCurrentRate = QPI::div(locals.shares * locals.currentRate, 1000ULL);
        if (state.get().atCurrentRate > state.get().atRequestRate)
        {
        state.mut().favourable++;
        state.mut().difference = state.get().atCurrentRate - state.get().atRequestRate;
        }
        else
        {
        state.mut().difference = state.get().atRequestRate - state.get().atCurrentRate;
        }

        state.mut().calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 atRequestRate;
        uint64 atCurrentRate;
        uint64 favourable;
        uint64 difference;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.atRequestRate = state.get().atRequestRate;
        output.atCurrentRate = state.get().atCurrentRate;
        output.favourable = state.get().favourable;
        output.difference = state.get().difference;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
