// WrongInitializerNameTakeover — ported from Rubixi wrong constructor name
// Stresses: an ownership assignment reachable from an entry
// Port caveat: INITIALIZE cannot be misnamed in QPI; the misnamed twin is an ordinary entry
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=empty placement=first stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct WrongInitializerNameTakeover2
{
};

struct WrongInitializerNameTakeover : public ContractBase
{
    struct StateData
    {
        uint64 collected;
        uint64 claims;
        id owner;
        uint64 placementGuard;
    };

    struct Collect_input
    {
        uint64 amount;
    };

    struct Collect_output
    {
        uint64 ok;
    };

    struct Collect_locals
    {
        Collect_input forwardedInput;
        Collect_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Collect)
    {
        locals.forwardedInput = input;
        CALL(CollectBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct DynamicPyramid_input {};

    struct DynamicPyramid_output {};

    struct DynamicPyramid_locals
    {
        DynamicPyramid_input forwardedInput;
        DynamicPyramid_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(DynamicPyramid)
    {
        CALL(DynamicPyramidBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 claims;
        uint64 collected;
        uint64 ownerIsSelf;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using CollectBody_input = Collect_input;

    using CollectBody_output = Collect_output;

    struct CollectBody_locals
    {
        id caller;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(CollectBody)
    {
        locals.caller = qpi.invocator();
        if (!(state.get().owner == locals.caller))
        {
        output.ok = 0;
        return;
        }
        state.mut().collected += input.amount;
        output.ok = 1;
    }

    using DynamicPyramidBody_input = DynamicPyramid_input;

    using DynamicPyramidBody_output = DynamicPyramid_output;

    struct DynamicPyramidBody_locals
    {
        id caller;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(DynamicPyramidBody)
    {
        locals.caller = qpi.invocator();
        state.mut().owner = locals.caller;
        state.mut().claims++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.claims = state.get().claims;
        output.collected = state.get().collected;
        output.ownerIsSelf = state.get().owner == SELF ? 1 : 0;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(DynamicPyramid, 1);
        REGISTER_USER_PROCEDURE(Collect, 2);
    }

    INITIALIZE()
    {

    }
};
