// BitwiseAnd — ported from test/libsolidity/semanticTests/operators/bitwise.sol
// Stresses: & across widths, and the high bits a narrowing store must clear
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full placement=last stateOrder=declared temporaries=stateScratch width=sint8
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct BitwiseAnd2
{
};

struct BitwiseAnd : public ContractBase
{
    struct Scratch
    {
        sint64 applyValue;
    };

    struct StateData
    {
        uint64 placementGuard;
        sint64 wide;
        sint8 narrow;
        uint64 calls;
        Scratch scratch;
    };

    struct Apply_input
    {
        sint8 a;
        sint8 b;
    };

    struct Apply_output {};

    struct Apply_locals
    {
        Apply_input forwardedInput;
        Apply_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Apply)
    {
        locals.forwardedInput = input;
        CALL(ApplyBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        sint64 wide;
        sint8 narrow;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using ApplyBody_input = Apply_input;

    using ApplyBody_output = Apply_output;

    PRIVATE_PROCEDURE(ApplyBody)
    {
        state.mut().scratch.applyValue = input.a & input.b;
        state.mut().wide = state.mut().scratch.applyValue;
        state.mut().narrow = input.a & input.b;
        state.mut().calls++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.wide = state.get().wide;
        output.narrow = state.get().narrow;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Apply, 1);
    }

    INITIALIZE()
    {
        state.mut().wide = 0;
        state.mut().narrow = 0;
        state.mut().calls = 0;
    }
};
