// BooleanToIntegerConversions — ported from test/libsolidity/semanticTests/types/bool_conversion.sol
// Stresses: comparison results used as arithmetic — the value of `true` in a sum, and the sum of several comparisons in one expression
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=full placement=last stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct BooleanToIntegerConversions2
{
};

struct BooleanToIntegerConversions : public ContractBase
{
    struct Scratch
    {
        uint64 runFirst;
        uint64 runSecond;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 asNumber;
        uint64 sumOfFlags;
        uint64 productOfFlags;
        uint64 calls;
        Scratch scratch;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 asNumber;
        uint64 sumOfFlags;
        uint64 productOfFlags;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    PRIVATE_PROCEDURE(RunBody)
    {
        state.mut().scratch.runFirst = input.a > input.b ? 1 : 0;
        state.mut().scratch.runSecond = input.a == input.b ? 1 : 0;
        state.mut().asNumber = state.mut().scratch.runFirst;
        state.mut().sumOfFlags = state.mut().scratch.runFirst + state.mut().scratch.runSecond + (input.a < input.b ? 1 : 0);
        state.mut().productOfFlags = state.mut().scratch.runFirst * 10 + state.mut().scratch.runSecond;

        state.mut().calls++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.asNumber = state.get().asNumber;
        output.sumOfFlags = state.get().sumOfFlags;
        output.productOfFlags = state.get().productOfFlags;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().asNumber = 0;
        state.mut().sumOfFlags = 0;
        state.mut().productOfFlags = 0;
        state.mut().calls = 0;
    }
};
