// CompareLess — ported from test/libsolidity/semanticTests/operators/comparison.sol
// Stresses: signed/unsigned comparison after promotion — the case where -1 < 1 flips
// Variant: width=uint64
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CompareLess2
{
};

struct CompareLess : public ContractBase
{
    struct StateData
    {
        uint64 wide;
        uint64 narrow;
        uint64 calls;
        uint64 placementGuard;
    };

    struct Apply_input
    {
        uint64 a;
        uint64 b;
    };

    struct Apply_output {};

    struct Apply_locals
    {
        uint64 value;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Apply)
    {
        locals.value = (input.a < input.b) ? 1 : 0;
        state.mut().wide = locals.value;
        state.mut().narrow = (input.a < input.b) ? 1 : 0;
        state.mut().calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 wide;
        uint64 narrow;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.wide = state.get().wide;
        output.narrow = state.get().narrow;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Apply, 1);
    }

    INITIALIZE()
    {
        state.mut().wide = 0;
        state.mut().narrow = 0;
        state.mut().calls = 0;
    }
};
