// CompareLess — ported from test/libsolidity/semanticTests/operators/comparison.sol
// Stresses: signed/unsigned comparison after promotion — the case where -1 < 1 flips
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=full placement=nested stateOrder=reversed temporaries=stateScratch width=uint64
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CompareLess2
{
};

struct CompareLess : public ContractBase
{
    struct Scratch
    {
        uint64 applyValue;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 calls;
        uint64 narrow;
        uint64 wide;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 wide;
        uint64 narrow;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Apply_input
    {
        uint64 a;
        uint64 b;
    };

    struct Apply_output {};

    struct Apply_locals
    {
        Apply_input forwardedInput;
        Apply_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Apply)
    {
        locals.forwardedInput = input;
        CALL(ApplyBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.wide = state.get().inner.wide;
        output.narrow = state.get().inner.narrow;
        output.calls = state.get().inner.calls;
    }

    using ApplyBody_input = Apply_input;

    using ApplyBody_output = Apply_output;

    PRIVATE_PROCEDURE(ApplyBody)
    {
        state.mut().inner.scratch.applyValue = (input.a < input.b) ? 1 : 0;
        state.mut().inner.wide = state.mut().inner.scratch.applyValue;
        state.mut().inner.narrow = (input.a < input.b) ? 1 : 0;
        state.mut().inner.calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Apply, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.wide = 0;
        state.mut().inner.narrow = 0;
        state.mut().inner.calls = 0;
    }
};
