// CompoundAssignNarrowsEachStep — ported from test/libsolidity/semanticTests/cleanup/cleanup_in_compound_assign.sol
// Stresses: `x += y` on a uint8 member, repeated, where the narrowing happens on every assignment rather than once at the end — the Solidity test's own subject
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full placement=last stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CompoundAssignNarrowsEachStep2
{
};

struct CompoundAssignNarrowsEachStep : public ContractBase
{
    struct Scratch
    {
        uint8 runNarrow;
        uint64 runWide;
        uint64 runI;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 narrowResult;
        uint64 wideResult;
        uint64 wrapCount;
        uint64 calls;
        Scratch scratch;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 narrowResult;
        uint64 wideResult;
        uint64 wrapCount;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.narrowResult = state.get().narrowResult;
        output.wideResult = state.get().wideResult;
        output.wrapCount = state.get().wrapCount;
        output.calls = state.get().calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    PRIVATE_PROCEDURE(RunBody)
    {
        state.mut().scratch.runNarrow = 0;
        state.mut().scratch.runWide = 0;
        for (state.mut().scratch.runI = 0; state.mut().scratch.runI < 4; state.mut().scratch.runI++)
        {
        state.mut().scratch.runNarrow += (uint8)input.a;
        state.mut().scratch.runWide += input.a;
        }
        state.mut().narrowResult = (uint64)state.mut().scratch.runNarrow;
        state.mut().wideResult = state.mut().scratch.runWide;
        if (state.get().narrowResult != QPI::mod(state.get().wideResult, 256ULL))
        {
        state.mut().wrapCount++;
        }

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().narrowResult = 0;
        state.mut().wideResult = 0;
        state.mut().wrapCount = 0;
        state.mut().calls = 0;
    }
};
