// CompoundAssignNarrowsEachStep — ported from test/libsolidity/semanticTests/cleanup/cleanup_in_compound_assign.sol
// Stresses: `x += y` on a uint8 member, repeated, where the narrowing happens on every assignment rather than once at the end — the Solidity test's own subject
// Variant: entryOrder=reversed entryShape=direct initStyle=empty placement=nested stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CompoundAssignNarrowsEachStep2
{
};

struct CompoundAssignNarrowsEachStep : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 narrowResult;
        uint64 wideResult;
        uint64 wrapCount;
        uint64 calls;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        uint8 narrow;
        uint64 wide;
        uint64 i;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.narrow = 0;
        locals.wide = 0;
        for (locals.i = 0; locals.i < 4; locals.i++)
        {
        locals.narrow += (uint8)input.a;
        locals.wide += input.a;
        }
        state.mut().inner.narrowResult = (uint64)locals.narrow;
        state.mut().inner.wideResult = locals.wide;
        if (state.get().inner.narrowResult != QPI::mod(state.get().inner.wideResult, 256ULL))
        {
        state.mut().inner.wrapCount++;
        }

        state.mut().inner.calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 narrowResult;
        uint64 wideResult;
        uint64 wrapCount;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.narrowResult = state.get().inner.narrowResult;
        output.wideResult = state.get().inner.wideResult;
        output.wrapCount = state.get().inner.wrapCount;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
