// CompoundAssignNarrowsEachStep — ported from test/libsolidity/semanticTests/cleanup/cleanup_in_compound_assign.sol
// Stresses: `x += y` on a uint8 member, repeated, where the narrowing happens on every assignment rather than once at the end — the Solidity test's own subject
// Variant: entryOrder=declared entryShape=direct initStyle=absent placement=first stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct CompoundAssignNarrowsEachStep2
{
};

struct CompoundAssignNarrowsEachStep : public ContractBase
{
    struct Scratch
    {
        uint8 runNarrow;
        uint64 runWide;
        uint64 runI;
    };

    struct StateData
    {
        uint64 calls;
        uint64 wrapCount;
        uint64 wideResult;
        uint64 narrowResult;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 narrowResult;
        uint64 wideResult;
        uint64 wrapCount;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.narrowResult = state.get().narrowResult;
        output.wideResult = state.get().wideResult;
        output.wrapCount = state.get().wrapCount;
        output.calls = state.get().calls;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    PUBLIC_PROCEDURE(Run)
    {
        state.mut().scratch.runNarrow = 0;
        state.mut().scratch.runWide = 0;
        for (state.mut().scratch.runI = 0; state.mut().scratch.runI < 4; state.mut().scratch.runI++)
        {
        state.mut().scratch.runNarrow += (uint8)input.a;
        state.mut().scratch.runWide += input.a;
        }
        state.mut().narrowResult = (uint64)state.mut().scratch.runNarrow;
        state.mut().wideResult = state.mut().scratch.runWide;
        if (state.get().narrowResult != QPI::mod(state.get().wideResult, 256ULL))
        {
        state.mut().wrapCount++;
        }

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }
};
