// ConstexprFoldVsRuntime — ported from test/libsolidity/semanticTests/constantEvaluator/rounding.sol
// Stresses: the same expression constant-folded and computed at runtime — a fold that disagrees with the emitted code is silent
// Variant: entryOrder=declared entryShape=direct initStyle=empty placement=last stateOrder=reversed temporaries=locals width=sint16
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct ConstexprFoldVsRuntime2
{
};

struct ConstexprFoldVsRuntime : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        uint64 agree;
        sint16 computed;
        sint16 folded;
        uint64 calls;
        uint64 accumulator;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 accumulator;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.accumulator = state.get().accumulator;
        output.calls = state.get().calls;
    }

    struct Run_input
    {
        sint16 a;
        sint16 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        sint16 scratch;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        state.mut().folded = (sint16)(32767 + 3);
        locals.scratch = input.a + input.b;
        state.mut().computed = locals.scratch;
        state.mut().agree = (state.get().folded == state.get().computed) ? 1 : 0;
        state.mut().accumulator += state.get().agree;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
