// DateDaysInMonthLadder — ported from test/libsolidity/semanticTests/various/date_time.sol (calendar table lookup)
// Stresses: the month-length table, its February leap-year special case, and the out-of-range guard that returns 0 rather than indexing the array
// Port caveat: The local lookup table shadows the function's own name, so this also exercises the name-resolution path that produced nine findings in earlier rounds.
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full placement=last stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct DateDaysInMonthLadder2
{
};

struct DateDaysInMonthLadder : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        uint64 calls;
        uint64 days;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 days;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.days = state.get().days;
        output.calls = state.get().calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    struct RunBody_locals
    {
        DateAndTime moment;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RunBody)
    {
        state.mut().days = DateAndTime::daysInMonth(input.a, input.b);
        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().days = 0;
        state.mut().calls = 0;
    }
};
