// ExplicitCastChainThroughSigned — ported from test/libsolidity/semanticTests/conversions/explicit_conversion_chain.sol
// Stresses: uint64 to sint32 to uint16 to sint64 — a chain where each hop can change the sign and the width, and only the final value tells whether every hop was applied
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=empty placement=last stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct ExplicitCastChainThroughSigned2
{
};

struct ExplicitCastChainThroughSigned : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        sint64 chained;
        sint64 direct;
        uint64 differences;
        uint64 calls;
    };

    struct Read_input {};

    struct Read_output
    {
        sint64 chained;
        sint64 direct;
        uint64 differences;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.chained = state.get().chained;
        output.direct = state.get().direct;
        output.differences = state.get().differences;
        output.calls = state.get().calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    struct RunBody_locals
    {
        sint32 asSigned;
        uint16 asWord;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RunBody)
    {
        locals.asSigned = (sint32)input.a;
        locals.asWord = (uint16)locals.asSigned;
        state.mut().chained = (sint64)locals.asWord;
        state.mut().direct = (sint64)(uint16)input.a;
        if (state.get().chained != state.get().direct)
        {
        state.mut().differences++;
        }

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
