// FibonacciIterativeWrap — ported from test/libsolidity/semanticTests/arithmetics/fibonacci.sol
// Stresses: an iterative Fibonacci to a caller-chosen index, where the 94th term is the last that fits — a two-variable rotation the compiler may reorder
// Variant: base
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct FibonacciIterativeWrap2
{
};

struct FibonacciIterativeWrap : public ContractBase
{
    struct StateData
    {
        uint64 value;
        uint64 previous;
        uint64 index;
        uint64 wrapped;
        uint64 calls;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 value;
        uint64 previous;
        uint64 index;
        uint64 wrapped;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.value = state.get().value;
        output.previous = state.get().previous;
        output.index = state.get().index;
        output.wrapped = state.get().wrapped;
        output.calls = state.get().calls;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        uint64 i;
        uint64 bounded;
        uint64 a;
        uint64 b;
        uint64 next;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.bounded = input.a > 100 ? 100 : input.a;
        locals.a = 0;
        locals.b = 1;
        for (locals.i = 0; locals.i < locals.bounded; locals.i++)
        {
        locals.next = locals.a + locals.b;
        if (locals.next < locals.b)
        {
        state.mut().wrapped = 1;
        }
        locals.a = locals.b;
        locals.b = locals.next;
        }
        state.mut().value = locals.a;
        state.mut().previous = locals.b;
        state.mut().index = locals.bounded;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().value = 0;
        state.mut().previous = 0;
        state.mut().index = 0;
        state.mut().wrapped = 0;
        state.mut().calls = 0;
    }
};
