// IncrementWrapAtMax — ported from test/libsolidity/semanticTests/arithmetics/checked_inc_dec.sol
// Stresses: ++ at the type's maximum and -- at its minimum, both wrapping
// Port caveat: Solidity 0.8 reverts on both; QPI wraps.
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=absent placement=nested stateOrder=declared temporaries=stateScratch width=uint64
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct IncrementWrapAtMax2
{
};

struct IncrementWrapAtMax : public ContractBase
{
    struct Scratch
    {
        uint64 runI;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 accumulator;
        uint64 calls;
        uint64 up;
        uint64 down;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Run_input
    {
        uint8 rounds;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 accumulator;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    PRIVATE_PROCEDURE(RunBody)
    {
        for (state.mut().inner.scratch.runI = 0; state.mut().inner.scratch.runI < input.rounds; state.mut().inner.scratch.runI++)
        {
        state.mut().inner.up++;
        state.mut().inner.down--;
        }
        state.mut().inner.accumulator = (uint64)state.get().inner.up;

        state.mut().inner.calls++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.accumulator = state.get().inner.accumulator;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }
};
