// K12OfComputedExpression — ported from OpenZeppelin utils/cryptography/MerkleProof.sol (hashing a computed value)
// Stresses: qpi.K12 applied to an expression rather than a named variable — the same value through a local is the control
// Port caveat: The two spellings are the same 8 bytes by C++ rules, so any difference between them is a backend defect rather than a port artefact.
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=absent placement=nested stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct K12OfComputedExpression2
{
};

struct K12OfComputedExpression : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 agree;
        id ofExpression;
        id ofLocal;
        uint64 calls;
        uint64 accumulator;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 accumulator;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    struct RunBody_locals
    {
        uint64 sum;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RunBody)
    {
        locals.sum = input.a + input.b;
        state.mut().inner.ofLocal = qpi.K12(locals.sum);
        state.mut().inner.ofExpression = qpi.K12(input.a + input.b);
        state.mut().inner.agree = (state.get().inner.ofLocal == state.get().inner.ofExpression) ? 1 : 0;
        state.mut().inner.accumulator = state.get().inner.agree;

        state.mut().inner.calls++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.accumulator = state.get().inner.accumulator;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }
};
