// K12OfComputedExpression — ported from OpenZeppelin utils/cryptography/MerkleProof.sol (hashing a computed value)
// Stresses: qpi.K12 applied to an expression rather than a named variable — the same value through a local is the control
// Port caveat: The two spellings are the same 8 bytes by C++ rules, so any difference between them is a backend defect rather than a port artefact.
// Variant: placement=last temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct K12OfComputedExpression2
{
};

struct K12OfComputedExpression : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        uint64 accumulator;
        uint64 calls;
        id ofLocal;
        id ofExpression;
        uint64 agree;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 accumulator;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.accumulator = state.get().accumulator;
        output.calls = state.get().calls;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        uint64 sum;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.sum = input.a + input.b;
        state.mut().ofLocal = qpi.K12(locals.sum);
        state.mut().ofExpression = qpi.K12(input.a + input.b);
        state.mut().agree = (state.get().ofLocal == state.get().ofExpression) ? 1 : 0;
        state.mut().accumulator = state.get().agree;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().accumulator = 0;
        state.mut().calls = 0;
    }
};
