// MathAverageNoOverflow — ported from OpenZeppelin utils/math/Math.sol (`average`)
// Stresses: the overflow-free average `(a & b) + ((a ^ b) >> 1)` beside the naive `(a + b) / 2` — they must agree except where the naive one wraps
// Port caveat: Solidity's `/` becomes QPI::div; the clever form is the point and the naive one is the control.
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full placement=last stateOrder=declared temporaries=locals width=sint16
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct MathAverageNoOverflow2
{
};

struct MathAverageNoOverflow : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        uint64 accumulator;
        uint64 calls;
        sint16 clever;
        sint16 naive;
        uint64 disagreements;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 accumulator;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        sint16 a;
        sint16 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.accumulator = state.get().accumulator;
        output.calls = state.get().calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    struct RunBody_locals
    {
        sint16 left;
        sint16 right;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RunBody)
    {
        locals.left = (input.a & input.b) + ((input.a ^ input.b) >> 1);
        locals.right = QPI::div((sint16)(input.a + input.b), (sint16)2);
        state.mut().clever = locals.left;
        state.mut().naive = locals.right;
        if (locals.left != locals.right)
        {
        state.mut().disagreements++;
        }
        state.mut().accumulator = (uint64)locals.left;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().accumulator = 0;
        state.mut().calls = 0;
    }
};
