// MathSafeCastDowncastLadder — ported from OpenZeppelin utils/math/SafeCast.sol
// Stresses: a uint64 → uint32 → uint16 → uint8 ladder with a range check before each step, driven at every boundary and one past it
// Port caveat: OpenZeppelin reverts on a failed check; QPI has no revert, so the port returns an ok-flag and — deliberately — leaves the earlier writes in place.
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=absent placement=first stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct MathSafeCastDowncastLadder2
{
};

struct MathSafeCastDowncastLadder : public ContractBase
{
    struct Scratch
    {
        uint64 runScratch;
    };

    struct StateData
    {
        uint64 rejected;
        uint8 as8;
        uint16 as16;
        uint32 as32;
        uint64 calls;
        uint64 accumulator;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Run_input
    {
        uint64 value;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 accumulator;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    PRIVATE_PROCEDURE(RunBody)
    {
        state.mut().rejected = 0;
        if (input.value > 4294967295)
        {
        state.mut().rejected++;
        }
        else
        {
        state.mut().as32 = (uint32)input.value;
        }
        if (input.value > 65535)
        {
        state.mut().rejected++;
        }
        else
        {
        state.mut().as16 = (uint16)input.value;
        }
        if (input.value > 255)
        {
        state.mut().rejected++;
        }
        else
        {
        state.mut().as8 = (uint8)input.value;
        }
        state.mut().scratch.runScratch = (uint64)state.get().as32 + (uint64)state.get().as16 + (uint64)state.get().as8;
        state.mut().accumulator = state.mut().scratch.runScratch;

        state.mut().calls++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.accumulator = state.get().accumulator;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }
};
