// MathAbsViaSignMask — ported from OpenZeppelin utils/math/SignedMath.sol (`abs`)
// Stresses: `mask = n >> 63; abs = (n + mask) ^ mask` — an arithmetic shift on the sign bit, then a signed-to-unsigned reinterpretation, exercised at INT64_MIN where the result is not representable
// Port caveat: OpenZeppelin shifts by 255 for int256; the port shifts by 63 for sint64.
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=empty placement=nested stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct MathAbsViaSignMask2
{
};

struct MathAbsViaSignMask : public ContractBase
{
    struct Scratch
    {
        sint64 runMask;
        uint64 runMasked;
        uint64 runBranched;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 accumulator;
        uint64 calls;
        uint64 viaMask;
        uint64 viaBranch;
        uint64 disagreements;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 accumulator;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        sint64 value;
        sint64 unused;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.accumulator = state.get().inner.accumulator;
        output.calls = state.get().inner.calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    PRIVATE_PROCEDURE(RunBody)
    {
        state.mut().inner.scratch.runMask = input.value >> 63;
        state.mut().inner.scratch.runMasked = (uint64)((input.value + state.mut().inner.scratch.runMask) ^ state.mut().inner.scratch.runMask);
        if (input.value < 0)
        {
        state.mut().inner.scratch.runBranched = (uint64)(0 - input.value);
        }
        else
        {
        state.mut().inner.scratch.runBranched = (uint64)input.value;
        }
        state.mut().inner.viaMask = state.mut().inner.scratch.runMasked;
        state.mut().inner.viaBranch = state.mut().inner.scratch.runBranched;
        if (state.mut().inner.scratch.runMasked != state.mut().inner.scratch.runBranched)
        {
        state.mut().inner.disagreements++;
        }
        state.mut().inner.accumulator = state.mut().inner.scratch.runMasked;

        state.mut().inner.calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
