// MinMaxWithoutBranches — ported from openzeppelin-contracts/contracts/utils/math/Math.sol (min, max)
// Stresses: branchless min and max built from a comparison and a multiply, checked against the branching spelling on the same operands
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=full placement=first stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct MinMaxWithoutBranches2
{
};

struct MinMaxWithoutBranches : public ContractBase
{
    struct StateData
    {
        uint64 calls;
        uint64 disagreements;
        uint64 minBranching;
        uint64 maxBranchless;
        uint64 minBranchless;
        uint64 placementGuard;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 minBranchless;
        uint64 maxBranchless;
        uint64 minBranching;
        uint64 disagreements;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    struct RunBody_locals
    {
        uint64 flag;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RunBody)
    {
        locals.flag = input.a < input.b ? 1 : 0;
        state.mut().minBranchless = locals.flag * input.a + (1 - locals.flag) * input.b;
        state.mut().maxBranchless = locals.flag * input.b + (1 - locals.flag) * input.a;
        if (input.a < input.b)
        {
        state.mut().minBranching = input.a;
        }
        else
        {
        state.mut().minBranching = input.b;
        }
        if (state.get().minBranchless != state.get().minBranching)
        {
        state.mut().disagreements++;
        }

        state.mut().calls++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.minBranchless = state.get().minBranchless;
        output.maxBranchless = state.get().maxBranchless;
        output.minBranching = state.get().minBranching;
        output.disagreements = state.get().disagreements;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().minBranchless = 0;
        state.mut().maxBranchless = 0;
        state.mut().minBranching = 0;
        state.mut().disagreements = 0;
        state.mut().calls = 0;
    }
};
