// NegateUnsignedMinimum — ported from test/libsolidity/semanticTests/arithmetics/unary_operators.sol
// Stresses: 0 - x on an unsigned type
// Port caveat: Solidity rejects unary minus on unsigned; `0 - x` is the equivalent wrap.
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=absent placement=first stateOrder=reversed temporaries=locals width=sint64
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct NegateUnsignedMinimum2
{
};

struct NegateUnsignedMinimum : public ContractBase
{
    struct StateData
    {
        uint64 widened;
        sint64 negated;
        uint64 placementGuard;
    };

    struct Negate_input
    {
        sint64 value;
    };

    struct Negate_output {};

    struct Negate_locals
    {
        Negate_input forwardedInput;
        Negate_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Negate)
    {
        locals.forwardedInput = input;
        CALL(NegateBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        sint64 negated;
        uint64 widened;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using NegateBody_input = Negate_input;

    using NegateBody_output = Negate_output;

    struct NegateBody_locals
    {
        sint64 scratch;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(NegateBody)
    {
        locals.scratch = (sint64)0 - input.value;
        state.mut().negated = locals.scratch;
        state.mut().widened = (uint64)locals.scratch;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.negated = state.get().negated;
        output.widened = state.get().widened;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Negate, 1);
    }
};
