// PromoteMul — ported from test/libsolidity/semanticTests/arithmetics/checked_mul.sol
// Stresses: overflow wrap and promotion on *; the narrow field truncates a product the wide field keeps
// Port caveat: Solidity reverts on overflow; QPI wraps.
// Variant: entryOrder=declared entryShape=direct initStyle=full placement=nested stateOrder=reversed temporaries=stateScratch width=uint64
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct PromoteMul2
{
};

struct PromoteMul : public ContractBase
{
    struct Scratch
    {
        uint64 applyValue;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 calls;
        uint64 narrow;
        uint64 wide;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Apply_input
    {
        uint64 a;
        uint64 b;
    };

    struct Apply_output {};

    PUBLIC_PROCEDURE(Apply)
    {
        state.mut().inner.scratch.applyValue = input.a * input.b;
        state.mut().inner.wide = state.mut().inner.scratch.applyValue;
        state.mut().inner.narrow = input.a * input.b;
        state.mut().inner.calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 wide;
        uint64 narrow;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.wide = state.get().inner.wide;
        output.narrow = state.get().inner.narrow;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Apply, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.wide = 0;
        state.mut().inner.narrow = 0;
        state.mut().inner.calls = 0;
    }
};
