// PromoteSub — ported from test/libsolidity/semanticTests/arithmetics/checked_sub.sol
// Stresses: underflow wrap and promotion on -
// Port caveat: Solidity reverts on underflow; QPI wraps.
// Variant: entryOrder=declared entryShape=direct initStyle=absent placement=first stateOrder=declared temporaries=stateScratch width=sint8
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct PromoteSub2
{
};

struct PromoteSub : public ContractBase
{
    struct Scratch
    {
        sint64 applyValue;
    };

    struct StateData
    {
        sint64 wide;
        sint8 narrow;
        uint64 calls;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Apply_input
    {
        sint8 a;
        sint8 b;
    };

    struct Apply_output {};

    PUBLIC_PROCEDURE(Apply)
    {
        state.mut().scratch.applyValue = input.a - input.b;
        state.mut().wide = state.mut().scratch.applyValue;
        state.mut().narrow = input.a - input.b;
        state.mut().calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        sint64 wide;
        sint8 narrow;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.wide = state.get().wide;
        output.narrow = state.get().narrow;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Apply, 1);
    }
};
