// ShiftLeftUnsigned — ported from test/libsolidity/semanticTests/operators/shifts/shift_left.sol
// Stresses: left shift across every width, including counts equal to and beyond the operand width
// Port caveat: Solidity defines a shift by any count; C++ leaves count >= width undefined, so a disagreement at the boundary is signal, not a port error.
// Variant: width=uint32
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct ShiftLeftUnsigned2
{
};

struct ShiftLeftUnsigned : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 wide;
        uint32 narrow;
        uint64 applied;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 wide;
        uint32 narrow;
        uint64 applied;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.wide = state.get().inner.wide;
        output.narrow = state.get().inner.narrow;
        output.applied = state.get().inner.applied;
    }

    struct Shift_input
    {
        uint32 value;
        uint8 count;
    };

    struct Shift_output {};

    struct Shift_locals
    {
        uint32 shifted;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Shift)
    {
        locals.shifted = input.value << input.count;
        state.mut().inner.narrow = locals.shifted;
        state.mut().inner.wide = (uint64)locals.shifted;
        state.mut().inner.applied++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Shift, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.wide = 0;
        state.mut().inner.narrow = 0;
        state.mut().inner.applied = 0;
    }
};
