// ShiftCountFromState — ported from test/libsolidity/semanticTests/operators/shifts/shift_underflow_negative_rvalue.sol
// Stresses: an unfoldable shift count
// Variant: entryOrder=reversed entryShape=direct initStyle=empty placement=last stateOrder=reversed temporaries=locals width=uint8
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct ShiftCountFromState2
{
};

struct ShiftCountFromState : public ContractBase
{
    struct StateData
    {
        uint64 placementGuard;
        uint64 witness;
        uint8 value;
        uint8 count;
    };

    struct SetCount_input
    {
        uint8 count;
    };

    struct SetCount_output {};

    struct SetCount_locals
    {
        uint64 scratch;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(SetCount)
    {
        state.mut().count = input.count;
    }

    struct Read_input {};

    struct Read_output
    {
        uint8 value;
        uint64 witness;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.value = state.get().value;
        output.witness = state.get().witness;
    }

    struct Apply_input
    {
        uint8 value;
    };

    struct Apply_output {};

    struct Apply_locals
    {
        uint8 shifted;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Apply)
    {
        locals.shifted = input.value << state.get().count;
        state.mut().value = locals.shifted;
        locals.shifted = input.value >> state.get().count;
        state.mut().witness = (uint64)locals.shifted;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(SetCount, 1);
        REGISTER_USER_PROCEDURE(Apply, 2);
    }

    INITIALIZE()
    {

    }
};
