// ShiftRightSignedArithmetic — ported from test/libsolidity/semanticTests/operators/shifts/shift_right_negative_lvalue_int8.sol
// Stresses: arithmetic vs logical right shift on a negative operand — the sign bit must propagate
// Variant: width=sint32
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct ShiftRightSignedArithmetic2
{
};

struct ShiftRightSignedArithmetic : public ContractBase
{
    struct StateData
    {
        sint64 wide;
        sint32 narrow;
        uint64 applied;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        sint64 wide;
        sint32 narrow;
        uint64 applied;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.wide = state.get().wide;
        output.narrow = state.get().narrow;
        output.applied = state.get().applied;
    }

    struct Shift_input
    {
        sint32 value;
        uint8 count;
    };

    struct Shift_output {};

    struct Shift_locals
    {
        sint32 shifted;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Shift)
    {
        locals.shifted = input.value >> input.count;
        state.mut().narrow = locals.shifted;
        state.mut().wide = (sint64)locals.shifted;
        state.mut().applied++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Shift, 1);
    }

    INITIALIZE()
    {
        state.mut().wide = 0;
        state.mut().narrow = 0;
        state.mut().applied = 0;
    }
};
