// ShiftByWidthAndBeyond — ported from test/libsolidity/semanticTests/operators/shifts/shift_overflow.sol
// Stresses: a shift count equal to and greater than the operand width — undefined in C++, defined in Solidity
// Port caveat: Solidity defines `x << n` for every n; C++ leaves n >= width undefined, so a backend disagreement here is expected signal, not a port error.
// Variant: entryOrder=reversed entryShape=direct initStyle=empty placement=first stateOrder=declared temporaries=stateScratch width=uint16
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct ShiftByWidthAndBeyond2
{
};

struct ShiftByWidthAndBeyond : public ContractBase
{
    struct Scratch
    {
        uint16 runScratch;
    };

    struct StateData
    {
        uint64 accumulator;
        uint64 calls;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Run_input
    {
        uint16 value;
        uint8 amount;
    };

    struct Run_output {};

    PUBLIC_PROCEDURE(Run)
    {
        state.mut().scratch.runScratch = input.value << input.amount;
        state.mut().accumulator += (uint64)state.mut().scratch.runScratch;
        state.mut().scratch.runScratch = input.value >> input.amount;
        state.mut().accumulator += (uint64)state.mut().scratch.runScratch;

        state.mut().calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 accumulator;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.accumulator = state.get().accumulator;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
