// ShiftCleanupChain — ported from operators/shifts/shift_cleanup.sol
// Stresses: compound shift chain on a narrow field
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full placement=nested stateOrder=reversed temporaries=stateScratch width=uint8
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct ShiftCleanupChain2
{
};

struct ShiftCleanupChain : public ContractBase
{
    struct Scratch
    {
        uint64 chainScratch;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 witness;
        uint8 value;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Chain_input
    {
        uint8 seed;
        uint8 addend;
    };

    struct Chain_output {};

    struct Chain_locals
    {
        Chain_input forwardedInput;
        Chain_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Chain)
    {
        locals.forwardedInput = input;
        CALL(ChainBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint8 value;
        uint64 witness;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using ChainBody_input = Chain_input;

    using ChainBody_output = Chain_output;

    PRIVATE_PROCEDURE(ChainBody)
    {
        state.mut().inner.value = input.seed;
        state.mut().inner.value += input.addend;
        state.mut().inner.value <<= 8;
        state.mut().inner.value >>= 16;
        state.mut().inner.scratch.chainScratch = (uint64)state.get().inner.value;
        state.mut().inner.witness = state.mut().inner.scratch.chainScratch;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.value = state.get().inner.value;
        output.witness = state.get().inner.witness;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Chain, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.value = 0;
        state.mut().inner.witness = 0;
    }
};
