// ShiftRhsWiderThanLhs — ported from test/libsolidity/semanticTests/operators/shifts/shift_left_larger_type.sol
// Stresses: a shift count wider than the operand
// Variant: constSource=constexpr entryOrder=declared entryShape=direct initStyle=absent placement=nested stateOrder=declared temporaries=stateScratch width=uint32
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

static constexpr uint8 FIXED_COUNT = 254;

struct ShiftRhsWiderThanLhs2
{
};

struct ShiftRhsWiderThanLhs : public ContractBase
{
    struct Scratch
    {
        uint32 shiftShifted;
    };

    struct StateData
    {
        struct Inner
        {
        sint64 wide;
        uint32 narrow;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        sint64 wide;
        uint32 narrow;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.wide = state.get().inner.wide;
        output.narrow = state.get().inner.narrow;
    }

    struct Shift_input
    {
        uint32 value;
        uint8 count;
    };

    struct Shift_output {};

    PUBLIC_PROCEDURE(Shift)
    {
        state.mut().inner.scratch.shiftShifted = input.value << FIXED_COUNT;
        state.mut().inner.narrow = state.mut().inner.scratch.shiftShifted;
        state.mut().inner.wide = (sint64)state.mut().inner.scratch.shiftShifted;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Shift, 1);
    }
};
