// SignExtendWidening — ported from test/libsolidity/semanticTests/types/convert_signed_to_wider.sol
// Stresses: sign extension when a negative narrow value widens — the bug that shows up as a huge positive number
// Variant: entryOrder=declared entryShape=direct initStyle=absent placement=nested stateOrder=reversed temporaries=stateScratch width=uint32
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SignExtendWidening2
{
};

struct SignExtendWidening : public ContractBase
{
    struct Scratch
    {
        sint64 runScratch;
    };

    struct StateData
    {
        struct Inner
        {
        sint64 widened;
        sint32 narrow;
        uint64 calls;
        uint64 accumulator;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 accumulator;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.accumulator = state.get().inner.accumulator;
        output.calls = state.get().inner.calls;
    }

    struct Run_input
    {
        sint32 value;
    };

    struct Run_output {};

    PUBLIC_PROCEDURE(Run)
    {
        state.mut().inner.narrow = input.value;
        state.mut().inner.scratch.runScratch = (sint64)state.get().inner.narrow;
        state.mut().inner.widened = state.mut().inner.scratch.runScratch;
        state.mut().inner.accumulator += (uint64)state.mut().inner.scratch.runScratch;

        state.mut().inner.calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }
};
