// SignedMinDivMinusOne — ported from test/libsolidity/semanticTests/arithmetics/signed_division.sol
// Stresses: INT_MIN / -1, the one signed division that genuinely overflows and traps on wasm
// Port caveat: Solidity panics 0x11; on wasm this is a real trap, so both backends must trap at the same step.
// Variant: entryOrder=reversed entryShape=direct initStyle=absent placement=first stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SignedMinDivMinusOne2
{
};

struct SignedMinDivMinusOne : public ContractBase
{
    struct Scratch
    {
        sint64 runScratch;
    };

    struct StateData
    {
        uint64 calls;
        uint64 accumulator;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Run_input
    {
        sint64 value;
        sint64 divisor;
    };

    struct Run_output {};

    PUBLIC_PROCEDURE(Run)
    {
        state.mut().scratch.runScratch = QPI::div(input.value, input.divisor);
        state.mut().accumulator += (uint64)state.mut().scratch.runScratch;

        state.mut().calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 accumulator;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.accumulator = state.get().accumulator;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }
};
