// SignedAccumulatorAcrossZero — ported from test/libsolidity/semanticTests/arithmetics/signed_accumulation.sol
// Stresses: an accumulator driven across zero in both directions with the crossing counted — the one archetype here that does accumulate, so its state depends on the whole script rather than one pair
// Variant: entryOrder=declared entryShape=direct initStyle=full placement=last stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SignedAccumulatorAcrossZero2
{
};

struct SignedAccumulatorAcrossZero : public ContractBase
{
    struct Scratch
    {
        sint64 runBefore;
        sint64 runDelta;
    };

    struct StateData
    {
        uint64 placementGuard;
        sint64 total;
        uint64 crossings;
        sint64 lowWater;
        sint64 highWater;
        uint64 calls;
        Scratch scratch;
    };

    struct Read_input {};

    struct Read_output
    {
        sint64 total;
        uint64 crossings;
        sint64 lowWater;
        sint64 highWater;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.total = state.get().total;
        output.crossings = state.get().crossings;
        output.lowWater = state.get().lowWater;
        output.highWater = state.get().highWater;
        output.calls = state.get().calls;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    PUBLIC_PROCEDURE(Run)
    {
        state.mut().scratch.runBefore = state.get().total;
        state.mut().scratch.runDelta = (sint64)input.a;
        state.mut().total = state.mut().scratch.runBefore + state.mut().scratch.runDelta;
        if ((state.mut().scratch.runBefore < 0) != (state.get().total < 0))
        {
        state.mut().crossings++;
        }
        if (state.get().total < state.get().lowWater)
        {
        state.mut().lowWater = state.get().total;
        }
        if (state.get().total > state.get().highWater)
        {
        state.mut().highWater = state.get().total;
        }

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().total = 0;
        state.mut().crossings = 0;
        state.mut().lowWater = 0;
        state.mut().highWater = 0;
        state.mut().calls = 0;
    }
};
