// SignedComparisonChain — ported from test/libsolidity/semanticTests/expressions/comparison_operators.sol
// Stresses: all six comparison operators evaluated on one signed pair and packed into a bitfield, so a single wrong comparison changes one bit of a number
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=empty placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SignedComparisonChain2
{
};

struct SignedComparisonChain : public ContractBase
{
    struct Scratch
    {
        sint64 runLeft;
        sint64 runRight;
        uint64 runBits;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 calls;
        sint64 rhs;
        sint64 lhs;
        uint64 trueCount;
        uint64 packed;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 packed;
        uint64 trueCount;
        sint64 lhs;
        sint64 rhs;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.packed = state.get().inner.packed;
        output.trueCount = state.get().inner.trueCount;
        output.lhs = state.get().inner.lhs;
        output.rhs = state.get().inner.rhs;
        output.calls = state.get().inner.calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    PRIVATE_PROCEDURE(RunBody)
    {
        state.mut().inner.scratch.runLeft = (sint64)input.a;
        state.mut().inner.scratch.runRight = (sint64)input.b;
        state.mut().inner.scratch.runBits = 0;
        state.mut().inner.scratch.runBits = state.mut().inner.scratch.runBits | (state.mut().inner.scratch.runLeft < state.mut().inner.scratch.runRight ? 1ULL : 0ULL);
        state.mut().inner.scratch.runBits = state.mut().inner.scratch.runBits | (state.mut().inner.scratch.runLeft <= state.mut().inner.scratch.runRight ? 2ULL : 0ULL);
        state.mut().inner.scratch.runBits = state.mut().inner.scratch.runBits | (state.mut().inner.scratch.runLeft == state.mut().inner.scratch.runRight ? 4ULL : 0ULL);
        state.mut().inner.scratch.runBits = state.mut().inner.scratch.runBits | (state.mut().inner.scratch.runLeft != state.mut().inner.scratch.runRight ? 8ULL : 0ULL);
        state.mut().inner.scratch.runBits = state.mut().inner.scratch.runBits | (state.mut().inner.scratch.runLeft >= state.mut().inner.scratch.runRight ? 16ULL : 0ULL);
        state.mut().inner.scratch.runBits = state.mut().inner.scratch.runBits | (state.mut().inner.scratch.runLeft > state.mut().inner.scratch.runRight ? 32ULL : 0ULL);
        state.mut().inner.packed = state.mut().inner.scratch.runBits;
        state.mut().inner.trueCount = (state.mut().inner.scratch.runBits & 1) + ((state.mut().inner.scratch.runBits >> 1) & 1) + ((state.mut().inner.scratch.runBits >> 2) & 1) + ((state.mut().inner.scratch.runBits >> 3) & 1) + ((state.mut().inner.scratch.runBits >> 4) & 1) + ((state.mut().inner.scratch.runBits >> 5) & 1);
        state.mut().inner.lhs = state.mut().inner.scratch.runLeft;
        state.mut().inner.rhs = state.mut().inner.scratch.runRight;

        state.mut().inner.calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
