// SignedShiftRightIsArithmetic — ported from test/libsolidity/semanticTests/operators/shifts/shift_right_negative_lvalue.sol
// Stresses: arithmetic shift right on negative values, next to the logical shift of the same bits reinterpreted as unsigned — the pair that shows the sign bit being replicated
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=absent placement=first stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SignedShiftRightIsArithmetic2
{
};

struct SignedShiftRightIsArithmetic : public ContractBase
{
    struct StateData
    {
        uint64 calls;
        uint64 shiftMatchesDivision;
        sint64 dividedByPowerOfTwo;
        uint64 logical;
        sint64 arithmetic;
        uint64 placementGuard;
    };

    struct Read_input {};

    struct Read_output
    {
        sint64 arithmetic;
        uint64 logical;
        sint64 dividedByPowerOfTwo;
        uint64 shiftMatchesDivision;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.arithmetic = state.get().arithmetic;
        output.logical = state.get().logical;
        output.dividedByPowerOfTwo = state.get().dividedByPowerOfTwo;
        output.shiftMatchesDivision = state.get().shiftMatchesDivision;
        output.calls = state.get().calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    struct RunBody_locals
    {
        sint64 value;
        uint64 asUnsigned;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RunBody)
    {
        locals.value = (sint64)input.a;
        locals.asUnsigned = input.a;
        state.mut().arithmetic = locals.value >> 2;
        state.mut().logical = locals.asUnsigned >> 2;
        state.mut().dividedByPowerOfTwo = QPI::div(locals.value, (sint64)4);
        state.mut().shiftMatchesDivision = state.get().arithmetic == state.get().dividedByPowerOfTwo ? 1 : 0;

        state.mut().calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }
};
