// SignedShiftRightIsArithmetic — ported from test/libsolidity/semanticTests/operators/shifts/shift_right_negative_lvalue.sol
// Stresses: arithmetic shift right on negative values, next to the logical shift of the same bits reinterpreted as unsigned — the pair that shows the sign bit being replicated
// Variant: entryOrder=reversed entryShape=direct initStyle=full placement=first stateOrder=declared temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SignedShiftRightIsArithmetic2
{
};

struct SignedShiftRightIsArithmetic : public ContractBase
{
    struct Scratch
    {
        sint64 runValue;
        uint64 runAsUnsigned;
    };

    struct StateData
    {
        sint64 arithmetic;
        uint64 logical;
        sint64 dividedByPowerOfTwo;
        uint64 shiftMatchesDivision;
        uint64 calls;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    PUBLIC_PROCEDURE(Run)
    {
        state.mut().scratch.runValue = (sint64)input.a;
        state.mut().scratch.runAsUnsigned = input.a;
        state.mut().arithmetic = state.mut().scratch.runValue >> 2;
        state.mut().logical = state.mut().scratch.runAsUnsigned >> 2;
        state.mut().dividedByPowerOfTwo = QPI::div(state.mut().scratch.runValue, (sint64)4);
        state.mut().shiftMatchesDivision = state.get().arithmetic == state.get().dividedByPowerOfTwo ? 1 : 0;

        state.mut().calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        sint64 arithmetic;
        uint64 logical;
        sint64 dividedByPowerOfTwo;
        uint64 shiftMatchesDivision;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.arithmetic = state.get().arithmetic;
        output.logical = state.get().logical;
        output.dividedByPowerOfTwo = state.get().dividedByPowerOfTwo;
        output.shiftMatchesDivision = state.get().shiftMatchesDivision;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().arithmetic = 0;
        state.mut().logical = 0;
        state.mut().dividedByPowerOfTwo = 0;
        state.mut().shiftMatchesDivision = 0;
        state.mut().calls = 0;
    }
};
