// SignedNarrowingKeepsSignBit — ported from test/libsolidity/semanticTests/cleanup/cleanup_bytes_types.sol
// Stresses: a value narrowed into sint8 and sint16 and widened back to sint64, where the sign bit of the narrow type decides whether the result comes back negative
// Variant: entryOrder=reversed entryShape=direct initStyle=absent placement=first stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SignedNarrowingKeepsSignBit2
{
};

struct SignedNarrowingKeepsSignBit : public ContractBase
{
    struct Scratch
    {
        sint8 runAsByte;
        sint16 runAsWord;
    };

    struct StateData
    {
        uint64 calls;
        uint64 negativeCount;
        sint64 fromWord;
        sint64 fromByte;
        Scratch scratch;
        uint64 placementGuard;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    PUBLIC_PROCEDURE(Run)
    {
        state.mut().scratch.runAsByte = (sint8)input.a;
        state.mut().scratch.runAsWord = (sint16)input.a;
        state.mut().fromByte = (sint64)state.mut().scratch.runAsByte;
        state.mut().fromWord = (sint64)state.mut().scratch.runAsWord;
        if (state.get().fromByte < 0)
        {
        state.mut().negativeCount++;
        }

        state.mut().calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        sint64 fromByte;
        sint64 fromWord;
        uint64 negativeCount;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.fromByte = state.get().fromByte;
        output.fromWord = state.get().fromWord;
        output.negativeCount = state.get().negativeCount;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }
};
