// SignedAbsoluteValue — ported from openzeppelin-contracts/contracts/utils/math/SignedMath.sol (abs)
// Stresses: absolute value three ways — a branch, a ternary and the sign-mask trick — on operands including the minimum, where the true absolute value does not fit in the type
// Variant: entryOrder=reversed entryShape=direct initStyle=empty placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SignedAbsoluteValue2
{
};

struct SignedAbsoluteValue : public ContractBase
{
    struct Scratch
    {
        sint64 runValue;
        sint64 runMask;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 calls;
        uint64 allAgree;
        uint64 viaMask;
        uint64 viaTernary;
        uint64 viaBranch;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    PUBLIC_PROCEDURE(Run)
    {
        state.mut().inner.scratch.runValue = (sint64)input.a;
        if (state.mut().inner.scratch.runValue < 0)
        {
        state.mut().inner.viaBranch = (uint64)(0 - state.mut().inner.scratch.runValue);
        }
        else
        {
        state.mut().inner.viaBranch = (uint64)state.mut().inner.scratch.runValue;
        }
        state.mut().inner.viaTernary = state.mut().inner.scratch.runValue < 0 ? (uint64)(0 - state.mut().inner.scratch.runValue) : (uint64)state.mut().inner.scratch.runValue;
        state.mut().inner.scratch.runMask = state.mut().inner.scratch.runValue >> 63;
        state.mut().inner.viaMask = (uint64)((state.mut().inner.scratch.runValue + state.mut().inner.scratch.runMask) ^ state.mut().inner.scratch.runMask);
        state.mut().inner.allAgree = state.get().inner.viaBranch == state.get().inner.viaTernary && state.get().inner.viaBranch == state.get().inner.viaMask ? 1 : 0;

        state.mut().inner.calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 viaBranch;
        uint64 viaTernary;
        uint64 viaMask;
        uint64 allAgree;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.viaBranch = state.get().inner.viaBranch;
        output.viaTernary = state.get().inner.viaTernary;
        output.viaMask = state.get().inner.viaMask;
        output.allAgree = state.get().inner.allAgree;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
