// SignExtendWidening — ported from test/libsolidity/semanticTests/types/convert_signed_to_wider.sol
// Stresses: sign extension when a negative narrow value widens — the bug that shows up as a huge positive number
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=empty placement=nested stateOrder=declared temporaries=stateScratch width=sint64
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SignExtendWidening2
{
};

struct SignExtendWidening : public ContractBase
{
    struct Scratch
    {
        sint64 runScratch;
    };

    struct StateData
    {
        struct Inner
        {
        uint64 accumulator;
        uint64 calls;
        sint64 narrow;
        sint64 widened;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Run_input
    {
        sint64 value;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 accumulator;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    PRIVATE_PROCEDURE(RunBody)
    {
        state.mut().inner.narrow = input.value;
        state.mut().inner.scratch.runScratch = (sint64)state.get().inner.narrow;
        state.mut().inner.widened = state.mut().inner.scratch.runScratch;
        state.mut().inner.accumulator += (uint64)state.mut().inner.scratch.runScratch;

        state.mut().inner.calls++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.accumulator = state.get().inner.accumulator;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
