// SignedToUnsignedRoundTrip — ported from test/libsolidity/semanticTests/types/mixed_signed_unsigned_comparison.sol
// Stresses: a signed value cast to unsigned and back, with the bit pattern preserved through both hops — and the same value compared before and after, where the ordering reverses
// Variant: entryOrder=reversed entryShape=direct initStyle=empty placement=nested stateOrder=declared temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SignedToUnsignedRoundTrip2
{
};

struct SignedToUnsignedRoundTrip : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 asUnsigned;
        sint64 backAgain;
        uint64 roundTrips;
        uint64 orderingFlipped;
        uint64 calls;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        sint64 value;
        uint64 unsignedValue;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.value = (sint64)input.a;
        locals.unsignedValue = (uint64)locals.value;
        state.mut().inner.asUnsigned = locals.unsignedValue;
        state.mut().inner.backAgain = (sint64)locals.unsignedValue;
        state.mut().inner.roundTrips = state.get().inner.backAgain == locals.value ? 1 : 0;
        state.mut().inner.orderingFlipped = (locals.value < 0) && (locals.unsignedValue > 9223372036854775807ULL) ? 1 : 0;

        state.mut().inner.calls++;
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 asUnsigned;
        sint64 backAgain;
        uint64 roundTrips;
        uint64 orderingFlipped;
        uint64 calls;
    };

    PUBLIC_FUNCTION(Read)
    {
        output.asUnsigned = state.get().inner.asUnsigned;
        output.backAgain = state.get().inner.backAgain;
        output.roundTrips = state.get().inner.roundTrips;
        output.orderingFlipped = state.get().inner.orderingFlipped;
        output.calls = state.get().inner.calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
