// SignedMinDivMinusOne — ported from test/libsolidity/semanticTests/arithmetics/signed_division.sol
// Stresses: INT_MIN / -1, the one signed division that genuinely overflows and traps on wasm
// Port caveat: Solidity panics 0x11; on wasm this is a real trap, so both backends must trap at the same step.
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full placement=nested stateOrder=reversed temporaries=locals
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct SignedMinDivMinusOne2
{
};

struct SignedMinDivMinusOne : public ContractBase
{
    struct StateData
    {
        struct Inner
        {
        uint64 calls;
        uint64 accumulator;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 accumulator;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        sint64 value;
        sint64 divisor;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.accumulator = state.get().inner.accumulator;
        output.calls = state.get().inner.calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    struct RunBody_locals
    {
        sint64 scratch;
    };

    PRIVATE_PROCEDURE_WITH_LOCALS(RunBody)
    {
        locals.scratch = QPI::div(input.value, input.divisor);
        state.mut().inner.accumulator += (uint64)locals.scratch;

        state.mut().inner.calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.accumulator = 0;
        state.mut().inner.calls = 0;
    }
};
