// U128AddCarry — ported from test/libsolidity/semanticTests/arithmetics/checked_add_v2.sol
// Stresses: uint128 addition across the 64-bit limb boundary — the carry the wide type needs and uint64 cannot show
// Port caveat: Stands in for Solidity's uint256 where the value exceeds 64 bits; the boundary moves from 2^256 to 2^128.
// Variant: entryOrder=declared entryShape=viaPrivate initStyle=full placement=nested stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct U128AddCarry2
{
};

struct U128AddCarry : public ContractBase
{
    struct Scratch
    {
        uint128 runScratch;
    };

    struct StateData
    {
        struct Inner
        {
        uint128 wide;
        uint64 calls;
        uint64 accumulator;
        Scratch scratch;
        };
        uint64 placementGuard;
        Inner inner;
    };

    struct Read_input {};

    struct Read_output
    {
        uint64 accumulator;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    struct Run_input
    {
        uint128 a;
        uint128 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.accumulator = state.get().inner.accumulator;
        output.calls = state.get().inner.calls;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    PRIVATE_PROCEDURE(RunBody)
    {
        state.mut().inner.scratch.runScratch = input.a + input.b;
        state.mut().inner.wide = state.mut().inner.scratch.runScratch;
        state.mut().inner.accumulator++;

        state.mut().inner.calls++;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {
        state.mut().inner.accumulator = 0;
        state.mut().inner.calls = 0;
    }
};
