// WideFixedPointMultiply — ported from abdk-libraries-solidity/ABDKMath64x64.sol (mul)
// Stresses: Q32.32 fixed-point multiply with the rounding step written out — a shift right by 32 after a product that may already have lost the high half
// Port caveat: ABDK works in 64.64 over int128; the port is 32.32 over uint64, so the precision loss arrives sooner and is part of what is being compared.
// Variant: entryOrder=reversed entryShape=viaPrivate initStyle=empty placement=last stateOrder=reversed temporaries=stateScratch
// Generated by scripts/solidity-port/generate.ts. Do not edit; edit the archetype instead.
using namespace QPI;

struct WideFixedPointMultiply2
{
};

struct WideFixedPointMultiply : public ContractBase
{
    struct Scratch
    {
        uint64 runProduct;
        uint64 runRounded;
    };

    struct StateData
    {
        uint64 placementGuard;
        uint64 calls;
        uint64 lostPrecision;
        uint64 productTruncated;
        uint64 productRounded;
        Scratch scratch;
    };

    struct Run_input
    {
        uint64 a;
        uint64 b;
    };

    struct Run_output {};

    struct Run_locals
    {
        Run_input forwardedInput;
        Run_output forwardedOutput;
    };

    PUBLIC_PROCEDURE_WITH_LOCALS(Run)
    {
        locals.forwardedInput = input;
        CALL(RunBody, locals.forwardedInput, locals.forwardedOutput);
    }

    struct Read_input {};

    struct Read_output
    {
        uint64 productRounded;
        uint64 productTruncated;
        uint64 lostPrecision;
        uint64 calls;
    };

    struct Read_locals
    {
        Read_input forwardedInput;
        Read_output forwardedOutput;
    };

    PUBLIC_FUNCTION_WITH_LOCALS(Read)
    {
        CALL(ReadBody, locals.forwardedInput, locals.forwardedOutput);
        output = locals.forwardedOutput;
    }

    using RunBody_input = Run_input;

    using RunBody_output = Run_output;

    PRIVATE_PROCEDURE(RunBody)
    {
        state.mut().scratch.runProduct = (input.a >> 16) * (input.b >> 16);
        state.mut().productTruncated = state.mut().scratch.runProduct >> 32;
        state.mut().scratch.runRounded = (state.mut().scratch.runProduct + 2147483648ULL) >> 32;
        state.mut().productRounded = state.mut().scratch.runRounded;
        if (state.mut().scratch.runRounded != (state.mut().scratch.runProduct >> 32))
        {
        state.mut().lostPrecision++;
        }

        state.mut().calls++;
    }

    using ReadBody_input = Read_input;

    using ReadBody_output = Read_output;

    PRIVATE_FUNCTION(ReadBody)
    {
        output.productRounded = state.get().productRounded;
        output.productTruncated = state.get().productTruncated;
        output.lostPrecision = state.get().lostPrecision;
        output.calls = state.get().calls;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(Read, 1);
        REGISTER_USER_PROCEDURE(Run, 1);
    }

    INITIALIZE()
    {

    }
};
