// Starter contracts for `qinit new --template`. Name-agnostic (use the CONTRACT_STATE_TYPE macro);
// each is a proven, qpi.h-constrained contract. Header line replaced per-template at scaffold time.
export type TemplateKind = "counter" | "hashmap" | "asset" | "intercontract";
export const TEMPLATE_KINDS: TemplateKind[] = ["counter", "hashmap", "asset", "intercontract"];

const HEAD = "// Generated by `qinit new`. qpi.h-constrained dynamic contract.\n";

const counter = `using namespace QPI;

struct CONTRACT_STATE2_TYPE
{
};

struct CONTRACT_STATE_TYPE : public ContractBase
{
    struct StateData
    {
        uint64 counter;
    };

    struct Inc_input {};
    struct Inc_output {};
    struct Get_input {};
    struct Get_output { uint64 value; };

    PUBLIC_PROCEDURE(Inc)
    {
        state.mut().counter += 1;
    }

    PUBLIC_FUNCTION(Get)
    {
        output.value = state.get().counter;
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_PROCEDURE(Inc, 1);
        REGISTER_USER_FUNCTION(Get, 1);
    }

    INITIALIZE()
    {
        state.mut().counter = 0;
    }
};
`;

const hashmap = `using namespace QPI;

struct CONTRACT_STATE2_TYPE
{
};

struct CONTRACT_STATE_TYPE : public ContractBase
{
    struct StateData
    {
        HashMap<id, uint64, 1024> balances;
        uint64 total;
    };

    struct Set_input { id who; uint64 amount; };
    struct Set_output {};
    struct BalanceOf_input { id who; };
    struct BalanceOf_output { uint64 amount; };
    struct Stats_input {};
    struct Stats_output { uint64 total; uint64 population; };

    PUBLIC_PROCEDURE(Set)
    {
        state.mut().balances.set(input.who, input.amount);
        state.mut().total += input.amount;
    }

    struct BalanceOf_locals { uint64 v; };
    PUBLIC_FUNCTION_WITH_LOCALS(BalanceOf)
    {
        locals.v = 0;
        state.get().balances.get(input.who, locals.v);
        output.amount = locals.v;
    }

    PUBLIC_FUNCTION(Stats)
    {
        output.total = state.get().total;
        output.population = state.get().balances.population();
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_PROCEDURE(Set, 1);
        REGISTER_USER_FUNCTION(BalanceOf, 1);
        REGISTER_USER_FUNCTION(Stats, 2);
    }

    INITIALIZE()
    {
        state.mut().total = 0;
        state.mut().balances.reset();
    }
};
`;

const asset = `using namespace QPI;

struct CONTRACT_STATE2_TYPE
{
};

// Issues its own asset (issuer = SELF) and can move shares to another id.
struct CONTRACT_STATE_TYPE : public ContractBase
{
    struct StateData
    {
        sint64 lastResult;
    };

    struct Issue_input { uint64 name; sint64 shares; };
    struct Issue_output { sint64 result; };
    struct Total_input { uint64 name; };
    struct Total_output { sint64 shares; };
    struct Move_input { uint64 name; id to; sint64 shares; };
    struct Move_output { sint64 result; };

    PUBLIC_PROCEDURE(Issue)
    {
        output.result = qpi.issueAsset(input.name, SELF, 0, input.shares, 0);
        state.mut().lastResult = output.result;
    }

    PUBLIC_PROCEDURE(Move)
    {
        output.result = qpi.transferShareOwnershipAndPossession(input.name, SELF, SELF, SELF, input.shares, input.to);
        state.mut().lastResult = output.result;
    }

    struct Total_locals { QPI::Asset a; };   // QPI:: qualified so it never clashes with a contract named "Asset"
    PUBLIC_FUNCTION_WITH_LOCALS(Total)
    {
        locals.a.issuer = SELF;
        locals.a.assetName = input.name;
        output.shares = qpi.numberOfShares(locals.a, AssetOwnershipSelect::any(), AssetPossessionSelect::any());
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_PROCEDURE(Issue, 1);
        REGISTER_USER_PROCEDURE(Move, 2);
        REGISTER_USER_FUNCTION(Total, 1);
    }

    INITIALIZE()
    {
        state.mut().lastResult = 0;
    }
};
`;

const intercontract = `// Calls the Counter contract at a LOWER slot. Deploy Counter first, then:
//   qinit deploy --callee Counter=/abs/path/Counter.h@<counter-slot>
using namespace QPI;

struct CONTRACT_STATE2_TYPE
{
};

struct CONTRACT_STATE_TYPE : public ContractBase
{
    struct StateData
    {
        uint64 dummy;
    };

    struct ReadCounter_input {};
    struct ReadCounter_output { uint64 value; };
    struct BumpCounter_input {};
    struct BumpCounter_output {};

    struct ReadCounter_locals { Counter::Get_input gi; Counter::Get_output go; };
    PUBLIC_FUNCTION_WITH_LOCALS(ReadCounter)
    {
        CALL_OTHER_CONTRACT_FUNCTION(Counter, Get, locals.gi, locals.go);
        output.value = locals.go.value;
    }

    struct BumpCounter_locals { Counter::Inc_input ii; Counter::Inc_output io; };
    PUBLIC_PROCEDURE_WITH_LOCALS(BumpCounter)
    {
        INVOKE_OTHER_CONTRACT_PROCEDURE(Counter, Inc, locals.ii, locals.io, 0);
    }

    REGISTER_USER_FUNCTIONS_AND_PROCEDURES()
    {
        REGISTER_USER_FUNCTION(ReadCounter, 1);
        REGISTER_USER_PROCEDURE(BumpCounter, 1);
    }

    INITIALIZE()
    {
        state.mut().dummy = 0;
    }
};
`;

const BODIES: Record<TemplateKind, string> = { counter, hashmap, asset, intercontract };
export const TEMPLATE_NOTE: Partial<Record<TemplateKind, string>> = {
  intercontract:
    "Counter callee scaffolded + auto-deployed on `qinit test`; for `qinit deploy`, deploy Counter first (or it resolves from the node registry)",
};

export function templateSource(kind: TemplateKind): string {
  return HEAD + BODIES[kind];
}
